// Code generated by the generate package DO NOT EDIT

/*
An Omnidirectional light is a type of [Light3D] that emits light in all directions. The light is attenuated by distance and this attenuation can be configured by changing its energy, radius, and attenuation parameters.

Note: When using the Mobile rendering method, only 8 omni lights can be displayed on each mesh resource. Attempting to display more than 8 omni lights on a single mesh resource will result in omni lights flickering in and out as the camera moves. When using the Compatibility rendering method, only 8 omni lights can be displayed on each mesh resource by default, but this can be increased by adjusting [ProjectSettings] "rendering/limits/opengl/max_lights_per_object".

Note: When using the Mobile or Compatibility rendering methods, omni lights will only correctly affect meshes whose visibility AABB intersects with the light's AABB. If using a shader to deform the mesh in a way that makes it go outside its AABB, [GeometryInstance3D.ExtraCullMargin] must be increased on the mesh. Otherwise, the light may not be visible on the mesh.

[GeometryInstance3D.ExtraCullMargin]: https://pkg.go.dev/graphics.gd/classdb/GeometryInstance3D#Instance.ExtraCullMargin
[Light3D]: https://pkg.go.dev/graphics.gd/classdb/Light3D
[ProjectSettings]: https://pkg.go.dev/graphics.gd/classdb/ProjectSettings
*/
package OmniLight3D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Light3D"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Node3D"
import "graphics.gd/classdb/VisualInstance3D"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.OmniLight3D

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_shadow_mode gdextension.MethodForClass `hash:"121862228"`
	get_shadow_mode gdextension.MethodForClass `hash:"4181586331"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("OmniLight3D")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsOmniLight3D() Instance
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.OmniLight3D

func (o class) AsObject() [1]gd.Object { return *(*[1]gd.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewOmniLight3D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewOmniLight3D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gd.Object      { return *(*[1]gd.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gd.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.OmniLight3D{gdclass.NewOmniLight3D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetOmniLight3D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.OmniLight3D{gdclass.NewOmniLight3D(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) OmniShadowMode() ShadowMode { //gd:OmniLight3D.omni_shadow_mode
	return ShadowMode(class(self).GetShadowMode())
}

// SetOmniShadowMode sets the property returned by [GetShadowMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetOmniShadowMode(value ShadowMode) Instance { //gd:OmniLight3D.omni_shadow_mode
	class(self).SetShadowMode(value)
	return self
}

func (self class) SetShadowMode(mode ShadowMode) { //gd:OmniLight3D.set_shadow_mode
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_shadow_mode, 0|(gdextension.SizeInt<<4), &struct{ mode ShadowMode }{mode})
}
func (self class) GetShadowMode() ShadowMode { //gd:OmniLight3D.get_shadow_mode
	var r_ret = jumponly.Call[ShadowMode](gd.ObjectChecked(self.AsObject()), methods.get_shadow_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsOmniLight3D() Advanced             { return Advanced(o) }
func (o Instance) AsOmniLight3D() Instance          { return o }
func (o *Extension[T]) AsOmniLight3D() Instance     { return o.Super() }
func (o class) AsLight3D() Light3D.Advanced         { return *(*Light3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsLight3D() Light3D.Instance { return o.Super().AsLight3D() }
func (o Instance) AsLight3D() Light3D.Instance      { return *(*Light3D.Instance)(ie.As(&o)) }
func (o class) AsVisualInstance3D() VisualInstance3D.Advanced {
	return *(*VisualInstance3D.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsVisualInstance3D() VisualInstance3D.Instance {
	return o.Super().AsVisualInstance3D()
}
func (o Instance) AsVisualInstance3D() VisualInstance3D.Instance {
	return *(*VisualInstance3D.Instance)(ie.As(&o))
}
func (o class) AsNode3D() Node3D.Advanced         { return *(*Node3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode3D() Node3D.Instance { return o.Super().AsNode3D() }
func (o Instance) AsNode3D() Node3D.Instance      { return *(*Node3D.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced             { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance     { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance          { return *(*Node.Instance)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Light3D.Advanced(self.AsLight3D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Light3D.Instance(self.AsLight3D()), name)
	}
}
func init() {
	gdclass.Register("OmniLight3D", func(ptr gd.Object) any { return Instance{gdclass.NewOmniLight3D(ptr)} })
}

type ShadowMode int64 //gd:OmniLight3D.ShadowMode

const (
	// Shadows are rendered to a dual-paraboloid texture. Faster than [ShadowCube], but lower-quality.
	ShadowDualParaboloid ShadowMode = 0
	// Shadows are rendered to a cubemap. Slower than [ShadowDualParaboloid], but higher-quality.
	ShadowCube ShadowMode = 1
)
