// Code generated by the generate package DO NOT EDIT

/*
A container used to provide a child control with scrollbars when needed. Scrollbars will automatically be drawn at the right (for vertical) or bottom (for horizontal) and will enable dragging to move the viewable Control (and its children) within the ScrollContainer. Scrollbars will also automatically resize the grabber based on the [Control.CustomMinimumSize] of the Control relative to the ScrollContainer.

[Control.CustomMinimumSize]: https://pkg.go.dev/graphics.gd/classdb/Control#Instance.CustomMinimumSize
*/
package ScrollContainer

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gdunsafe "graphics.gd"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/CanvasItem"
import "graphics.gd/classdb/Container"
import "graphics.gd/classdb/Control"
import "graphics.gd/classdb/HScrollBar"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/VScrollBar"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ gdunsafe.Object
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.ScrollContainer

var otype gdunsafe.ObjectType
var sname gdextension.StringName
var methods struct {
	set_h_scroll               gdextension.MethodForClass `hash:"1286410249"`
	get_h_scroll               gdextension.MethodForClass `hash:"3905245786"`
	set_v_scroll               gdextension.MethodForClass `hash:"1286410249"`
	get_v_scroll               gdextension.MethodForClass `hash:"3905245786"`
	set_horizontal_custom_step gdextension.MethodForClass `hash:"373806689"`
	get_horizontal_custom_step gdextension.MethodForClass `hash:"1740695150"`
	set_vertical_custom_step   gdextension.MethodForClass `hash:"373806689"`
	get_vertical_custom_step   gdextension.MethodForClass `hash:"1740695150"`
	set_horizontal_scroll_mode gdextension.MethodForClass `hash:"2750506364"`
	get_horizontal_scroll_mode gdextension.MethodForClass `hash:"3987985145"`
	set_vertical_scroll_mode   gdextension.MethodForClass `hash:"2750506364"`
	get_vertical_scroll_mode   gdextension.MethodForClass `hash:"3987985145"`
	set_deadzone               gdextension.MethodForClass `hash:"1286410249"`
	get_deadzone               gdextension.MethodForClass `hash:"3905245786"`
	set_scroll_hint_mode       gdextension.MethodForClass `hash:"578158943"`
	get_scroll_hint_mode       gdextension.MethodForClass `hash:"246835423"`
	set_tile_scroll_hint       gdextension.MethodForClass `hash:"2586408642"`
	is_scroll_hint_tiled       gdextension.MethodForClass `hash:"2240911060"`
	set_follow_focus           gdextension.MethodForClass `hash:"2586408642"`
	is_following_focus         gdextension.MethodForClass `hash:"36873697"`
	get_h_scroll_bar           gdextension.MethodForClass `hash:"4004517983"`
	get_v_scroll_bar           gdextension.MethodForClass `hash:"2630340773"`
	ensure_control_visible     gdextension.MethodForClass `hash:"1496901182"`
	set_draw_focus_border      gdextension.MethodForClass `hash:"2586408642"`
	get_draw_focus_border      gdextension.MethodForClass `hash:"2240911060"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("ScrollContainer")
		otype = gdunsafe.ObjectTypeTag(gdunsafe.StringName(sname[0]))
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsScrollContainer() Instance
}

/*
Returns the horizontal scrollbar [HScrollBar] of this [ScrollContainer].

Warning: This is a required internal node, removing and freeing it may cause a crash. If you wish to disable or hide a scrollbar, you can use [HorizontalScrollMode].

[HScrollBar]: https://pkg.go.dev/graphics.gd/classdb/HScrollBar
[HorizontalScrollMode]: https://pkg.go.dev/graphics.gd/classdb/ScrollContainer#Instance.HorizontalScrollMode
[ScrollContainer]: https://pkg.go.dev/graphics.gd/classdb/ScrollContainer
*/
func (self Instance) GetHScrollBar() HScrollBar.Instance { //gd:ScrollContainer.get_h_scroll_bar
	return HScrollBar.Instance(Advanced(self).GetHScrollBar())
}

/*
Returns the vertical scrollbar [VScrollBar] of this [ScrollContainer].

Warning: This is a required internal node, removing and freeing it may cause a crash. If you wish to disable or hide a scrollbar, you can use [VerticalScrollMode].

[ScrollContainer]: https://pkg.go.dev/graphics.gd/classdb/ScrollContainer
[VScrollBar]: https://pkg.go.dev/graphics.gd/classdb/VScrollBar
[VerticalScrollMode]: https://pkg.go.dev/graphics.gd/classdb/ScrollContainer#Instance.VerticalScrollMode
*/
func (self Instance) GetVScrollBar() VScrollBar.Instance { //gd:ScrollContainer.get_v_scroll_bar
	return VScrollBar.Instance(Advanced(self).GetVScrollBar())
}

/*
Ensures the given 'control' is visible (must be a direct or indirect child of the ScrollContainer). Used by [FollowFocus].

Note: This will not work on a node that was just added during the same frame. If you want to scroll to a newly added child, you must wait until the next frame using [OnScenetree.ProcessFrame]:

	scrollContainer.AsNode().AddChild(control.AsNode())
	SceneTree.Get(scrollContainer.AsNode()).OnPhysicsFrame(func() {
		scrollContainer.EnsureControlVisible(control)
	})

[FollowFocus]: https://pkg.go.dev/graphics.gd/classdb/ScrollContainer#Instance.FollowFocus
[OnScenetree.ProcessFrame]: https://pkg.go.dev/graphics.gd/classdb/ScrollContainer#Instance.OnScenetree.ProcessFrame
*/
func (self Instance) EnsureControlVisible(control Control.Instance) { //gd:ScrollContainer.ensure_control_visible
	Advanced(self).EnsureControlVisible(control)
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.ScrollContainer

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewScrollContainer(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewScrollContainer(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.ScrollContainer{gdclass.NewScrollContainer(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetScrollContainer(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdunsafe.Object(raw).Free()
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.ScrollContainer{gdclass.NewScrollContainer(gdreference.OwnObject(gdextension.Object(gdunsafe.MakeObject(gdunsafe.StringName(sname[0]))), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
If true, the ScrollContainer will automatically scroll to focused children (including indirect children) to make sure they are fully visible.
*/
func (self Instance) FollowFocus() bool { //gd:ScrollContainer.follow_focus
	return bool(class(self).IsFollowingFocus())
}

// SetFollowFocus sets the property returned by [IsFollowingFocus]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFollowFocus(value bool) Instance { //gd:ScrollContainer.follow_focus
	class(self).SetFollowFocus(value)
	return self
}

/*
If true, theme's 'focus' is drawn when the ScrollContainer or one of its descendant nodes is focused.
*/
func (self Instance) DrawFocusBorder() bool { //gd:ScrollContainer.draw_focus_border
	return bool(class(self).GetDrawFocusBorder())
}

// SetDrawFocusBorder sets the property returned by [GetDrawFocusBorder]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDrawFocusBorder(value bool) Instance { //gd:ScrollContainer.draw_focus_border
	class(self).SetDrawFocusBorder(value)
	return self
}

/*
The current horizontal scroll value.

Note: If you are setting this value in the [Node.Ready] function or earlier, it needs to be wrapped with [Object.SetDeferred], since scroll bar's [Range.MaxValue] is not initialized yet.

[Node.Ready]: https://pkg.go.dev/graphics.gd/classdb/Node#Instance.Ready
[Object.SetDeferred]: https://pkg.go.dev/graphics.gd/variant/Object#SetDeferred
[Range.MaxValue]: https://pkg.go.dev/graphics.gd/classdb/Range#Instance.MaxValue
*/
func (self Instance) ScrollHorizontal() int { //gd:ScrollContainer.scroll_horizontal
	return int(int(class(self).GetHScroll()))
}

// SetScrollHorizontal sets the property returned by [GetHScroll]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollHorizontal(value int) Instance { //gd:ScrollContainer.scroll_horizontal
	class(self).SetHScroll(int64(value))
	return self
}

/*
The current vertical scroll value.

Note: Setting it early needs to be deferred, just like in [ScrollHorizontal].

[ScrollHorizontal]: https://pkg.go.dev/graphics.gd/classdb/ScrollContainer#Instance.ScrollHorizontal
*/
func (self Instance) ScrollVertical() int { //gd:ScrollContainer.scroll_vertical
	return int(int(class(self).GetVScroll()))
}

// SetScrollVertical sets the property returned by [GetVScroll]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollVertical(value int) Instance { //gd:ScrollContainer.scroll_vertical
	class(self).SetVScroll(int64(value))
	return self
}

/*
Overrides the [ScrollBar.CustomStep] used when clicking the internal scroll bar's horizontal increment and decrement buttons or when using arrow keys when the [ScrollBar] is focused.

[ScrollBar]: https://pkg.go.dev/graphics.gd/classdb/ScrollBar
[ScrollBar.CustomStep]: https://pkg.go.dev/graphics.gd/classdb/ScrollBar#Instance.CustomStep
*/
func (self Instance) ScrollHorizontalCustomStep() Float.X { //gd:ScrollContainer.scroll_horizontal_custom_step
	return Float.X(Float.X(class(self).GetHorizontalCustomStep()))
}

// SetScrollHorizontalCustomStep sets the property returned by [GetHorizontalCustomStep]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollHorizontalCustomStep(value Float.X) Instance { //gd:ScrollContainer.scroll_horizontal_custom_step
	class(self).SetHorizontalCustomStep(float64(value))
	return self
}

/*
Overrides the [ScrollBar.CustomStep] used when clicking the internal scroll bar's vertical increment and decrement buttons or when using arrow keys when the [ScrollBar] is focused.

[ScrollBar]: https://pkg.go.dev/graphics.gd/classdb/ScrollBar
[ScrollBar.CustomStep]: https://pkg.go.dev/graphics.gd/classdb/ScrollBar#Instance.CustomStep
*/
func (self Instance) ScrollVerticalCustomStep() Float.X { //gd:ScrollContainer.scroll_vertical_custom_step
	return Float.X(Float.X(class(self).GetVerticalCustomStep()))
}

// SetScrollVerticalCustomStep sets the property returned by [GetVerticalCustomStep]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollVerticalCustomStep(value Float.X) Instance { //gd:ScrollContainer.scroll_vertical_custom_step
	class(self).SetVerticalCustomStep(float64(value))
	return self
}

/*
Controls whether horizontal scrollbar can be used and when it should be visible.
*/
func (self Instance) HorizontalScrollMode() ScrollMode { //gd:ScrollContainer.horizontal_scroll_mode
	return ScrollMode(class(self).GetHorizontalScrollMode())
}

// SetHorizontalScrollMode sets the property returned by [GetHorizontalScrollMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetHorizontalScrollMode(value ScrollMode) Instance { //gd:ScrollContainer.horizontal_scroll_mode
	class(self).SetHorizontalScrollMode(value)
	return self
}

/*
Controls whether vertical scrollbar can be used and when it should be visible.
*/
func (self Instance) VerticalScrollMode() ScrollMode { //gd:ScrollContainer.vertical_scroll_mode
	return ScrollMode(class(self).GetVerticalScrollMode())
}

// SetVerticalScrollMode sets the property returned by [GetVerticalScrollMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetVerticalScrollMode(value ScrollMode) Instance { //gd:ScrollContainer.vertical_scroll_mode
	class(self).SetVerticalScrollMode(value)
	return self
}

/*
Deadzone for touch scrolling. Lower deadzone makes the scrolling more sensitive.
*/
func (self Instance) ScrollDeadzone() int { //gd:ScrollContainer.scroll_deadzone
	return int(int(class(self).GetDeadzone()))
}

// SetScrollDeadzone sets the property returned by [GetDeadzone]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollDeadzone(value int) Instance { //gd:ScrollContainer.scroll_deadzone
	class(self).SetDeadzone(int64(value))
	return self
}

/*
The way which scroll hints (indicators that show that the content can still be scrolled in a certain direction) will be shown.

Note: Hints won't be shown if the content can be scrolled both vertically and horizontally.
*/
func (self Instance) ScrollHintMode() ScrollHintMode { //gd:ScrollContainer.scroll_hint_mode
	return ScrollHintMode(class(self).GetScrollHintMode())
}

// SetScrollHintMode sets the property returned by [GetScrollHintMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollHintMode(value ScrollHintMode) Instance { //gd:ScrollContainer.scroll_hint_mode
	class(self).SetScrollHintMode(value)
	return self
}

/*
If true, the scroll hint texture will be tiled instead of stretched. See [ScrollHintMode].

[ScrollHintMode]: https://pkg.go.dev/graphics.gd/classdb/ScrollContainer#Instance.ScrollHintMode
*/
func (self Instance) TileScrollHint() bool { //gd:ScrollContainer.tile_scroll_hint
	return bool(class(self).IsScrollHintTiled())
}

// SetTileScrollHint sets the property returned by [IsScrollHintTiled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTileScrollHint(value bool) Instance { //gd:ScrollContainer.tile_scroll_hint
	class(self).SetTileScrollHint(value)
	return self
}

func (self class) SetHScroll(value int64) { //gd:ScrollContainer.set_h_scroll
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_h_scroll, 0|(gdextension.SizeInt<<4), &struct{ value int64 }{value})
}
func (self class) GetHScroll() int64 { //gd:ScrollContainer.get_h_scroll
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_h_scroll, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetVScroll(value int64) { //gd:ScrollContainer.set_v_scroll
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_v_scroll, 0|(gdextension.SizeInt<<4), &struct{ value int64 }{value})
}
func (self class) GetVScroll() int64 { //gd:ScrollContainer.get_v_scroll
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_v_scroll, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetHorizontalCustomStep(value float64) { //gd:ScrollContainer.set_horizontal_custom_step
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_horizontal_custom_step, 0|(gdextension.SizeFloat<<4), &struct{ value float64 }{value})
}
func (self class) GetHorizontalCustomStep() float64 { //gd:ScrollContainer.get_horizontal_custom_step
	var r_ret = noescape.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_horizontal_custom_step, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetVerticalCustomStep(value float64) { //gd:ScrollContainer.set_vertical_custom_step
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_vertical_custom_step, 0|(gdextension.SizeFloat<<4), &struct{ value float64 }{value})
}
func (self class) GetVerticalCustomStep() float64 { //gd:ScrollContainer.get_vertical_custom_step
	var r_ret = noescape.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_vertical_custom_step, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetHorizontalScrollMode(enable ScrollMode) { //gd:ScrollContainer.set_horizontal_scroll_mode
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_horizontal_scroll_mode, 0|(gdextension.SizeInt<<4), &struct{ enable ScrollMode }{enable})
}
func (self class) GetHorizontalScrollMode() ScrollMode { //gd:ScrollContainer.get_horizontal_scroll_mode
	var r_ret = jumponly.Call[ScrollMode](gd.ObjectChecked(self.AsObject()), methods.get_horizontal_scroll_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetVerticalScrollMode(enable ScrollMode) { //gd:ScrollContainer.set_vertical_scroll_mode
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_vertical_scroll_mode, 0|(gdextension.SizeInt<<4), &struct{ enable ScrollMode }{enable})
}
func (self class) GetVerticalScrollMode() ScrollMode { //gd:ScrollContainer.get_vertical_scroll_mode
	var r_ret = jumponly.Call[ScrollMode](gd.ObjectChecked(self.AsObject()), methods.get_vertical_scroll_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetDeadzone(deadzone int64) { //gd:ScrollContainer.set_deadzone
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_deadzone, 0|(gdextension.SizeInt<<4), &struct{ deadzone int64 }{deadzone})
}
func (self class) GetDeadzone() int64 { //gd:ScrollContainer.get_deadzone
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_deadzone, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetScrollHintMode(scroll_hint_mode ScrollHintMode) { //gd:ScrollContainer.set_scroll_hint_mode
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_scroll_hint_mode, 0|(gdextension.SizeInt<<4), &struct{ scroll_hint_mode ScrollHintMode }{scroll_hint_mode})
}
func (self class) GetScrollHintMode() ScrollHintMode { //gd:ScrollContainer.get_scroll_hint_mode
	var r_ret = jumponly.Call[ScrollHintMode](gd.ObjectChecked(self.AsObject()), methods.get_scroll_hint_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetTileScrollHint(tile_scroll_hint bool) { //gd:ScrollContainer.set_tile_scroll_hint
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_tile_scroll_hint, 0|(gdextension.SizeBool<<4), &struct{ tile_scroll_hint bool }{tile_scroll_hint})
}
func (self class) IsScrollHintTiled() bool { //gd:ScrollContainer.is_scroll_hint_tiled
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_scroll_hint_tiled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFollowFocus(enabled bool) { //gd:ScrollContainer.set_follow_focus
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_follow_focus, 0|(gdextension.SizeBool<<4), &struct{ enabled bool }{enabled})
}
func (self class) IsFollowingFocus() bool { //gd:ScrollContainer.is_following_focus
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_following_focus, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetHScrollBar() [1]gdclass.HScrollBar { //gd:ScrollContainer.get_h_scroll_bar
	var r_ret = jumponly.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_h_scroll_bar, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.HScrollBar{gdclass.NewHScrollBar(gd.PointerLifetimeBoundTo(self.AsObject(), r_ret))}
	return ret
}
func (self class) GetVScrollBar() [1]gdclass.VScrollBar { //gd:ScrollContainer.get_v_scroll_bar
	var r_ret = jumponly.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_v_scroll_bar, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.VScrollBar{gdclass.NewVScrollBar(gd.PointerLifetimeBoundTo(self.AsObject(), r_ret))}
	return ret
}
func (self class) EnsureControlVisible(control [1]gdclass.Control) { //gd:ScrollContainer.ensure_control_visible
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.ensure_control_visible, 0|(gdextension.SizeObject<<4), &struct{ control gdextension.Object }{gdextension.Object(gdreference.GetObject(gdclass.GetControl(control[0])[0]))})
}
func (self class) SetDrawFocusBorder(draw bool) { //gd:ScrollContainer.set_draw_focus_border
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_draw_focus_border, 0|(gdextension.SizeBool<<4), &struct{ draw bool }{draw})
}
func (self class) GetDrawFocusBorder() bool { //gd:ScrollContainer.get_draw_focus_border
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_draw_focus_border, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}

/*
Emitted when scrolling starts when dragging the scrollable area with a touch event. This signal is not emitted when scrolling by dragging the scrollbar, scrolling with the mouse wheel or scrolling with keyboard/gamepad events.

Note: This signal is only emitted on Android or iOS, or on desktop/web platforms when [ProjectSettings] "input_devices/pointing/emulate_touch_from_mouse" is enabled.

[ProjectSettings]: https://pkg.go.dev/graphics.gd/classdb/ProjectSettings
*/
func (self Instance) OnScrollStarted(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("scroll_started"), gd.NewCallable(cb), int64(flags_together))
	return self
}

func (self class) ScrollStarted() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`scroll_started`))))
}

/*
Emitted when scrolling stops when dragging the scrollable area with a touch event. This signal is not emitted when scrolling by dragging the scrollbar, scrolling with the mouse wheel or scrolling with keyboard/gamepad events.

Note: This signal is only emitted on Android or iOS, or on desktop/web platforms when [ProjectSettings] "input_devices/pointing/emulate_touch_from_mouse" is enabled.

[ProjectSettings]: https://pkg.go.dev/graphics.gd/classdb/ProjectSettings
*/
func (self Instance) OnScrollEnded(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("scroll_ended"), gd.NewCallable(cb), int64(flags_together))
	return self
}

func (self class) ScrollEnded() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`scroll_ended`))))
}

func (o class) AsScrollContainer() Advanced               { return Advanced(o) }
func (o Instance) AsScrollContainer() Instance            { return o }
func (o *Extension[T]) AsScrollContainer() Instance       { return o.Super() }
func (o class) AsContainer() Container.Advanced           { return *(*Container.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsContainer() Container.Instance   { return o.Super().AsContainer() }
func (o Instance) AsContainer() Container.Instance        { return *(*Container.Instance)(ie.As(&o)) }
func (o class) AsControl() Control.Advanced               { return *(*Control.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsControl() Control.Instance       { return o.Super().AsControl() }
func (o Instance) AsControl() Control.Instance            { return *(*Control.Instance)(ie.As(&o)) }
func (o class) AsCanvasItem() CanvasItem.Advanced         { return *(*CanvasItem.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsCanvasItem() CanvasItem.Instance { return o.Super().AsCanvasItem() }
func (o Instance) AsCanvasItem() CanvasItem.Instance      { return *(*CanvasItem.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced                     { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance             { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance                  { return *(*Node.Instance)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Container.Advanced(self.AsContainer()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Container.Instance(self.AsContainer()), name)
	}
}
func init() {
	gdclass.Register("ScrollContainer", func(ptr gdreference.Object) any { return Instance{gdclass.NewScrollContainer(ptr)} })
}

type ScrollMode int64 //gd:ScrollContainer.ScrollMode

const (
	// Scrolling disabled, scrollbar will be invisible.
	ScrollModeDisabled ScrollMode = 0
	// Scrolling enabled, scrollbar will be visible only if necessary, i.e. container's content is bigger than the container.
	ScrollModeAuto ScrollMode = 1
	// Scrolling enabled, scrollbar will be always visible.
	ScrollModeShowAlways ScrollMode = 2
	// Scrolling enabled, scrollbar will be hidden.
	ScrollModeShowNever ScrollMode = 3
	// Combines [ScrollModeAuto] and [ScrollModeShowAlways]. The scrollbar is only visible if necessary, but the content size is adjusted as if it was always visible. It's useful for ensuring that content size stays the same regardless if the scrollbar is visible.
	ScrollModeReserve ScrollMode = 4
)

type ScrollHintMode int64 //gd:ScrollContainer.ScrollHintMode

const (
	// Scroll hints will never be shown.
	ScrollHintModeDisabled ScrollHintMode = 0
	// Scroll hints will be shown at the top and bottom (if vertical), or left and right (if horizontal).
	ScrollHintModeAll ScrollHintMode = 1
	// Scroll hints will be shown at the top (if vertical), or the left (if horizontal).
	ScrollHintModeTopAndLeft ScrollHintMode = 2
	// Scroll hints will be shown at the bottom (if horizontal), or the right (if horizontal).
	ScrollHintModeBottomAndRight ScrollHintMode = 3
)
