// Code generated by the generate package DO NOT EDIT

/*
The GDExtensionManager loads, initializes, and keeps track of all available [GDExtension] libraries in the project.

Note: Do not worry about GDExtension unless you know what you are doing.

[GDExtension]: https://pkg.go.dev/graphics.gd/classdb/GDExtension
*/
package GDExtensionManager

import "sync"
import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/GDExtension"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create an extension of this class.
T should be the type that is embedding this [Extension]
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.GDExtensionManager

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	load_extension        gdextension.MethodForClass `hash:"4024158731"`
	reload_extension      gdextension.MethodForClass `hash:"4024158731"`
	unload_extension      gdextension.MethodForClass `hash:"4024158731"`
	is_extension_loaded   gdextension.MethodForClass `hash:"3927539163"`
	get_loaded_extensions gdextension.MethodForClass `hash:"1139954409"`
	get_extension         gdextension.MethodForClass `hash:"49743343"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("GDExtensionManager")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

var self [1]gdclass.GDExtensionManager
var once sync.Once

func singleton() {
	self[0] = pointers.Raw[gdclass.GDExtensionManager]([3]uint64{uint64(gdextension.Host.Objects.Global(sname))})
}

/*
Loads an extension by absolute file path. The 'path' needs to point to a valid [GDExtension]. Returns [LoadStatusOk] if successful.

[GDExtension]: https://pkg.go.dev/graphics.gd/classdb/GDExtension
*/
func LoadExtension(path string) LoadStatus { //gd:GDExtensionManager.load_extension
	once.Do(singleton)
	return LoadStatus(Advanced().LoadExtension(String.New(path)))
}

/*
Reloads the extension at the given file path. The 'path' needs to point to a valid [GDExtension], otherwise this method may return either [LoadStatusNotLoaded] or [LoadStatusFailed].

Note: You can only reload extensions in the editor. In release builds, this method always fails and returns [LoadStatusFailed].

[GDExtension]: https://pkg.go.dev/graphics.gd/classdb/GDExtension
*/
func ReloadExtension(path string) LoadStatus { //gd:GDExtensionManager.reload_extension
	once.Do(singleton)
	return LoadStatus(Advanced().ReloadExtension(String.New(path)))
}

/*
Unloads an extension by file path. The 'path' needs to point to an already loaded [GDExtension], otherwise this method returns [LoadStatusNotLoaded].

[GDExtension]: https://pkg.go.dev/graphics.gd/classdb/GDExtension
*/
func UnloadExtension(path string) LoadStatus { //gd:GDExtensionManager.unload_extension
	once.Do(singleton)
	return LoadStatus(Advanced().UnloadExtension(String.New(path)))
}

/*
Returns true if the extension at the given file 'path' has already been loaded successfully. See also [GetLoadedExtensions].
*/
func IsExtensionLoaded(path string) bool { //gd:GDExtensionManager.is_extension_loaded
	once.Do(singleton)
	return bool(Advanced().IsExtensionLoaded(String.New(path)))
}

/*
Returns the file paths of all currently loaded extensions.
*/
func GetLoadedExtensions() []string { //gd:GDExtensionManager.get_loaded_extensions
	once.Do(singleton)
	return []string(Advanced().GetLoadedExtensions().Strings())
}

/*
Returns the [GDExtension] at the given file 'path', or null if it has not been loaded or does not exist.

[GDExtension]: https://pkg.go.dev/graphics.gd/classdb/GDExtension
*/
func GetExtension(path string) GDExtension.Instance { //gd:GDExtensionManager.get_extension
	once.Do(singleton)
	return GDExtension.Instance(Advanced().GetExtension(String.New(path)))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
func Advanced() class { once.Do(singleton); return self }

type class [1]gdclass.GDExtensionManager

func (self class) AsObject() [1]gd.Object { return self[0].AsObject() }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = pointers.AsA[gdclass.GDExtensionManager](obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = pointers.AsA[gdclass.GDExtensionManager](obj[0])
		return true
	}
	return false
}
func (self Instance) AsObject() [1]gd.Object      { return self[0].AsObject() }
func (self *Extension[T]) AsObject() [1]gd.Object { return self.Super().AsObject() }

/*
Loads an extension by absolute file path. The 'path' needs to point to a valid [GDExtension]. Returns [LoadStatusOk] if successful.

[GDExtension]: https://pkg.go.dev/graphics.gd/classdb/GDExtension
*/
//go:nosplit
func (self class) LoadExtension(path String.Readable) LoadStatus { //gd:GDExtensionManager.load_extension
	var r_ret = noescape.Call[LoadStatus](gd.ObjectChecked(self.AsObject()), methods.load_extension, gdextension.SizeInt|(gdextension.SizeString<<4), &struct{ path gdextension.String }{pointers.Get(gd.InternalString(path))})
	var ret = r_ret
	return ret
}

/*
Reloads the extension at the given file path. The 'path' needs to point to a valid [GDExtension], otherwise this method may return either [LoadStatusNotLoaded] or [LoadStatusFailed].

Note: You can only reload extensions in the editor. In release builds, this method always fails and returns [LoadStatusFailed].

[GDExtension]: https://pkg.go.dev/graphics.gd/classdb/GDExtension
*/
//go:nosplit
func (self class) ReloadExtension(path String.Readable) LoadStatus { //gd:GDExtensionManager.reload_extension
	var r_ret = noescape.Call[LoadStatus](gd.ObjectChecked(self.AsObject()), methods.reload_extension, gdextension.SizeInt|(gdextension.SizeString<<4), &struct{ path gdextension.String }{pointers.Get(gd.InternalString(path))})
	var ret = r_ret
	return ret
}

/*
Unloads an extension by file path. The 'path' needs to point to an already loaded [GDExtension], otherwise this method returns [LoadStatusNotLoaded].

[GDExtension]: https://pkg.go.dev/graphics.gd/classdb/GDExtension
*/
//go:nosplit
func (self class) UnloadExtension(path String.Readable) LoadStatus { //gd:GDExtensionManager.unload_extension
	var r_ret = noescape.Call[LoadStatus](gd.ObjectChecked(self.AsObject()), methods.unload_extension, gdextension.SizeInt|(gdextension.SizeString<<4), &struct{ path gdextension.String }{pointers.Get(gd.InternalString(path))})
	var ret = r_ret
	return ret
}

/*
Returns true if the extension at the given file 'path' has already been loaded successfully. See also [GetLoadedExtensions].
*/
//go:nosplit
func (self class) IsExtensionLoaded(path String.Readable) bool { //gd:GDExtensionManager.is_extension_loaded
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_extension_loaded, gdextension.SizeBool|(gdextension.SizeString<<4), &struct{ path gdextension.String }{pointers.Get(gd.InternalString(path))})
	var ret = r_ret
	return ret
}

/*
Returns the file paths of all currently loaded extensions.
*/
//go:nosplit
func (self class) GetLoadedExtensions() Packed.Strings { //gd:GDExtensionManager.get_loaded_extensions
	var r_ret = noescape.Call[gd.PackedPointers](gd.ObjectChecked(self.AsObject()), methods.get_loaded_extensions, gdextension.SizePackedArray, &struct{}{})
	var ret = Packed.Strings(Array.Through(gd.PackedStringArrayProxy{}, pointers.Pack(pointers.Let[gd.PackedStringArray](r_ret))))
	return ret
}

/*
Returns the [GDExtension] at the given file 'path', or null if it has not been loaded or does not exist.

[GDExtension]: https://pkg.go.dev/graphics.gd/classdb/GDExtension
*/
//go:nosplit
func (self class) GetExtension(path String.Readable) [1]gdclass.GDExtension { //gd:GDExtensionManager.get_extension
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_extension, gdextension.SizeObject|(gdextension.SizeString<<4), &struct{ path gdextension.String }{pointers.Get(gd.InternalString(path))})
	var ret = [1]gdclass.GDExtension{gd.PointerWithOwnershipTransferredToGo[gdclass.GDExtension](r_ret)}
	return ret
}

/*
Emitted after the editor has finished reloading one or more extensions.
*/
func OnExtensionsReloaded(cb func(), flags ...Signal.Flags) {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	self[0].AsObject()[0].Connect(gd.NewStringName("extensions_reloaded"), gd.NewCallable(cb), int64(flags_together))
}

func (self class) ExtensionsReloaded() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`ExtensionsReloaded`))))
}

/*
Emitted after the editor has finished loading a new extension.

Note: This signal is only emitted in editor builds.
*/
func OnExtensionLoaded(cb func(extension GDExtension.Instance), flags ...Signal.Flags) {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	self[0].AsObject()[0].Connect(gd.NewStringName("extension_loaded"), gd.NewCallable(cb), int64(flags_together))
}

func (self class) ExtensionLoaded() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`ExtensionLoaded`))))
}

/*
Emitted before the editor starts unloading an extension.

Note: This signal is only emitted in editor builds.
*/
func OnExtensionUnloading(cb func(extension GDExtension.Instance), flags ...Signal.Flags) {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	self[0].AsObject()[0].Connect(gd.NewStringName("extension_unloading"), gd.NewCallable(cb), int64(flags_together))
}

func (self class) ExtensionUnloading() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`ExtensionUnloading`))))
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Object.Advanced(self.AsObject()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Object.Instance(self.AsObject()), name)
	}
}
func init() {
	gdclass.Register("GDExtensionManager", func(ptr gd.Object) any { return Instance{pointers.AsA[gdclass.GDExtensionManager](ptr)} })
}

type LoadStatus int //gd:GDExtensionManager.LoadStatus

const (
	// The extension has loaded successfully.
	LoadStatusOk LoadStatus = 0
	// The extension has failed to load, possibly because it does not exist or has missing dependencies.
	LoadStatusFailed LoadStatus = 1
	// The extension has already been loaded.
	LoadStatusAlreadyLoaded LoadStatus = 2
	// The extension has not been loaded.
	LoadStatusNotLoaded LoadStatus = 3
	// The extension requires the application to restart to fully load.
	LoadStatusNeedsRestart LoadStatus = 4
)
