// Code generated by the generate package DO NOT EDIT

/*
For XR to be comfortable, it is important for applications to deliver frames quickly and consistently. In order to make sure the important application threads get their full share of time, these threads must be identified to the system, which will adjust their scheduling priority accordingly.
*/
package OpenXRAndroidThreadSettingsExtension

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/OpenXRExtensionWrapper"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.OpenXRAndroidThreadSettingsExtension

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_application_thread_type gdextension.MethodForClass `hash:"1558751158"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("OpenXRAndroidThreadSettingsExtension")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// MoreArgs is a container for [Instance] functions with additional 'optional' arguments.
type MoreArgs [1]gdclass.OpenXRAndroidThreadSettingsExtension
type Expanded = MoreArgs

// MoreArgs enables certain functions to be called with additional 'optional' arguments.
func (self Instance) MoreArgs() MoreArgs { return MoreArgs(self) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsOpenXRAndroidThreadSettingsExtension() Instance
}

/*
Sets the thread type of the given thread, so that the XR runtime can adjust its scheduling priority accordingly.

'thread_id' refers to the OS thread id (ie from gettid()). When 'thread_id' is 0, it will set the thread type of the current thread.

NOTE: The id returned by [Thread.GetId] is incompatible with 'thread_id'.

[Thread.GetId]: https://pkg.go.dev/graphics.gd/classdb/Thread#Instance.GetId
*/
func (self Instance) SetApplicationThreadType(thread_type ThreadType) bool { //gd:OpenXRAndroidThreadSettingsExtension.set_application_thread_type
	return bool(Advanced(self).SetApplicationThreadType(thread_type, int64(0)))
}

/*
Sets the thread type of the given thread, so that the XR runtime can adjust its scheduling priority accordingly.

'thread_id' refers to the OS thread id (ie from gettid()). When 'thread_id' is 0, it will set the thread type of the current thread.

NOTE: The id returned by [Thread.GetId] is incompatible with 'thread_id'.

[Thread.GetId]: https://pkg.go.dev/graphics.gd/classdb/Thread#Instance.GetId
*/
func (self MoreArgs) SetApplicationThreadType(thread_type ThreadType, thread_id int) bool { //gd:OpenXRAndroidThreadSettingsExtension.set_application_thread_type
	return bool(Advanced(self).SetApplicationThreadType(thread_type, int64(thread_id)))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.OpenXRAndroidThreadSettingsExtension

func (self class) AsObject() [1]gd.Object {
	return gdclass.GetOpenXRAndroidThreadSettingsExtension(self[0])
}
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = gdclass.NewOpenXRAndroidThreadSettingsExtension(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = gdclass.NewOpenXRAndroidThreadSettingsExtension(obj[0])
		return true
	}
	return false
}
func (self Instance) AsObject() [1]gd.Object {
	return gdclass.GetOpenXRAndroidThreadSettingsExtension(self[0])
}
func (self *Extension[T]) AsObject() [1]gd.Object { return self.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.OpenXRAndroidThreadSettingsExtension{gdclass.NewOpenXRAndroidThreadSettingsExtension(pointers.Add[gd.Object]([3]uint64{}))})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := pointers.End(New().AsObject()[0])
				pointers.Set(gdclass.GetOpenXRAndroidThreadSettingsExtension(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := pointers.Get[gd.Object](placeholder.AsObject()[0]); raw[0] != 0 && raw[1] == 0 {
						gdextension.Host.Objects.Unsafe.Free(gdextension.Object(raw[0]))
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.OpenXRAndroidThreadSettingsExtension{gdclass.NewOpenXRAndroidThreadSettingsExtension(pointers.New[gd.Object]([3]uint64{uint64(gdextension.Host.Objects.Make(sname))}))})
	casted.AsObject()[0].Notification(0, false)
	return casted
}

func (self class) SetApplicationThreadType(thread_type ThreadType, thread_id int64) bool { //gd:OpenXRAndroidThreadSettingsExtension.set_application_thread_type
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.set_application_thread_type, gdextension.SizeBool|(gdextension.SizeInt<<4)|(gdextension.SizeInt<<8), &struct {
		thread_type ThreadType
		thread_id   int64
	}{thread_type, thread_id})
	var ret = r_ret
	return ret
}
func (self class) AsOpenXRAndroidThreadSettingsExtension() Advanced {
	return Advanced{gdclass.NewOpenXRAndroidThreadSettingsExtension(self.AsObject()[0])}
}
func (self Instance) AsOpenXRAndroidThreadSettingsExtension() Instance {
	return Instance{gdclass.NewOpenXRAndroidThreadSettingsExtension(self.AsObject()[0])}
}
func (self *Extension[T]) AsOpenXRAndroidThreadSettingsExtension() Instance {
	return self.Super().AsOpenXRAndroidThreadSettingsExtension()
}
func (self class) AsOpenXRExtensionWrapper() OpenXRExtensionWrapper.Advanced {
	return OpenXRExtensionWrapper.Advanced{gdclass.NewOpenXRExtensionWrapper(self.AsObject()[0])}
}
func (self *Extension[T]) AsOpenXRExtensionWrapper() OpenXRExtensionWrapper.Instance {
	return self.Super().AsOpenXRExtensionWrapper()
}
func (self Instance) AsOpenXRExtensionWrapper() OpenXRExtensionWrapper.Instance {
	return OpenXRExtensionWrapper.Instance{gdclass.NewOpenXRExtensionWrapper(self.AsObject()[0])}
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(OpenXRExtensionWrapper.Advanced(self.AsOpenXRExtensionWrapper()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(OpenXRExtensionWrapper.Instance(self.AsOpenXRExtensionWrapper()), name)
	}
}
func init() {
	gdclass.Register("OpenXRAndroidThreadSettingsExtension", func(ptr gd.Object) any { return Instance{gdclass.NewOpenXRAndroidThreadSettingsExtension(ptr)} })
}

type ThreadType int //gd:OpenXRAndroidThreadSettingsExtension.ThreadType

const (
	// Hints to the XR runtime that the thread is doing time critical CPU tasks.
	ThreadTypeApplicationMain ThreadType = 0
	// Hints to the XR runtime that the thread is doing background CPU tasks.
	ThreadTypeApplicationWorker ThreadType = 1
	// Hints to the XR runtime that the thread is doing time critical graphics device tasks.
	ThreadTypeRendererMain ThreadType = 2
	// Hints to the XR runtime that the thread is doing background graphics device tasks.
	ThreadTypeRendererWorker ThreadType = 3
)
