// Code generated by the generate package DO NOT EDIT

/*
This object is used by [RenderingDevice].

[RenderingDevice]: https://pkg.go.dev/graphics.gd/classdb/RenderingDevice
*/
package RDTextureFormat

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gdunsafe "graphics.gd"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Rendering"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ gdunsafe.Object
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.RDTextureFormat

var otype gdunsafe.ObjectType
var sname gdextension.StringName
var methods struct {
	set_format              gdextension.MethodForClass `hash:"565531219"`
	get_format              gdextension.MethodForClass `hash:"2235804183"`
	set_width               gdextension.MethodForClass `hash:"1286410249"`
	get_width               gdextension.MethodForClass `hash:"3905245786"`
	set_height              gdextension.MethodForClass `hash:"1286410249"`
	get_height              gdextension.MethodForClass `hash:"3905245786"`
	set_depth               gdextension.MethodForClass `hash:"1286410249"`
	get_depth               gdextension.MethodForClass `hash:"3905245786"`
	set_array_layers        gdextension.MethodForClass `hash:"1286410249"`
	get_array_layers        gdextension.MethodForClass `hash:"3905245786"`
	set_mipmaps             gdextension.MethodForClass `hash:"1286410249"`
	get_mipmaps             gdextension.MethodForClass `hash:"3905245786"`
	set_texture_type        gdextension.MethodForClass `hash:"652343381"`
	get_texture_type        gdextension.MethodForClass `hash:"4036357416"`
	set_samples             gdextension.MethodForClass `hash:"3774171498"`
	get_samples             gdextension.MethodForClass `hash:"407791724"`
	set_usage_bits          gdextension.MethodForClass `hash:"245642367"`
	get_usage_bits          gdextension.MethodForClass `hash:"1313398998"`
	set_is_resolve_buffer   gdextension.MethodForClass `hash:"2586408642"`
	get_is_resolve_buffer   gdextension.MethodForClass `hash:"36873697"`
	set_is_discardable      gdextension.MethodForClass `hash:"2586408642"`
	get_is_discardable      gdextension.MethodForClass `hash:"36873697"`
	add_shareable_format    gdextension.MethodForClass `hash:"565531219"`
	remove_shareable_format gdextension.MethodForClass `hash:"565531219"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("RDTextureFormat")
		otype = gdunsafe.ObjectTypeTag(gdunsafe.StringName(sname[0]))
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsRDTextureFormat() Instance
}

/*
Adds 'format' as a valid format for the corresponding [RDTextureView]'s [RDTextureView.FormatOverride] property. If any format is added as shareable, then the main [Format] must also be added.

[Format]: https://pkg.go.dev/graphics.gd/classdb/RDTextureFormat#Instance.Format
[RDTextureView]: https://pkg.go.dev/graphics.gd/classdb/RDTextureView
[RDTextureView.FormatOverride]: https://pkg.go.dev/graphics.gd/classdb/RDTextureView#Instance.FormatOverride
*/
func (self Instance) AddShareableFormat(format Rendering.DataFormat) { //gd:RDTextureFormat.add_shareable_format
	Advanced(self).AddShareableFormat(format)
}

/*
Removes 'format' from the list of valid formats that the corresponding [RDTextureView]'s [RDTextureView.FormatOverride] property can be set to.

[RDTextureView]: https://pkg.go.dev/graphics.gd/classdb/RDTextureView
[RDTextureView.FormatOverride]: https://pkg.go.dev/graphics.gd/classdb/RDTextureView#Instance.FormatOverride
*/
func (self Instance) RemoveShareableFormat(format Rendering.DataFormat) { //gd:RDTextureFormat.remove_shareable_format
	Advanced(self).RemoveShareableFormat(format)
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.RDTextureFormat

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewRDTextureFormat(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewRDTextureFormat(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.RDTextureFormat{gdclass.NewRDTextureFormat(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetRDTextureFormat(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdunsafe.Object(raw).Free()
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.RDTextureFormat{gdclass.NewRDTextureFormat(gdreference.OwnObject(gdextension.Object(gdunsafe.MakeObject(gdunsafe.StringName(sname[0]))), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
The texture's pixel data format.
*/
func (self Instance) Format() Rendering.DataFormat { //gd:RDTextureFormat.format
	return Rendering.DataFormat(class(self).GetFormat())
}

// SetFormat sets the property returned by [GetFormat]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFormat(value Rendering.DataFormat) Instance { //gd:RDTextureFormat.format
	class(self).SetFormat(value)
	return self
}

/*
The texture's width (in pixels).
*/
func (self Instance) Width() int { //gd:RDTextureFormat.width
	return int(int(class(self).GetWidth()))
}

// SetWidth sets the property returned by [GetWidth]. Returns the instance, so that property settings can be chained.
func (self Instance) SetWidth(value int) Instance { //gd:RDTextureFormat.width
	class(self).SetWidth(int64(value))
	return self
}

/*
The texture's height (in pixels).
*/
func (self Instance) Height() int { //gd:RDTextureFormat.height
	return int(int(class(self).GetHeight()))
}

// SetHeight sets the property returned by [GetHeight]. Returns the instance, so that property settings can be chained.
func (self Instance) SetHeight(value int) Instance { //gd:RDTextureFormat.height
	class(self).SetHeight(int64(value))
	return self
}

/*
The texture's depth (in pixels). This is always 1 for 2D textures.
*/
func (self Instance) Depth() int { //gd:RDTextureFormat.depth
	return int(int(class(self).GetDepth()))
}

// SetDepth sets the property returned by [GetDepth]. Returns the instance, so that property settings can be chained.
func (self Instance) SetDepth(value int) Instance { //gd:RDTextureFormat.depth
	class(self).SetDepth(int64(value))
	return self
}

/*
The number of layers in the texture. Only relevant for 2D texture arrays.
*/
func (self Instance) ArrayLayers() int { //gd:RDTextureFormat.array_layers
	return int(int(class(self).GetArrayLayers()))
}

// SetArrayLayers sets the property returned by [GetArrayLayers]. Returns the instance, so that property settings can be chained.
func (self Instance) SetArrayLayers(value int) Instance { //gd:RDTextureFormat.array_layers
	class(self).SetArrayLayers(int64(value))
	return self
}

/*
The number of mipmaps available in the texture.
*/
func (self Instance) Mipmaps() int { //gd:RDTextureFormat.mipmaps
	return int(int(class(self).GetMipmaps()))
}

// SetMipmaps sets the property returned by [GetMipmaps]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMipmaps(value int) Instance { //gd:RDTextureFormat.mipmaps
	class(self).SetMipmaps(int64(value))
	return self
}

/*
The texture type.
*/
func (self Instance) TextureType() Rendering.TextureType { //gd:RDTextureFormat.texture_type
	return Rendering.TextureType(class(self).GetTextureType())
}

// SetTextureType sets the property returned by [GetTextureType]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTextureType(value Rendering.TextureType) Instance { //gd:RDTextureFormat.texture_type
	class(self).SetTextureType(value)
	return self
}

/*
The number of samples used when sampling the texture.
*/
func (self Instance) Samples() Rendering.TextureSamples { //gd:RDTextureFormat.samples
	return Rendering.TextureSamples(class(self).GetSamples())
}

// SetSamples sets the property returned by [GetSamples]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSamples(value Rendering.TextureSamples) Instance { //gd:RDTextureFormat.samples
	class(self).SetSamples(value)
	return self
}

/*
The texture's usage bits, which determine what can be done using the texture.
*/
func (self Instance) UsageBits() Rendering.TextureUsageBits { //gd:RDTextureFormat.usage_bits
	return Rendering.TextureUsageBits(class(self).GetUsageBits())
}

// SetUsageBits sets the property returned by [GetUsageBits]. Returns the instance, so that property settings can be chained.
func (self Instance) SetUsageBits(value Rendering.TextureUsageBits) Instance { //gd:RDTextureFormat.usage_bits
	class(self).SetUsageBits(value)
	return self
}

/*
The texture will be used as the destination of a resolve operation.
*/
func (self Instance) IsResolveBuffer() bool { //gd:RDTextureFormat.is_resolve_buffer
	return bool(class(self).GetIsResolveBuffer())
}

// SetIsResolveBuffer sets the property returned by [GetIsResolveBuffer]. Returns the instance, so that property settings can be chained.
func (self Instance) SetIsResolveBuffer(value bool) Instance { //gd:RDTextureFormat.is_resolve_buffer
	class(self).SetIsResolveBuffer(value)
	return self
}

/*
If a texture is discardable, its contents do not need to be preserved between frames. This flag is only relevant when the texture is used as target in a draw list.

This information is used by [RenderingDevice] to figure out if a texture's contents can be discarded, eliminating unnecessary writes to memory and boosting performance.

[RenderingDevice]: https://pkg.go.dev/graphics.gd/classdb/RenderingDevice
*/
func (self Instance) IsDiscardable() bool { //gd:RDTextureFormat.is_discardable
	return bool(class(self).GetIsDiscardable())
}

// SetIsDiscardable sets the property returned by [GetIsDiscardable]. Returns the instance, so that property settings can be chained.
func (self Instance) SetIsDiscardable(value bool) Instance { //gd:RDTextureFormat.is_discardable
	class(self).SetIsDiscardable(value)
	return self
}

func (self class) SetFormat(p_member Rendering.DataFormat) { //gd:RDTextureFormat.set_format
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_format, 0|(gdextension.SizeInt<<4), &struct{ p_member Rendering.DataFormat }{p_member})
}
func (self class) GetFormat() Rendering.DataFormat { //gd:RDTextureFormat.get_format
	var r_ret = jumponly.Call[Rendering.DataFormat](gd.ObjectChecked(self.AsObject()), methods.get_format, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetWidth(p_member int64) { //gd:RDTextureFormat.set_width
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_width, 0|(gdextension.SizeInt<<4), &struct{ p_member int64 }{p_member})
}
func (self class) GetWidth() int64 { //gd:RDTextureFormat.get_width
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_width, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetHeight(p_member int64) { //gd:RDTextureFormat.set_height
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_height, 0|(gdextension.SizeInt<<4), &struct{ p_member int64 }{p_member})
}
func (self class) GetHeight() int64 { //gd:RDTextureFormat.get_height
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_height, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetDepth(p_member int64) { //gd:RDTextureFormat.set_depth
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_depth, 0|(gdextension.SizeInt<<4), &struct{ p_member int64 }{p_member})
}
func (self class) GetDepth() int64 { //gd:RDTextureFormat.get_depth
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_depth, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetArrayLayers(p_member int64) { //gd:RDTextureFormat.set_array_layers
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_array_layers, 0|(gdextension.SizeInt<<4), &struct{ p_member int64 }{p_member})
}
func (self class) GetArrayLayers() int64 { //gd:RDTextureFormat.get_array_layers
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_array_layers, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMipmaps(p_member int64) { //gd:RDTextureFormat.set_mipmaps
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_mipmaps, 0|(gdextension.SizeInt<<4), &struct{ p_member int64 }{p_member})
}
func (self class) GetMipmaps() int64 { //gd:RDTextureFormat.get_mipmaps
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_mipmaps, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetTextureType(p_member Rendering.TextureType) { //gd:RDTextureFormat.set_texture_type
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_texture_type, 0|(gdextension.SizeInt<<4), &struct{ p_member Rendering.TextureType }{p_member})
}
func (self class) GetTextureType() Rendering.TextureType { //gd:RDTextureFormat.get_texture_type
	var r_ret = jumponly.Call[Rendering.TextureType](gd.ObjectChecked(self.AsObject()), methods.get_texture_type, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSamples(p_member Rendering.TextureSamples) { //gd:RDTextureFormat.set_samples
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_samples, 0|(gdextension.SizeInt<<4), &struct{ p_member Rendering.TextureSamples }{p_member})
}
func (self class) GetSamples() Rendering.TextureSamples { //gd:RDTextureFormat.get_samples
	var r_ret = jumponly.Call[Rendering.TextureSamples](gd.ObjectChecked(self.AsObject()), methods.get_samples, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetUsageBits(p_member Rendering.TextureUsageBits) { //gd:RDTextureFormat.set_usage_bits
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_usage_bits, 0|(gdextension.SizeInt<<4), &struct{ p_member Rendering.TextureUsageBits }{p_member})
}
func (self class) GetUsageBits() Rendering.TextureUsageBits { //gd:RDTextureFormat.get_usage_bits
	var r_ret = jumponly.Call[Rendering.TextureUsageBits](gd.ObjectChecked(self.AsObject()), methods.get_usage_bits, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetIsResolveBuffer(p_member bool) { //gd:RDTextureFormat.set_is_resolve_buffer
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_is_resolve_buffer, 0|(gdextension.SizeBool<<4), &struct{ p_member bool }{p_member})
}
func (self class) GetIsResolveBuffer() bool { //gd:RDTextureFormat.get_is_resolve_buffer
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_is_resolve_buffer, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetIsDiscardable(p_member bool) { //gd:RDTextureFormat.set_is_discardable
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_is_discardable, 0|(gdextension.SizeBool<<4), &struct{ p_member bool }{p_member})
}
func (self class) GetIsDiscardable() bool { //gd:RDTextureFormat.get_is_discardable
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_is_discardable, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) AddShareableFormat(format Rendering.DataFormat) { //gd:RDTextureFormat.add_shareable_format
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.add_shareable_format, 0|(gdextension.SizeInt<<4), &struct{ format Rendering.DataFormat }{format})
}
func (self class) RemoveShareableFormat(format Rendering.DataFormat) { //gd:RDTextureFormat.remove_shareable_format
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.remove_shareable_format, 0|(gdextension.SizeInt<<4), &struct{ format Rendering.DataFormat }{format})
}
func (o class) AsRDTextureFormat() Advanced         { return Advanced(o) }
func (o Instance) AsRDTextureFormat() Instance      { return o }
func (o *Extension[T]) AsRDTextureFormat() Instance { return o.Super() }
func (o class) AsRefCounted() ie.RC                 { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC         { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC              { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Advanced(self.AsRefCounted()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Instance(self.AsRefCounted()), name)
	}
}
func init() {
	gdclass.Register("RDTextureFormat", func(ptr gdreference.Object) any { return Instance{gdclass.NewRDTextureFormat(ptr)} })
}
