// Code generated by the generate package DO NOT EDIT

/*
Scripts extending this class and implementing its [Run] method can be executed from the Script Editor's File > Run menu option (or by pressing Ctrl + Shift + X) while the editor is running. This is useful for adding custom in-editor functionality to Godot. For more complex additions, consider using [EditorPlugin]s instead.

If a script extending this class also has a global class name, it will be included in the editor's command palette.

Note: Extending scripts need to have tool mode enabled.

Example: Running the following script prints "Hello from the Godot Editor!":

	package main

	import (
		"fmt"

		"graphics.gd/classdb/EditorScript"
	)

	type HelloEditor struct {
		EditorScript.Extension[HelloEditor]
	}

	func (h *HelloEditor) Run() {
		fmt.Println("Hello from the Godot Editor!")
	}

Note: EditorScript is [RefCounted], meaning it is destroyed when nothing references it. This can cause errors during asynchronous operations if there are no references to the script.

[EditorPlugin]: https://pkg.go.dev/graphics.gd/classdb/EditorPlugin
[RefCounted]: https://pkg.go.dev/graphics.gd/variant/RefCounted
[Run]: https://pkg.go.dev/graphics.gd/classdb/EditorScript#Interface
*/
package EditorScript

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/EditorInterface"
import "graphics.gd/classdb/Node"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
See [Interface] for methods that can be overridden by T.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
See [Interface] for methods that can be overridden by T.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.EditorScript

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	add_root_node        gdextension.MethodForClass `hash:"1078189570"`
	get_scene            gdextension.MethodForClass `hash:"3160264692"`
	get_editor_interface gdextension.MethodForClass `hash:"1976662476"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("EditorScript")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, true)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsEditorScript() Instance
}

type Interface interface {
	// This method is executed by the Editor when File > Run is used.
	Run()
}

// Implementation implements [Interface] with empty methods.
type Implementation = implementation

type implementation struct{}

func (self implementation) Run() { return }

/*
This method is executed by the Editor when File > Run is used.
*/
func (Instance) _run(impl func(ptr gdclass.Receiver)) (cb gd.ExtensionClassCallVirtualFunc) {
	return func(class any, p_args, p_back gdextension.Pointer) {
		self := gdclass.Receiver(reflect.ValueOf(class).UnsafePointer())
		impl(self)
	}
}

/*
Makes 'node' root of the currently opened scene. Only works if the scene is empty. If the 'node' is a scene instance, an inheriting scene will be created.
*/
func (self Instance) AddRootNode(node Node.Instance) { //gd:EditorScript.add_root_node
	Advanced(self).AddRootNode(node)
}

/*
Returns the edited (current) scene's root [Node]. Equivalent of [EditorInterface.GetEditedSceneRoot].

[EditorInterface.GetEditedSceneRoot]: https://pkg.go.dev/graphics.gd/classdb/EditorInterface#GetEditedSceneRoot
[Node]: https://pkg.go.dev/graphics.gd/classdb/Node
*/
func (self Instance) GetScene() Node.Instance { //gd:EditorScript.get_scene
	return Node.Instance(Advanced(self).GetScene())
}

/*
Returns the [EditorInterface] singleton instance.

[EditorInterface]: https://pkg.go.dev/graphics.gd/classdb/EditorInterface
*/
func (self Instance) GetEditorInterface() EditorInterface.Instance { //gd:EditorScript.get_editor_interface
	return EditorInterface.Instance(Advanced(self).GetEditorInterface())
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.EditorScript

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewEditorScript(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewEditorScript(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.EditorScript{gdclass.NewEditorScript(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetEditorScript(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.EditorScript{gdclass.NewEditorScript(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}
func (class) _run(impl func(ptr gdclass.Receiver)) (cb gd.ExtensionClassCallVirtualFunc) {
	return func(class any, p_args, p_back gdextension.Pointer) {
		self := gdclass.Receiver(reflect.ValueOf(class).UnsafePointer())
		impl(self)
	}
}

func (self class) AddRootNode(node [1]gdclass.Node) { //gd:EditorScript.add_root_node
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.add_root_node, 0|(gdextension.SizeObject<<4), &struct{ node gdextension.Object }{gdextension.Object(gd.PointerWithOwnershipTransferredToGodot(gdclass.GetNode(node[0])[0]))})
}
func (self class) GetScene() [1]gdclass.Node { //gd:EditorScript.get_scene
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_scene, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.Node{gdclass.NewNode(gdreference.LetObject(r_ret))}
	return ret
}
func (self class) GetEditorInterface() [1]gdclass.EditorInterface { //gd:EditorScript.get_editor_interface
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_editor_interface, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.EditorInterface{gdclass.NewEditorInterface(gd.PointerLifetimeBoundTo(self.AsObject(), r_ret))}
	return ret
}
func (o class) AsEditorScript() Advanced         { return Advanced(o) }
func (o Instance) AsEditorScript() Instance      { return o }
func (o *Extension[T]) AsEditorScript() Instance { return o.Super() }
func (o class) AsRefCounted() ie.RC              { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC      { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC           { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	case "_run":
		return reflect.ValueOf(self._run)
	default:
		return gd.VirtualByName(RefCounted.Advanced(self.AsRefCounted()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	case "_run":
		return reflect.ValueOf(self._run)
	default:
		return gd.VirtualByName(RefCounted.Instance(self.AsRefCounted()), name)
	}
}
func init() {
	gdclass.Register("EditorScript", func(ptr gdreference.Object) any { return Instance{gdclass.NewEditorScript(ptr)} })
}
