// Code generated by the generate package DO NOT EDIT

/*
Parent class for various CSG primitives. It contains code and functionality that is common between them. It cannot be used directly. Instead use one of the various classes that inherit from it.

Note: CSG nodes are intended to be used for level prototyping. Creating CSG nodes has a significant CPU cost compared to creating a [MeshInstance3D] with a [PrimitiveMesh]. Moving a CSG node within another CSG node also has a significant CPU cost, so it should be avoided during gameplay.

[MeshInstance3D]: https://pkg.go.dev/graphics.gd/classdb/MeshInstance3D
[PrimitiveMesh]: https://pkg.go.dev/graphics.gd/classdb/PrimitiveMesh
*/
package CSGPrimitive3D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/CSGShape3D"
import "graphics.gd/classdb/GeometryInstance3D"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Node3D"
import "graphics.gd/classdb/VisualInstance3D"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.CSGPrimitive3D

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_flip_faces gdextension.MethodForClass `hash:"2586408642"`
	get_flip_faces gdextension.MethodForClass `hash:"2240911060"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("CSGPrimitive3D")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsCSGPrimitive3D() Instance
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.CSGPrimitive3D

func (o class) AsObject() [1]gd.Object { return *(*[1]gd.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = gdclass.NewCSGPrimitive3D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = gdclass.NewCSGPrimitive3D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gd.Object      { return *(*[1]gd.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gd.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.CSGPrimitive3D{gdclass.NewCSGPrimitive3D(pointers.Add[gd.Object]([3]uint64{}))})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := pointers.End(New().AsObject()[0])
				pointers.Set(gdclass.GetCSGPrimitive3D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := pointers.Get[gd.Object](placeholder.AsObject()[0]); raw[0] != 0 && raw[1] == 0 {
						gdextension.Host.Objects.Unsafe.Free(gdextension.Object(raw[0]))
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.CSGPrimitive3D{gdclass.NewCSGPrimitive3D(pointers.New[gd.Object]([3]uint64{uint64(gdextension.Host.Objects.Make(sname))}))})
	casted.AsObject()[0].Notification(0, false)
	return casted
}

/*
If set, the order of the vertices in each triangle are reversed resulting in the backside of the mesh being drawn.
*/
func (self Instance) FlipFaces() bool { //gd:CSGPrimitive3D.flip_faces
	return bool(class(self).GetFlipFaces())
}

// SetFlipFaces sets the property returned by [GetFlipFaces]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFlipFaces(value bool) Instance { //gd:CSGPrimitive3D.flip_faces
	class(self).SetFlipFaces(value)
	return self
}

func (self class) SetFlipFaces(flip_faces bool) { //gd:CSGPrimitive3D.set_flip_faces
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_flip_faces, 0|(gdextension.SizeBool<<4), &struct{ flip_faces bool }{flip_faces})
}
func (self class) GetFlipFaces() bool { //gd:CSGPrimitive3D.get_flip_faces
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_flip_faces, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsCSGPrimitive3D() Advanced                { return Advanced(o) }
func (o Instance) AsCSGPrimitive3D() Instance             { return o }
func (o *Extension[T]) AsCSGPrimitive3D() Instance        { return o.Super() }
func (o class) AsCSGShape3D() CSGShape3D.Advanced         { return *(*CSGShape3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsCSGShape3D() CSGShape3D.Instance { return o.Super().AsCSGShape3D() }
func (o Instance) AsCSGShape3D() CSGShape3D.Instance      { return *(*CSGShape3D.Instance)(ie.As(&o)) }
func (o class) AsGeometryInstance3D() GeometryInstance3D.Advanced {
	return *(*GeometryInstance3D.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsGeometryInstance3D() GeometryInstance3D.Instance {
	return o.Super().AsGeometryInstance3D()
}
func (o Instance) AsGeometryInstance3D() GeometryInstance3D.Instance {
	return *(*GeometryInstance3D.Instance)(ie.As(&o))
}
func (o class) AsVisualInstance3D() VisualInstance3D.Advanced {
	return *(*VisualInstance3D.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsVisualInstance3D() VisualInstance3D.Instance {
	return o.Super().AsVisualInstance3D()
}
func (o Instance) AsVisualInstance3D() VisualInstance3D.Instance {
	return *(*VisualInstance3D.Instance)(ie.As(&o))
}
func (o class) AsNode3D() Node3D.Advanced         { return *(*Node3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode3D() Node3D.Instance { return o.Super().AsNode3D() }
func (o Instance) AsNode3D() Node3D.Instance      { return *(*Node3D.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced             { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance     { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance          { return *(*Node.Instance)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(CSGShape3D.Advanced(self.AsCSGShape3D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(CSGShape3D.Instance(self.AsCSGShape3D()), name)
	}
}
func init() {
	gdclass.Register("CSGPrimitive3D", func(ptr gd.Object) any { return Instance{gdclass.NewCSGPrimitive3D(ptr)} })
}
