// Code generated by graphics.gd. DO NOT EDIT.

package icons

import (
	"graphics.gd/classdb/HBoxContainer"
	"graphics.gd/classdb/MarginContainer"
	"graphics.gd/classdb/PackedScene"
	"graphics.gd/classdb/PanelContainer"
	"graphics.gd/classdb/Resource"
	"graphics.gd/classdb/Texture2D"
	"graphics.gd/classdb/TextureRect"
)

var PNG = Resource.Library[struct {
	BombIcon  Texture2D.Instance `gd:"res://icons/bomb_icon.png"`
	FlashIcon Texture2D.Instance `gd:"res://icons/flash_icon.png"`
}]()

var TSCN = Resource.Library[struct {
	Icone    PackedScene.Is[SceneIcone]    `gd:"res://icons/icone.tscn"`
	WeaponUi PackedScene.Is[SceneWeaponUi] `gd:"res://icons/weapon_ui.tscn"`
}]()

type SceneIcone struct {
	TextureRect.Instance `gd:"res://icons/icone.tscn"`
}

type SceneWeaponUi struct {
	PanelContainer.Instance `gd:"res://icons/weapon_ui.tscn"`

	Control struct {
		HBoxContainer.Instance

		MarginContainer struct {
			MarginContainer.Instance

			Flash TextureRect.Instance
		}
		MarginContainer2 struct {
			MarginContainer.Instance

			Grenade TextureRect.Instance
		}
	}
}
