// Code generated by the generate package DO NOT EDIT

/*
A constant [Vector2.XY], which can be used as an input node.

[Vector2.XY]: https://pkg.go.dev/graphics.gd/variant/Vector2#XY
*/
package VisualShaderNodeVec2Constant

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Resource"
import "graphics.gd/classdb/VisualShaderNode"
import "graphics.gd/classdb/VisualShaderNodeConstant"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Vector2"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.VisualShaderNodeVec2Constant

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_constant gdextension.MethodForClass `hash:"743155724"`
	get_constant gdextension.MethodForClass `hash:"3341600327"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("VisualShaderNodeVec2Constant")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsVisualShaderNodeVec2Constant() Instance
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.VisualShaderNodeVec2Constant

func (o class) AsObject() [1]gd.Object { return *(*[1]gd.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = gdclass.NewVisualShaderNodeVec2Constant(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = gdclass.NewVisualShaderNodeVec2Constant(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gd.Object      { return *(*[1]gd.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gd.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.VisualShaderNodeVec2Constant{gdclass.NewVisualShaderNodeVec2Constant(pointers.Add[gd.Object]([3]uint64{}))})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := pointers.End(New().AsObject()[0])
				pointers.Set(gdclass.GetVisualShaderNodeVec2Constant(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := pointers.Get[gd.Object](placeholder.AsObject()[0]); raw[0] != 0 && raw[1] == 0 {
						gdextension.Host.Objects.Unsafe.Free(gdextension.Object(raw[0]))
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.VisualShaderNodeVec2Constant{gdclass.NewVisualShaderNodeVec2Constant(pointers.New[gd.Object]([3]uint64{uint64(gdextension.Host.Objects.Make(sname))}))})
	casted.AsRefCounted()[0].InitRef()
	casted.AsObject()[0].Notification(0, false)
	return casted
}

/*
A [Vector2.XY] constant which represents the state of this node.

[Vector2.XY]: https://pkg.go.dev/graphics.gd/variant/Vector2#XY
*/
func (self Instance) Constant() Vector2.XY { //gd:VisualShaderNodeVec2Constant.constant
	return Vector2.XY(class(self).GetConstant())
}

// SetConstant sets the property returned by [GetConstant]. Returns the instance, so that property settings can be chained.
func (self Instance) SetConstant(value Vector2.XY) Instance { //gd:VisualShaderNodeVec2Constant.constant
	class(self).SetConstant(Vector2.XY(value))
	return self
}

func (self class) SetConstant(constant Vector2.XY) { //gd:VisualShaderNodeVec2Constant.set_constant
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_constant, 0|(gdextension.SizeVector2<<4), &struct{ constant Vector2.XY }{constant})
}
func (self class) GetConstant() Vector2.XY { //gd:VisualShaderNodeVec2Constant.get_constant
	var r_ret = noescape.Call[Vector2.XY](gd.ObjectChecked(self.AsObject()), methods.get_constant, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsVisualShaderNodeVec2Constant() Advanced         { return Advanced(o) }
func (o Instance) AsVisualShaderNodeVec2Constant() Instance      { return o }
func (o *Extension[T]) AsVisualShaderNodeVec2Constant() Instance { return o.Super() }
func (o class) AsVisualShaderNodeConstant() VisualShaderNodeConstant.Advanced {
	return *(*VisualShaderNodeConstant.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsVisualShaderNodeConstant() VisualShaderNodeConstant.Instance {
	return o.Super().AsVisualShaderNodeConstant()
}
func (o Instance) AsVisualShaderNodeConstant() VisualShaderNodeConstant.Instance {
	return *(*VisualShaderNodeConstant.Instance)(ie.As(&o))
}
func (o class) AsVisualShaderNode() VisualShaderNode.Advanced {
	return *(*VisualShaderNode.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsVisualShaderNode() VisualShaderNode.Instance {
	return o.Super().AsVisualShaderNode()
}
func (o Instance) AsVisualShaderNode() VisualShaderNode.Instance {
	return *(*VisualShaderNode.Instance)(ie.As(&o))
}
func (o class) AsResource() Resource.Advanced         { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance      { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC                   { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC           { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(VisualShaderNodeConstant.Advanced(self.AsVisualShaderNodeConstant()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(VisualShaderNodeConstant.Instance(self.AsVisualShaderNodeConstant()), name)
	}
}
func init() {
	gdclass.Register("VisualShaderNodeVec2Constant", func(ptr gd.Object) any { return Instance{gdclass.NewVisualShaderNodeVec2Constant(ptr)} })
}
