// Code generated by the generate package DO NOT EDIT

/*
Abstract base class for sliders, used to adjust a value by moving a grabber along a horizontal or vertical axis. Sliders are [Range]-based controls.

[Range]: https://pkg.go.dev/graphics.gd/classdb/Range
*/
package Slider

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gdunsafe "graphics.gd"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/CanvasItem"
import "graphics.gd/classdb/Control"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Range"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ gdunsafe.Object
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.Slider

var otype gdunsafe.ObjectType
var sname gdextension.StringName
var methods struct {
	set_ticks            gdextension.MethodForClass `hash:"1286410249"`
	get_ticks            gdextension.MethodForClass `hash:"3905245786"`
	get_ticks_on_borders gdextension.MethodForClass `hash:"36873697"`
	set_ticks_on_borders gdextension.MethodForClass `hash:"2586408642"`
	get_ticks_position   gdextension.MethodForClass `hash:"3567635531"`
	set_ticks_position   gdextension.MethodForClass `hash:"2952822224"`
	set_editable         gdextension.MethodForClass `hash:"2586408642"`
	is_editable          gdextension.MethodForClass `hash:"36873697"`
	set_scrollable       gdextension.MethodForClass `hash:"2586408642"`
	is_scrollable        gdextension.MethodForClass `hash:"36873697"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("Slider")
		otype = gdunsafe.ObjectTypeTag(gdunsafe.StringName(sname[0]))
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsSlider() Instance
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.Slider

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewSlider(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewSlider(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.Slider{gdclass.NewSlider(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetSlider(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdunsafe.Object(raw).Free()
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.Slider{gdclass.NewSlider(gdreference.OwnObject(gdextension.Object(gdunsafe.MakeObject(gdunsafe.StringName(sname[0]))), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
If true, the slider can be interacted with. If false, the value can be changed only by code.
*/
func (self Instance) Editable() bool { //gd:Slider.editable
	return bool(class(self).IsEditable())
}

// SetEditable sets the property returned by [IsEditable]. Returns the instance, so that property settings can be chained.
func (self Instance) SetEditable(value bool) Instance { //gd:Slider.editable
	class(self).SetEditable(value)
	return self
}

/*
If true, the value can be changed using the mouse wheel.
*/
func (self Instance) Scrollable() bool { //gd:Slider.scrollable
	return bool(class(self).IsScrollable())
}

// SetScrollable sets the property returned by [IsScrollable]. Returns the instance, so that property settings can be chained.
func (self Instance) SetScrollable(value bool) Instance { //gd:Slider.scrollable
	class(self).SetScrollable(value)
	return self
}

/*
Number of ticks displayed on the slider, including border ticks. Ticks are uniformly-distributed value markers.
*/
func (self Instance) TickCount() int { //gd:Slider.tick_count
	return int(int(class(self).GetTicks()))
}

// SetTickCount sets the property returned by [GetTicks]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTickCount(value int) Instance { //gd:Slider.tick_count
	class(self).SetTicks(int64(value))
	return self
}

/*
If true, the slider will display ticks for minimum and maximum values.
*/
func (self Instance) TicksOnBorders() bool { //gd:Slider.ticks_on_borders
	return bool(class(self).GetTicksOnBorders())
}

// SetTicksOnBorders sets the property returned by [GetTicksOnBorders]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTicksOnBorders(value bool) Instance { //gd:Slider.ticks_on_borders
	class(self).SetTicksOnBorders(value)
	return self
}

/*
Sets the position of the ticks. See [TickPosition] for details.
*/
func (self Instance) TicksPosition() TickPosition { //gd:Slider.ticks_position
	return TickPosition(class(self).GetTicksPosition())
}

// SetTicksPosition sets the property returned by [GetTicksPosition]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTicksPosition(value TickPosition) Instance { //gd:Slider.ticks_position
	class(self).SetTicksPosition(value)
	return self
}

func (self class) SetTicks(count int64) { //gd:Slider.set_ticks
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_ticks, 0|(gdextension.SizeInt<<4), &struct{ count int64 }{count})
}
func (self class) GetTicks() int64 { //gd:Slider.get_ticks
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_ticks, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) GetTicksOnBorders() bool { //gd:Slider.get_ticks_on_borders
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_ticks_on_borders, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetTicksOnBorders(ticks_on_border bool) { //gd:Slider.set_ticks_on_borders
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_ticks_on_borders, 0|(gdextension.SizeBool<<4), &struct{ ticks_on_border bool }{ticks_on_border})
}
func (self class) GetTicksPosition() TickPosition { //gd:Slider.get_ticks_position
	var r_ret = jumponly.Call[TickPosition](gd.ObjectChecked(self.AsObject()), methods.get_ticks_position, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetTicksPosition(ticks_on_border TickPosition) { //gd:Slider.set_ticks_position
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_ticks_position, 0|(gdextension.SizeInt<<4), &struct{ ticks_on_border TickPosition }{ticks_on_border})
}
func (self class) SetEditable(editable bool) { //gd:Slider.set_editable
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_editable, 0|(gdextension.SizeBool<<4), &struct{ editable bool }{editable})
}
func (self class) IsEditable() bool { //gd:Slider.is_editable
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_editable, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetScrollable(scrollable bool) { //gd:Slider.set_scrollable
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_scrollable, 0|(gdextension.SizeBool<<4), &struct{ scrollable bool }{scrollable})
}
func (self class) IsScrollable() bool { //gd:Slider.is_scrollable
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_scrollable, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}

/*
Emitted when the grabber starts being dragged. This is emitted before the corresponding [OnRange.ValueChanged] signal.

[OnRange.ValueChanged]: https://pkg.go.dev/graphics.gd/classdb/Slider#Instance.OnRange.ValueChanged
*/
func (self Instance) OnDragStarted(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("drag_started"), gd.NewCallable(cb), int64(flags_together))
	return self
}

func (self class) DragStarted() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`drag_started`))))
}

/*
Emitted when the grabber stops being dragged. If 'value_changed' is true, [Range.Value] is different from the value when the dragging was started.

[Range.Value]: https://pkg.go.dev/graphics.gd/classdb/Range#Instance.Value
*/
func (self Instance) OnDragEnded(cb func(value_changed bool), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	gd.ObjectConnect(self.AsObject()[0], gd.NewStringName("drag_ended"), gd.NewCallable(cb), int64(flags_together))
	return self
}

func (self class) DragEnded() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`drag_ended`))))
}

func (o class) AsSlider() Advanced                        { return Advanced(o) }
func (o Instance) AsSlider() Instance                     { return o }
func (o *Extension[T]) AsSlider() Instance                { return o.Super() }
func (o class) AsRange() Range.Advanced                   { return *(*Range.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsRange() Range.Instance           { return o.Super().AsRange() }
func (o Instance) AsRange() Range.Instance                { return *(*Range.Instance)(ie.As(&o)) }
func (o class) AsControl() Control.Advanced               { return *(*Control.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsControl() Control.Instance       { return o.Super().AsControl() }
func (o Instance) AsControl() Control.Instance            { return *(*Control.Instance)(ie.As(&o)) }
func (o class) AsCanvasItem() CanvasItem.Advanced         { return *(*CanvasItem.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsCanvasItem() CanvasItem.Instance { return o.Super().AsCanvasItem() }
func (o Instance) AsCanvasItem() CanvasItem.Instance      { return *(*CanvasItem.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced                     { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance             { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance                  { return *(*Node.Instance)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Range.Advanced(self.AsRange()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Range.Instance(self.AsRange()), name)
	}
}
func init() {
	gdclass.Register("Slider", func(ptr gdreference.Object) any { return Instance{gdclass.NewSlider(ptr)} })
}

type TickPosition int64 //gd:Slider.TickPosition

const (
	// Places the ticks at the bottom of the [HSlider], or right of the [VSlider].
	//
	// [HSlider]: https://pkg.go.dev/graphics.gd/classdb/HSlider
	// [VSlider]: https://pkg.go.dev/graphics.gd/classdb/VSlider
	TickPositionBottomRight TickPosition = 0
	// Places the ticks at the top of the [HSlider], or left of the [VSlider].
	//
	// [HSlider]: https://pkg.go.dev/graphics.gd/classdb/HSlider
	// [VSlider]: https://pkg.go.dev/graphics.gd/classdb/VSlider
	TickPositionTopLeft TickPosition = 1
	// Places the ticks at the both sides of the slider.
	TickPositionBoth TickPosition = 2
	// Places the ticks at the center of the slider.
	TickPositionCenter TickPosition = 3
)
