// Code generated by the generate package DO NOT EDIT

/*
Parameters to be used with a [Mesh] convex decomposition operation.

[Mesh]: https://pkg.go.dev/graphics.gd/classdb/Mesh
*/
package MeshConvexDecompositionSettings

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gdunsafe "graphics.gd"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ gdunsafe.Object
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.MeshConvexDecompositionSettings

var otype gdunsafe.ClassTag
var sname gdunsafe.StringName
var methods struct {
	set_max_concavity                    gdextension.MethodForClass `hash:"373806689"`
	get_max_concavity                    gdextension.MethodForClass `hash:"1740695150"`
	set_symmetry_planes_clipping_bias    gdextension.MethodForClass `hash:"373806689"`
	get_symmetry_planes_clipping_bias    gdextension.MethodForClass `hash:"1740695150"`
	set_revolution_axes_clipping_bias    gdextension.MethodForClass `hash:"373806689"`
	get_revolution_axes_clipping_bias    gdextension.MethodForClass `hash:"1740695150"`
	set_min_volume_per_convex_hull       gdextension.MethodForClass `hash:"373806689"`
	get_min_volume_per_convex_hull       gdextension.MethodForClass `hash:"1740695150"`
	set_resolution                       gdextension.MethodForClass `hash:"1286410249"`
	get_resolution                       gdextension.MethodForClass `hash:"3905245786"`
	set_max_num_vertices_per_convex_hull gdextension.MethodForClass `hash:"1286410249"`
	get_max_num_vertices_per_convex_hull gdextension.MethodForClass `hash:"3905245786"`
	set_plane_downsampling               gdextension.MethodForClass `hash:"1286410249"`
	get_plane_downsampling               gdextension.MethodForClass `hash:"3905245786"`
	set_convex_hull_downsampling         gdextension.MethodForClass `hash:"1286410249"`
	get_convex_hull_downsampling         gdextension.MethodForClass `hash:"3905245786"`
	set_normalize_mesh                   gdextension.MethodForClass `hash:"2586408642"`
	get_normalize_mesh                   gdextension.MethodForClass `hash:"36873697"`
	set_mode                             gdextension.MethodForClass `hash:"1668072869"`
	get_mode                             gdextension.MethodForClass `hash:"23479454"`
	set_convex_hull_approximation        gdextension.MethodForClass `hash:"2586408642"`
	get_convex_hull_approximation        gdextension.MethodForClass `hash:"36873697"`
	set_max_convex_hulls                 gdextension.MethodForClass `hash:"1286410249"`
	get_max_convex_hulls                 gdextension.MethodForClass `hash:"3905245786"`
	set_project_hull_vertices            gdextension.MethodForClass `hash:"2586408642"`
	get_project_hull_vertices            gdextension.MethodForClass `hash:"36873697"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdunsafe.UTF8.Intern("MeshConvexDecompositionSettings")
		otype = gdunsafe.Class(sname).Tag()
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		gdunsafe.Free(sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsMeshConvexDecompositionSettings() Instance
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.MeshConvexDecompositionSettings

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewMeshConvexDecompositionSettings(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewMeshConvexDecompositionSettings(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.MeshConvexDecompositionSettings{gdclass.NewMeshConvexDecompositionSettings(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetMeshConvexDecompositionSettings(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdunsafe.Object(raw).Free()
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.MeshConvexDecompositionSettings{gdclass.NewMeshConvexDecompositionSettings(gdreference.OwnObject(gdextension.Object(gdunsafe.New(gdunsafe.Class(sname))), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
Maximum concavity. Ranges from 0.0 to 1.0.
*/
func (self Instance) MaxConcavity() Float.X { //gd:MeshConvexDecompositionSettings.max_concavity
	return Float.X(Float.X(class(self).GetMaxConcavity()))
}

// SetMaxConcavity sets the property returned by [GetMaxConcavity]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMaxConcavity(value Float.X) Instance { //gd:MeshConvexDecompositionSettings.max_concavity
	class(self).SetMaxConcavity(float64(value))
	return self
}

/*
Controls the bias toward clipping along symmetry planes. Ranges from 0.0 to 1.0.
*/
func (self Instance) SymmetryPlanesClippingBias() Float.X { //gd:MeshConvexDecompositionSettings.symmetry_planes_clipping_bias
	return Float.X(Float.X(class(self).GetSymmetryPlanesClippingBias()))
}

// SetSymmetryPlanesClippingBias sets the property returned by [GetSymmetryPlanesClippingBias]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSymmetryPlanesClippingBias(value Float.X) Instance { //gd:MeshConvexDecompositionSettings.symmetry_planes_clipping_bias
	class(self).SetSymmetryPlanesClippingBias(float64(value))
	return self
}

/*
Controls the bias toward clipping along revolution axes. Ranges from 0.0 to 1.0.
*/
func (self Instance) RevolutionAxesClippingBias() Float.X { //gd:MeshConvexDecompositionSettings.revolution_axes_clipping_bias
	return Float.X(Float.X(class(self).GetRevolutionAxesClippingBias()))
}

// SetRevolutionAxesClippingBias sets the property returned by [GetRevolutionAxesClippingBias]. Returns the instance, so that property settings can be chained.
func (self Instance) SetRevolutionAxesClippingBias(value Float.X) Instance { //gd:MeshConvexDecompositionSettings.revolution_axes_clipping_bias
	class(self).SetRevolutionAxesClippingBias(float64(value))
	return self
}

/*
Controls the adaptive sampling of the generated convex-hulls. Ranges from 0.0 to 0.01.
*/
func (self Instance) MinVolumePerConvexHull() Float.X { //gd:MeshConvexDecompositionSettings.min_volume_per_convex_hull
	return Float.X(Float.X(class(self).GetMinVolumePerConvexHull()))
}

// SetMinVolumePerConvexHull sets the property returned by [GetMinVolumePerConvexHull]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMinVolumePerConvexHull(value Float.X) Instance { //gd:MeshConvexDecompositionSettings.min_volume_per_convex_hull
	class(self).SetMinVolumePerConvexHull(float64(value))
	return self
}

/*
Maximum number of voxels generated during the voxelization stage.
*/
func (self Instance) Resolution() int { //gd:MeshConvexDecompositionSettings.resolution
	return int(int(class(self).GetResolution()))
}

// SetResolution sets the property returned by [GetResolution]. Returns the instance, so that property settings can be chained.
func (self Instance) SetResolution(value int) Instance { //gd:MeshConvexDecompositionSettings.resolution
	class(self).SetResolution(int64(value))
	return self
}

/*
Controls the maximum number of triangles per convex-hull. Ranges from 4 to 1024.
*/
func (self Instance) MaxNumVerticesPerConvexHull() int { //gd:MeshConvexDecompositionSettings.max_num_vertices_per_convex_hull
	return int(int(class(self).GetMaxNumVerticesPerConvexHull()))
}

// SetMaxNumVerticesPerConvexHull sets the property returned by [GetMaxNumVerticesPerConvexHull]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMaxNumVerticesPerConvexHull(value int) Instance { //gd:MeshConvexDecompositionSettings.max_num_vertices_per_convex_hull
	class(self).SetMaxNumVerticesPerConvexHull(int64(value))
	return self
}

/*
Controls the granularity of the search for the "best" clipping plane. Ranges from 1 to 16.
*/
func (self Instance) PlaneDownsampling() int { //gd:MeshConvexDecompositionSettings.plane_downsampling
	return int(int(class(self).GetPlaneDownsampling()))
}

// SetPlaneDownsampling sets the property returned by [GetPlaneDownsampling]. Returns the instance, so that property settings can be chained.
func (self Instance) SetPlaneDownsampling(value int) Instance { //gd:MeshConvexDecompositionSettings.plane_downsampling
	class(self).SetPlaneDownsampling(int64(value))
	return self
}

/*
Controls the precision of the convex-hull generation process during the clipping plane selection stage. Ranges from 1 to 16.
*/
func (self Instance) ConvexHullDownsampling() int { //gd:MeshConvexDecompositionSettings.convex_hull_downsampling
	return int(int(class(self).GetConvexHullDownsampling()))
}

// SetConvexHullDownsampling sets the property returned by [GetConvexHullDownsampling]. Returns the instance, so that property settings can be chained.
func (self Instance) SetConvexHullDownsampling(value int) Instance { //gd:MeshConvexDecompositionSettings.convex_hull_downsampling
	class(self).SetConvexHullDownsampling(int64(value))
	return self
}

/*
If true, normalizes the mesh before applying the convex decomposition.
*/
func (self Instance) NormalizeMesh() bool { //gd:MeshConvexDecompositionSettings.normalize_mesh
	return bool(class(self).GetNormalizeMesh())
}

// SetNormalizeMesh sets the property returned by [GetNormalizeMesh]. Returns the instance, so that property settings can be chained.
func (self Instance) SetNormalizeMesh(value bool) Instance { //gd:MeshConvexDecompositionSettings.normalize_mesh
	class(self).SetNormalizeMesh(value)
	return self
}

/*
Mode for the approximate convex decomposition.
*/
func (self Instance) Mode() Mode { //gd:MeshConvexDecompositionSettings.mode
	return Mode(class(self).GetMode())
}

// SetMode sets the property returned by [GetMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMode(value Mode) Instance { //gd:MeshConvexDecompositionSettings.mode
	class(self).SetMode(value)
	return self
}

/*
If true, uses approximation for computing convex hulls.
*/
func (self Instance) ConvexHullApproximation() bool { //gd:MeshConvexDecompositionSettings.convex_hull_approximation
	return bool(class(self).GetConvexHullApproximation())
}

// SetConvexHullApproximation sets the property returned by [GetConvexHullApproximation]. Returns the instance, so that property settings can be chained.
func (self Instance) SetConvexHullApproximation(value bool) Instance { //gd:MeshConvexDecompositionSettings.convex_hull_approximation
	class(self).SetConvexHullApproximation(value)
	return self
}

/*
The maximum number of convex hulls to produce from the merge operation.
*/
func (self Instance) MaxConvexHulls() int { //gd:MeshConvexDecompositionSettings.max_convex_hulls
	return int(int(class(self).GetMaxConvexHulls()))
}

// SetMaxConvexHulls sets the property returned by [GetMaxConvexHulls]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMaxConvexHulls(value int) Instance { //gd:MeshConvexDecompositionSettings.max_convex_hulls
	class(self).SetMaxConvexHulls(int64(value))
	return self
}

/*
If true, projects output convex hull vertices onto the original source mesh to increase floating-point accuracy of the results.
*/
func (self Instance) ProjectHullVertices() bool { //gd:MeshConvexDecompositionSettings.project_hull_vertices
	return bool(class(self).GetProjectHullVertices())
}

// SetProjectHullVertices sets the property returned by [GetProjectHullVertices]. Returns the instance, so that property settings can be chained.
func (self Instance) SetProjectHullVertices(value bool) Instance { //gd:MeshConvexDecompositionSettings.project_hull_vertices
	class(self).SetProjectHullVertices(value)
	return self
}

func (self class) SetMaxConcavity(max_concavity float64) { //gd:MeshConvexDecompositionSettings.set_max_concavity
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_max_concavity, 0|(gdextension.SizeFloat<<4), &struct{ max_concavity float64 }{max_concavity})
}
func (self class) GetMaxConcavity() float64 { //gd:MeshConvexDecompositionSettings.get_max_concavity
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_max_concavity, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSymmetryPlanesClippingBias(symmetry_planes_clipping_bias float64) { //gd:MeshConvexDecompositionSettings.set_symmetry_planes_clipping_bias
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_symmetry_planes_clipping_bias, 0|(gdextension.SizeFloat<<4), &struct{ symmetry_planes_clipping_bias float64 }{symmetry_planes_clipping_bias})
}
func (self class) GetSymmetryPlanesClippingBias() float64 { //gd:MeshConvexDecompositionSettings.get_symmetry_planes_clipping_bias
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_symmetry_planes_clipping_bias, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetRevolutionAxesClippingBias(revolution_axes_clipping_bias float64) { //gd:MeshConvexDecompositionSettings.set_revolution_axes_clipping_bias
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_revolution_axes_clipping_bias, 0|(gdextension.SizeFloat<<4), &struct{ revolution_axes_clipping_bias float64 }{revolution_axes_clipping_bias})
}
func (self class) GetRevolutionAxesClippingBias() float64 { //gd:MeshConvexDecompositionSettings.get_revolution_axes_clipping_bias
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_revolution_axes_clipping_bias, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMinVolumePerConvexHull(min_volume_per_convex_hull float64) { //gd:MeshConvexDecompositionSettings.set_min_volume_per_convex_hull
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_min_volume_per_convex_hull, 0|(gdextension.SizeFloat<<4), &struct{ min_volume_per_convex_hull float64 }{min_volume_per_convex_hull})
}
func (self class) GetMinVolumePerConvexHull() float64 { //gd:MeshConvexDecompositionSettings.get_min_volume_per_convex_hull
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_min_volume_per_convex_hull, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetResolution(min_volume_per_convex_hull int64) { //gd:MeshConvexDecompositionSettings.set_resolution
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_resolution, 0|(gdextension.SizeInt<<4), &struct{ min_volume_per_convex_hull int64 }{min_volume_per_convex_hull})
}
func (self class) GetResolution() int64 { //gd:MeshConvexDecompositionSettings.get_resolution
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_resolution, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMaxNumVerticesPerConvexHull(max_num_vertices_per_convex_hull int64) { //gd:MeshConvexDecompositionSettings.set_max_num_vertices_per_convex_hull
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_max_num_vertices_per_convex_hull, 0|(gdextension.SizeInt<<4), &struct{ max_num_vertices_per_convex_hull int64 }{max_num_vertices_per_convex_hull})
}
func (self class) GetMaxNumVerticesPerConvexHull() int64 { //gd:MeshConvexDecompositionSettings.get_max_num_vertices_per_convex_hull
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_max_num_vertices_per_convex_hull, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetPlaneDownsampling(plane_downsampling int64) { //gd:MeshConvexDecompositionSettings.set_plane_downsampling
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_plane_downsampling, 0|(gdextension.SizeInt<<4), &struct{ plane_downsampling int64 }{plane_downsampling})
}
func (self class) GetPlaneDownsampling() int64 { //gd:MeshConvexDecompositionSettings.get_plane_downsampling
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_plane_downsampling, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetConvexHullDownsampling(convex_hull_downsampling int64) { //gd:MeshConvexDecompositionSettings.set_convex_hull_downsampling
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_convex_hull_downsampling, 0|(gdextension.SizeInt<<4), &struct{ convex_hull_downsampling int64 }{convex_hull_downsampling})
}
func (self class) GetConvexHullDownsampling() int64 { //gd:MeshConvexDecompositionSettings.get_convex_hull_downsampling
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_convex_hull_downsampling, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetNormalizeMesh(normalize_mesh bool) { //gd:MeshConvexDecompositionSettings.set_normalize_mesh
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_normalize_mesh, 0|(gdextension.SizeBool<<4), &struct{ normalize_mesh bool }{normalize_mesh})
}
func (self class) GetNormalizeMesh() bool { //gd:MeshConvexDecompositionSettings.get_normalize_mesh
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_normalize_mesh, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMode(mode Mode) { //gd:MeshConvexDecompositionSettings.set_mode
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_mode, 0|(gdextension.SizeInt<<4), &struct{ mode Mode }{mode})
}
func (self class) GetMode() Mode { //gd:MeshConvexDecompositionSettings.get_mode
	var r_ret = jumponly.Call[Mode](gd.ObjectChecked(self.AsObject()), methods.get_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetConvexHullApproximation(convex_hull_approximation bool) { //gd:MeshConvexDecompositionSettings.set_convex_hull_approximation
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_convex_hull_approximation, 0|(gdextension.SizeBool<<4), &struct{ convex_hull_approximation bool }{convex_hull_approximation})
}
func (self class) GetConvexHullApproximation() bool { //gd:MeshConvexDecompositionSettings.get_convex_hull_approximation
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_convex_hull_approximation, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMaxConvexHulls(max_convex_hulls int64) { //gd:MeshConvexDecompositionSettings.set_max_convex_hulls
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_max_convex_hulls, 0|(gdextension.SizeInt<<4), &struct{ max_convex_hulls int64 }{max_convex_hulls})
}
func (self class) GetMaxConvexHulls() int64 { //gd:MeshConvexDecompositionSettings.get_max_convex_hulls
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_max_convex_hulls, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetProjectHullVertices(project_hull_vertices bool) { //gd:MeshConvexDecompositionSettings.set_project_hull_vertices
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_project_hull_vertices, 0|(gdextension.SizeBool<<4), &struct{ project_hull_vertices bool }{project_hull_vertices})
}
func (self class) GetProjectHullVertices() bool { //gd:MeshConvexDecompositionSettings.get_project_hull_vertices
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_project_hull_vertices, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsMeshConvexDecompositionSettings() Advanced         { return Advanced(o) }
func (o Instance) AsMeshConvexDecompositionSettings() Instance      { return o }
func (o *Extension[T]) AsMeshConvexDecompositionSettings() Instance { return o.Super() }
func (o class) AsRefCounted() ie.RC                                 { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC                         { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                              { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Advanced(self.AsRefCounted()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Instance(self.AsRefCounted()), name)
	}
}
func init() {
	gdclass.Register("MeshConvexDecompositionSettings", func(ptr gdreference.Object) any { return Instance{gdclass.NewMeshConvexDecompositionSettings(ptr)} })
}

type Mode int64 //gd:MeshConvexDecompositionSettings.Mode

const (
	// Constant for voxel-based approximate convex decomposition.
	ConvexDecompositionModeVoxel Mode = 0
	// Constant for tetrahedron-based approximate convex decomposition.
	ConvexDecompositionModeTetrahedron Mode = 1
)
