// Code generated by the generate package DO NOT EDIT

/*
A physics joint that restricts the rotation of a 3D physics body around an axis relative to another physics body. For example, Body A can be a [StaticBody3D] representing a door hinge that a [RigidBody3D] rotates around.

[RigidBody3D]: https://pkg.go.dev/graphics.gd/classdb/RigidBody3D
[StaticBody3D]: https://pkg.go.dev/graphics.gd/classdb/StaticBody3D
*/
package HingeJoint3D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gdunsafe "graphics.gd"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Joint3D"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Node3D"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ gdunsafe.Object
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.HingeJoint3D

var otype gdunsafe.ObjectType
var sname gdextension.StringName
var methods struct {
	set_param gdextension.MethodForClass `hash:"3082977519"`
	get_param gdextension.MethodForClass `hash:"4066002676"`
	set_flag  gdextension.MethodForClass `hash:"1083494620"`
	get_flag  gdextension.MethodForClass `hash:"2841369610"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.StringName{gdextension.Pointer(gdunsafe.UTF8.Intern("HingeJoint3D"))}
		otype = gdunsafe.ObjectTypeTag(gdunsafe.StringName(sname[0]))
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsHingeJoint3D() Instance
}

/*
Sets the value of the specified parameter.

Returns 'self' to enable method chaining.
*/
func (self Instance) SetParam(param Param, value Float.X) Instance { //gd:HingeJoint3D.set_param
	Advanced(self).SetParam(param, float64(value))
	return self
}

/*
Returns the value of the specified parameter.
*/
func (self Instance) GetParam(param Param) Float.X { //gd:HingeJoint3D.get_param
	return Float.X(Float.X(Advanced(self).GetParam(param)))
}

/*
If true, enables the specified flag.

Returns 'self' to enable method chaining.
*/
func (self Instance) SetFlag(flag Flag, enabled bool) Instance { //gd:HingeJoint3D.set_flag
	Advanced(self).SetFlag(flag, enabled)
	return self
}

/*
Returns the value of the specified flag.
*/
func (self Instance) GetFlag(flag Flag) bool { //gd:HingeJoint3D.get_flag
	return bool(Advanced(self).GetFlag(flag))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.HingeJoint3D

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewHingeJoint3D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewHingeJoint3D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.HingeJoint3D{gdclass.NewHingeJoint3D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetHingeJoint3D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdunsafe.Object(raw).Free()
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.HingeJoint3D{gdclass.NewHingeJoint3D(gdreference.OwnObject(gdextension.Object(gdunsafe.MakeObject(gdunsafe.StringName(sname[0]))), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self class) SetParam(param Param, value float64) { //gd:HingeJoint3D.set_param
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_param, 0|(gdextension.SizeInt<<4)|(gdextension.SizeFloat<<8), &struct {
		param Param
		value float64
	}{param, value})
}
func (self class) GetParam(param Param) float64 { //gd:HingeJoint3D.get_param
	var r_ret = noescape.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_param, gdextension.SizeFloat|(gdextension.SizeInt<<4), &struct{ param Param }{param})
	var ret = r_ret
	return ret
}
func (self class) SetFlag(flag Flag, enabled bool) { //gd:HingeJoint3D.set_flag
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_flag, 0|(gdextension.SizeInt<<4)|(gdextension.SizeBool<<8), &struct {
		flag    Flag
		enabled bool
	}{flag, enabled})
}
func (self class) GetFlag(flag Flag) bool { //gd:HingeJoint3D.get_flag
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_flag, gdextension.SizeBool|(gdextension.SizeInt<<4), &struct{ flag Flag }{flag})
	var ret = r_ret
	return ret
}
func (o class) AsHingeJoint3D() Advanced            { return Advanced(o) }
func (o Instance) AsHingeJoint3D() Instance         { return o }
func (o *Extension[T]) AsHingeJoint3D() Instance    { return o.Super() }
func (o class) AsJoint3D() Joint3D.Advanced         { return *(*Joint3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsJoint3D() Joint3D.Instance { return o.Super().AsJoint3D() }
func (o Instance) AsJoint3D() Joint3D.Instance      { return *(*Joint3D.Instance)(ie.As(&o)) }
func (o class) AsNode3D() Node3D.Advanced           { return *(*Node3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode3D() Node3D.Instance   { return o.Super().AsNode3D() }
func (o Instance) AsNode3D() Node3D.Instance        { return *(*Node3D.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced               { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance       { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance            { return *(*Node.Instance)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Joint3D.Advanced(self.AsJoint3D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Joint3D.Instance(self.AsJoint3D()), name)
	}
}
func init() {
	gdclass.Register("HingeJoint3D", func(ptr gdreference.Object) any { return Instance{gdclass.NewHingeJoint3D(ptr)} })
}

type Param int64 //gd:HingeJoint3D.Param

const (
	// The speed with which the two bodies get pulled together when they move in different directions.
	ParamBias Param = 0
	// The maximum rotation. Only active if "angular_limit/enable" is true.
	ParamLimitUpper Param = 1
	// The minimum rotation. Only active if "angular_limit/enable" is true.
	ParamLimitLower Param = 2
	// The speed with which the rotation across the axis perpendicular to the hinge gets corrected.
	ParamLimitBias     Param = 3
	ParamLimitSoftness Param = 4
	// The lower this value, the more the rotation gets slowed down.
	ParamLimitRelaxation Param = 5
	// Target speed for the motor.
	ParamMotorTargetVelocity Param = 6
	// Maximum acceleration for the motor.
	ParamMotorMaxImpulse Param = 7
	// Represents the size of the [Param] enum.
	ParamMax Param = 8
)

type Flag int64 //gd:HingeJoint3D.Flag

const (
	// If true, the hinges maximum and minimum rotation, defined by "angular_limit/lower" and "angular_limit/upper" has effects.
	FlagUseLimit Flag = 0
	// When activated, a motor turns the hinge.
	FlagEnableMotor Flag = 1
	// Represents the size of the [Flag] enum.
	FlagMax Flag = 2
)
