// Code generated by the generate package DO NOT EDIT

/*
A resource used by [AnimationNodeBlendTree].

[AnimationNodeBlendSpace1D] represents a virtual axis on which any type of [AnimationRootNode]s can be added using [AddBlendPoint]. Outputs the linear blend of the two [AnimationRootNode]s adjacent to the current value.

You can set the extents of the axis with [MinSpace] and [MaxSpace].

[AddBlendPoint]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeBlendSpace1D#Instance.AddBlendPoint
[AnimationNodeBlendSpace1D]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeBlendSpace1D
[AnimationNodeBlendTree]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeBlendTree
[AnimationRootNode]: https://pkg.go.dev/graphics.gd/classdb/AnimationRootNode
[MaxSpace]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeBlendSpace1D#Instance.MaxSpace
[MinSpace]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeBlendSpace1D#Instance.MinSpace
*/
package AnimationNodeBlendSpace1D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gdunsafe "graphics.gd"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/AnimationNode"
import "graphics.gd/classdb/AnimationRootNode"
import "graphics.gd/classdb/Resource"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ gdunsafe.Object
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.AnimationNodeBlendSpace1D

var otype gdunsafe.ClassTag
var sname gdunsafe.StringName
var methods struct {
	add_blend_point          gdextension.MethodForClass `hash:"285050433"`
	set_blend_point_position gdextension.MethodForClass `hash:"1602489585"`
	get_blend_point_position gdextension.MethodForClass `hash:"2339986948"`
	set_blend_point_node     gdextension.MethodForClass `hash:"4240341528"`
	get_blend_point_node     gdextension.MethodForClass `hash:"665599029"`
	remove_blend_point       gdextension.MethodForClass `hash:"1286410249"`
	get_blend_point_count    gdextension.MethodForClass `hash:"3905245786"`
	set_min_space            gdextension.MethodForClass `hash:"373806689"`
	get_min_space            gdextension.MethodForClass `hash:"1740695150"`
	set_max_space            gdextension.MethodForClass `hash:"373806689"`
	get_max_space            gdextension.MethodForClass `hash:"1740695150"`
	set_snap                 gdextension.MethodForClass `hash:"373806689"`
	get_snap                 gdextension.MethodForClass `hash:"1740695150"`
	set_value_label          gdextension.MethodForClass `hash:"83702148"`
	get_value_label          gdextension.MethodForClass `hash:"201670096"`
	set_blend_mode           gdextension.MethodForClass `hash:"2600869457"`
	get_blend_mode           gdextension.MethodForClass `hash:"1547667849"`
	set_use_sync             gdextension.MethodForClass `hash:"2586408642"`
	is_using_sync            gdextension.MethodForClass `hash:"36873697"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdunsafe.UTF8.Intern("AnimationNodeBlendSpace1D")
		otype = gdunsafe.Class(sname).Tag()
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		gdunsafe.Free(sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// MoreArgs is a container for [Instance] functions with additional 'optional' arguments.
type MoreArgs [1]gdclass.AnimationNodeBlendSpace1D
type Expanded = MoreArgs

// MoreArgs enables certain functions to be called with additional 'optional' arguments.
func (self Instance) MoreArgs() MoreArgs { return MoreArgs(self) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsAnimationNodeBlendSpace1D() Instance
}

/*
Adds a new point that represents a 'node' on the virtual axis at a given position set by 'pos'. You can insert it at a specific index using the 'at_index' argument. If you use the default value for 'at_index', the point is inserted at the end of the blend points array.
*/
func (self Instance) AddBlendPoint(node AnimationRootNode.Instance, pos Float.X) { //gd:AnimationNodeBlendSpace1D.add_blend_point
	Advanced(self).AddBlendPoint(node, float64(pos), int64(-1))
}

/*
Adds a new point that represents a 'node' on the virtual axis at a given position set by 'pos'. You can insert it at a specific index using the 'at_index' argument. If you use the default value for 'at_index', the point is inserted at the end of the blend points array.
*/
func (self MoreArgs) AddBlendPoint(node AnimationRootNode.Instance, pos Float.X, at_index int) { //gd:AnimationNodeBlendSpace1D.add_blend_point
	Advanced(self).AddBlendPoint(node, float64(pos), int64(at_index))
}

/*
Updates the position of the point at index 'point' on the blend axis.

Returns 'self' to enable method chaining.
*/
func (self Instance) SetBlendPointPosition(point int, pos Float.X) Instance { //gd:AnimationNodeBlendSpace1D.set_blend_point_position
	Advanced(self).SetBlendPointPosition(int64(point), float64(pos))
	return self
}

/*
Returns the position of the point at index 'point'.
*/
func (self Instance) GetBlendPointPosition(point int) Float.X { //gd:AnimationNodeBlendSpace1D.get_blend_point_position
	return Float.X(Float.X(Advanced(self).GetBlendPointPosition(int64(point))))
}

/*
Changes the [AnimationNode] referenced by the point at index 'point'.

Returns 'self' to enable method chaining.

[AnimationNode]: https://pkg.go.dev/graphics.gd/classdb/AnimationNode
*/
func (self Instance) SetBlendPointNode(point int, node AnimationRootNode.Instance) Instance { //gd:AnimationNodeBlendSpace1D.set_blend_point_node
	Advanced(self).SetBlendPointNode(int64(point), node)
	return self
}

/*
Returns the [AnimationNode] referenced by the point at index 'point'.

[AnimationNode]: https://pkg.go.dev/graphics.gd/classdb/AnimationNode
*/
func (self Instance) GetBlendPointNode(point int) AnimationRootNode.Instance { //gd:AnimationNodeBlendSpace1D.get_blend_point_node
	return AnimationRootNode.Instance(Advanced(self).GetBlendPointNode(int64(point)))
}

/*
Removes the point at index 'point' from the blend axis.
*/
func (self Instance) RemoveBlendPoint(point int) { //gd:AnimationNodeBlendSpace1D.remove_blend_point
	Advanced(self).RemoveBlendPoint(int64(point))
}

/*
Returns the number of points on the blend axis.
*/
func (self Instance) GetBlendPointCount() int { //gd:AnimationNodeBlendSpace1D.get_blend_point_count
	return int(int(Advanced(self).GetBlendPointCount()))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.AnimationNodeBlendSpace1D

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewAnimationNodeBlendSpace1D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewAnimationNodeBlendSpace1D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.AnimationNodeBlendSpace1D{gdclass.NewAnimationNodeBlendSpace1D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetAnimationNodeBlendSpace1D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdunsafe.Object(raw).Free()
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.AnimationNodeBlendSpace1D{gdclass.NewAnimationNodeBlendSpace1D(gdreference.OwnObject(gdextension.Object(gdunsafe.New(gdunsafe.Class(sname))), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
The blend space's axis's lower limit for the points' position. See [AddBlendPoint].

[AddBlendPoint]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeBlendSpace1D#Instance.AddBlendPoint
*/
func (self Instance) MinSpace() Float.X { //gd:AnimationNodeBlendSpace1D.min_space
	return Float.X(Float.X(class(self).GetMinSpace()))
}

// SetMinSpace sets the property returned by [GetMinSpace]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMinSpace(value Float.X) Instance { //gd:AnimationNodeBlendSpace1D.min_space
	class(self).SetMinSpace(float64(value))
	return self
}

/*
The blend space's axis's upper limit for the points' position. See [AddBlendPoint].

[AddBlendPoint]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeBlendSpace1D#Instance.AddBlendPoint
*/
func (self Instance) MaxSpace() Float.X { //gd:AnimationNodeBlendSpace1D.max_space
	return Float.X(Float.X(class(self).GetMaxSpace()))
}

// SetMaxSpace sets the property returned by [GetMaxSpace]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMaxSpace(value Float.X) Instance { //gd:AnimationNodeBlendSpace1D.max_space
	class(self).SetMaxSpace(float64(value))
	return self
}

/*
Position increment to snap to when moving a point on the axis.
*/
func (self Instance) Snap() Float.X { //gd:AnimationNodeBlendSpace1D.snap
	return Float.X(Float.X(class(self).GetSnap()))
}

// SetSnap sets the property returned by [GetSnap]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSnap(value Float.X) Instance { //gd:AnimationNodeBlendSpace1D.snap
	class(self).SetSnap(float64(value))
	return self
}

/*
Label of the virtual axis of the blend space.
*/
func (self Instance) ValueLabel() string { //gd:AnimationNodeBlendSpace1D.value_label
	return string(class(self).GetValueLabel().String())
}

// SetValueLabel sets the property returned by [GetValueLabel]. Returns the instance, so that property settings can be chained.
func (self Instance) SetValueLabel(value string) Instance { //gd:AnimationNodeBlendSpace1D.value_label
	class(self).SetValueLabel(String.From(value))
	return self
}

/*
Controls the interpolation between animations.
*/
func (self Instance) BlendMode() BlendMode { //gd:AnimationNodeBlendSpace1D.blend_mode
	return BlendMode(class(self).GetBlendMode())
}

// SetBlendMode sets the property returned by [GetBlendMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetBlendMode(value BlendMode) Instance { //gd:AnimationNodeBlendSpace1D.blend_mode
	class(self).SetBlendMode(value)
	return self
}

/*
If false, the blended animations' frame are stopped when the blend value is 0.

If true, forcing the blended animations to advance frame.
*/
func (self Instance) Sync() bool { //gd:AnimationNodeBlendSpace1D.sync
	return bool(class(self).IsUsingSync())
}

// SetSync sets the property returned by [IsUsingSync]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSync(value bool) Instance { //gd:AnimationNodeBlendSpace1D.sync
	class(self).SetUseSync(value)
	return self
}

func (self class) AddBlendPoint(node [1]gdclass.AnimationRootNode, pos float64, at_index int64) { //gd:AnimationNodeBlendSpace1D.add_blend_point
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.add_blend_point, 0|(gdextension.SizeObject<<4)|(gdextension.SizeFloat<<8)|(gdextension.SizeInt<<12), &struct {
		node     gdextension.Object
		pos      float64
		at_index int64
	}{gdextension.Object(gdreference.GetObject(gdclass.GetAnimationRootNode(node[0])[0])), pos, at_index})
}
func (self class) SetBlendPointPosition(point int64, pos float64) { //gd:AnimationNodeBlendSpace1D.set_blend_point_position
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_blend_point_position, 0|(gdextension.SizeInt<<4)|(gdextension.SizeFloat<<8), &struct {
		point int64
		pos   float64
	}{point, pos})
}
func (self class) GetBlendPointPosition(point int64) float64 { //gd:AnimationNodeBlendSpace1D.get_blend_point_position
	var r_ret = noescape.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_blend_point_position, gdextension.SizeFloat|(gdextension.SizeInt<<4), &struct{ point int64 }{point})
	var ret = r_ret
	return ret
}
func (self class) SetBlendPointNode(point int64, node [1]gdclass.AnimationRootNode) { //gd:AnimationNodeBlendSpace1D.set_blend_point_node
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_blend_point_node, 0|(gdextension.SizeInt<<4)|(gdextension.SizeObject<<8), &struct {
		point int64
		node  gdextension.Object
	}{point, gdextension.Object(gdreference.GetObject(gdclass.GetAnimationRootNode(node[0])[0]))})
}
func (self class) GetBlendPointNode(point int64) [1]gdclass.AnimationRootNode { //gd:AnimationNodeBlendSpace1D.get_blend_point_node
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_blend_point_node, gdextension.SizeObject|(gdextension.SizeInt<<4), &struct{ point int64 }{point})
	var ret = [1]gdclass.AnimationRootNode{gdclass.NewAnimationRootNode(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) RemoveBlendPoint(point int64) { //gd:AnimationNodeBlendSpace1D.remove_blend_point
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.remove_blend_point, 0|(gdextension.SizeInt<<4), &struct{ point int64 }{point})
}
func (self class) GetBlendPointCount() int64 { //gd:AnimationNodeBlendSpace1D.get_blend_point_count
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_blend_point_count, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMinSpace(min_space float64) { //gd:AnimationNodeBlendSpace1D.set_min_space
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_min_space, 0|(gdextension.SizeFloat<<4), &struct{ min_space float64 }{min_space})
}
func (self class) GetMinSpace() float64 { //gd:AnimationNodeBlendSpace1D.get_min_space
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_min_space, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMaxSpace(max_space float64) { //gd:AnimationNodeBlendSpace1D.set_max_space
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_max_space, 0|(gdextension.SizeFloat<<4), &struct{ max_space float64 }{max_space})
}
func (self class) GetMaxSpace() float64 { //gd:AnimationNodeBlendSpace1D.get_max_space
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_max_space, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSnap(snap float64) { //gd:AnimationNodeBlendSpace1D.set_snap
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_snap, 0|(gdextension.SizeFloat<<4), &struct{ snap float64 }{snap})
}
func (self class) GetSnap() float64 { //gd:AnimationNodeBlendSpace1D.get_snap
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_snap, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetValueLabel(text String.Readable) { //gd:AnimationNodeBlendSpace1D.set_value_label
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_value_label, 0|(gdextension.SizeString<<4), &struct{ text gdextension.String }{pointers.Get(gd.InternalString(text))})
}
func (self class) GetValueLabel() String.Readable { //gd:AnimationNodeBlendSpace1D.get_value_label
	var r_ret = jumponly.Call[gdextension.String](gd.ObjectChecked(self.AsObject()), methods.get_value_label, gdextension.SizeString, &struct{}{})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) SetBlendMode(mode BlendMode) { //gd:AnimationNodeBlendSpace1D.set_blend_mode
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_blend_mode, 0|(gdextension.SizeInt<<4), &struct{ mode BlendMode }{mode})
}
func (self class) GetBlendMode() BlendMode { //gd:AnimationNodeBlendSpace1D.get_blend_mode
	var r_ret = jumponly.Call[BlendMode](gd.ObjectChecked(self.AsObject()), methods.get_blend_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetUseSync(enable bool) { //gd:AnimationNodeBlendSpace1D.set_use_sync
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_use_sync, 0|(gdextension.SizeBool<<4), &struct{ enable bool }{enable})
}
func (self class) IsUsingSync() bool { //gd:AnimationNodeBlendSpace1D.is_using_sync
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_using_sync, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsAnimationNodeBlendSpace1D() Advanced         { return Advanced(o) }
func (o Instance) AsAnimationNodeBlendSpace1D() Instance      { return o }
func (o *Extension[T]) AsAnimationNodeBlendSpace1D() Instance { return o.Super() }
func (o class) AsAnimationRootNode() AnimationRootNode.Advanced {
	return *(*AnimationRootNode.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsAnimationRootNode() AnimationRootNode.Instance {
	return o.Super().AsAnimationRootNode()
}
func (o Instance) AsAnimationRootNode() AnimationRootNode.Instance {
	return *(*AnimationRootNode.Instance)(ie.As(&o))
}
func (o class) AsAnimationNode() AnimationNode.Advanced         { return *(*AnimationNode.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsAnimationNode() AnimationNode.Instance { return o.Super().AsAnimationNode() }
func (o Instance) AsAnimationNode() AnimationNode.Instance {
	return *(*AnimationNode.Instance)(ie.As(&o))
}
func (o class) AsResource() Resource.Advanced         { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance      { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC                   { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC           { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(AnimationRootNode.Advanced(self.AsAnimationRootNode()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(AnimationRootNode.Instance(self.AsAnimationRootNode()), name)
	}
}
func init() {
	gdclass.Register("AnimationNodeBlendSpace1D", func(ptr gdreference.Object) any { return Instance{gdclass.NewAnimationNodeBlendSpace1D(ptr)} })
}

type BlendMode int64 //gd:AnimationNodeBlendSpace1D.BlendMode

const (
	// The interpolation between animations is linear.
	BlendModeInterpolated BlendMode = 0
	// The blend space plays the animation of the animation node which blending position is closest to. Useful for frame-by-frame 2D animations.
	BlendModeDiscrete BlendMode = 1
	// Similar to [BlendModeDiscrete], but starts the new animation at the last animation's playback position.
	BlendModeDiscreteCarry BlendMode = 2
)
