// Code generated by the generate package DO NOT EDIT

package GLTFSkin

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Resource"
import "graphics.gd/classdb/Skin"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Transform3D"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.GLTFSkin

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	get_skin_root         gdextension.MethodForClass `hash:"2455072627"`
	set_skin_root         gdextension.MethodForClass `hash:"1286410249"`
	get_joints_original   gdextension.MethodForClass `hash:"969006518"`
	set_joints_original   gdextension.MethodForClass `hash:"3614634198"`
	get_inverse_binds     gdextension.MethodForClass `hash:"2915620761"`
	set_inverse_binds     gdextension.MethodForClass `hash:"381264803"`
	get_joints            gdextension.MethodForClass `hash:"969006518"`
	set_joints            gdextension.MethodForClass `hash:"3614634198"`
	get_non_joints        gdextension.MethodForClass `hash:"969006518"`
	set_non_joints        gdextension.MethodForClass `hash:"3614634198"`
	get_roots             gdextension.MethodForClass `hash:"969006518"`
	set_roots             gdextension.MethodForClass `hash:"3614634198"`
	get_skeleton          gdextension.MethodForClass `hash:"2455072627"`
	set_skeleton          gdextension.MethodForClass `hash:"1286410249"`
	get_joint_i_to_bone_i gdextension.MethodForClass `hash:"2382534195"`
	set_joint_i_to_bone_i gdextension.MethodForClass `hash:"4155329257"`
	get_joint_i_to_name   gdextension.MethodForClass `hash:"2382534195"`
	set_joint_i_to_name   gdextension.MethodForClass `hash:"4155329257"`
	get_godot_skin        gdextension.MethodForClass `hash:"1032037385"`
	set_godot_skin        gdextension.MethodForClass `hash:"3971435618"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("GLTFSkin")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsGLTFSkin() Instance
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.GLTFSkin

func (o class) AsObject() [1]gd.Object { return *(*[1]gd.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewGLTFSkin(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewGLTFSkin(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gd.Object      { return *(*[1]gd.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gd.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.GLTFSkin{gdclass.NewGLTFSkin(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetGLTFSkin(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.GLTFSkin{gdclass.NewGLTFSkin(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self Instance) SkinRoot() int { //gd:GLTFSkin.skin_root
	return int(int(class(self).GetSkinRoot()))
}

// SetSkinRoot sets the property returned by [GetSkinRoot]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSkinRoot(value int) Instance { //gd:GLTFSkin.skin_root
	class(self).SetSkinRoot(int64(value))
	return self
}

func (self Instance) JointsOriginal() []int32 { //gd:GLTFSkin.joints_original
	return []int32(slices.Collect(class(self).GetJointsOriginal().Values()))
}

// SetJointsOriginal sets the property returned by [GetJointsOriginal]. Returns the instance, so that property settings can be chained.
func (self Instance) SetJointsOriginal(value []int32) Instance { //gd:GLTFSkin.joints_original
	class(self).SetJointsOriginal(Packed.New(value...))
	return self
}

func (self Instance) InverseBinds() []Transform3D.BasisOrigin { //gd:GLTFSkin.inverse_binds
	return []Transform3D.BasisOrigin(gd.ArrayAs[[]Transform3D.BasisOrigin](gd.InternalArray(class(self).GetInverseBinds())))
}

// SetInverseBinds sets the property returned by [GetInverseBinds]. Returns the instance, so that property settings can be chained.
func (self Instance) SetInverseBinds(value []Transform3D.BasisOrigin) Instance { //gd:GLTFSkin.inverse_binds
	class(self).SetInverseBinds(gd.ArrayFromSlice[Array.Contains[Transform3D.BasisOrigin]](value))
	return self
}

func (self Instance) Joints() []int32 { //gd:GLTFSkin.joints
	return []int32(slices.Collect(class(self).GetJoints().Values()))
}

// SetJoints sets the property returned by [GetJoints]. Returns the instance, so that property settings can be chained.
func (self Instance) SetJoints(value []int32) Instance { //gd:GLTFSkin.joints
	class(self).SetJoints(Packed.New(value...))
	return self
}

func (self Instance) NonJoints() []int32 { //gd:GLTFSkin.non_joints
	return []int32(slices.Collect(class(self).GetNonJoints().Values()))
}

// SetNonJoints sets the property returned by [GetNonJoints]. Returns the instance, so that property settings can be chained.
func (self Instance) SetNonJoints(value []int32) Instance { //gd:GLTFSkin.non_joints
	class(self).SetNonJoints(Packed.New(value...))
	return self
}

func (self Instance) Roots() []int32 { //gd:GLTFSkin.roots
	return []int32(slices.Collect(class(self).GetRoots().Values()))
}

// SetRoots sets the property returned by [GetRoots]. Returns the instance, so that property settings can be chained.
func (self Instance) SetRoots(value []int32) Instance { //gd:GLTFSkin.roots
	class(self).SetRoots(Packed.New(value...))
	return self
}

func (self Instance) Skeleton() int { //gd:GLTFSkin.skeleton
	return int(int(class(self).GetSkeleton()))
}

// SetSkeleton sets the property returned by [GetSkeleton]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSkeleton(value int) Instance { //gd:GLTFSkin.skeleton
	class(self).SetSkeleton(int64(value))
	return self
}

func (self Instance) JointIToBoneI() map[int]int { //gd:GLTFSkin.joint_i_to_bone_i
	return map[int]int(gd.DictionaryAs[map[int]int](class(self).GetJointIToBoneI()))
}

// SetJointIToBoneI sets the property returned by [GetJointIToBoneI]. Returns the instance, so that property settings can be chained.
func (self Instance) SetJointIToBoneI(value map[int]int) Instance { //gd:GLTFSkin.joint_i_to_bone_i
	class(self).SetJointIToBoneI(gd.DictionaryFromMap(value))
	return self
}

func (self Instance) JointIToName() map[int]string { //gd:GLTFSkin.joint_i_to_name
	return map[int]string(gd.DictionaryAs[map[int]string](class(self).GetJointIToName()))
}

// SetJointIToName sets the property returned by [GetJointIToName]. Returns the instance, so that property settings can be chained.
func (self Instance) SetJointIToName(value map[int]string) Instance { //gd:GLTFSkin.joint_i_to_name
	class(self).SetJointIToName(gd.DictionaryFromMap(value))
	return self
}

func (self Instance) GodotSkin() Skin.Instance { //gd:GLTFSkin.godot_skin
	return Skin.Instance(class(self).GetGodotSkin())
}

// SetGodotSkin sets the property returned by [GetGodotSkin]. Returns the instance, so that property settings can be chained.
func (self Instance) SetGodotSkin(value Skin.Instance) Instance { //gd:GLTFSkin.godot_skin
	class(self).SetGodotSkin(value)
	return self
}

func (self class) GetSkinRoot() int64 { //gd:GLTFSkin.get_skin_root
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_skin_root, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSkinRoot(skin_root int64) { //gd:GLTFSkin.set_skin_root
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_skin_root, 0|(gdextension.SizeInt<<4), &struct{ skin_root int64 }{skin_root})
}
func (self class) GetJointsOriginal() Packed.Array[int32] { //gd:GLTFSkin.get_joints_original
	var r_ret = noescape.Call[gd.PackedPointers](gd.ObjectChecked(self.AsObject()), methods.get_joints_original, gdextension.SizePackedArray, &struct{}{})
	var ret = Packed.Array[int32](Array.Through(gd.PackedProxy[gd.PackedInt32Array, int32]{}, pointers.Pack(pointers.Let[gd.PackedStringArray](r_ret))))
	return ret
}
func (self class) SetJointsOriginal(joints_original Packed.Array[int32]) { //gd:GLTFSkin.set_joints_original
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_joints_original, 0|(gdextension.SizePackedArray<<4), &struct {
		joints_original gdextension.PackedArray[int32]
	}{pointers.Get(gd.InternalPacked[gd.PackedInt32Array, int32](joints_original))})
}
func (self class) GetInverseBinds() Array.Contains[Transform3D.BasisOrigin] { //gd:GLTFSkin.get_inverse_binds
	var r_ret = noescape.Call[gdextension.Array](gd.ObjectChecked(self.AsObject()), methods.get_inverse_binds, gdextension.SizeArray, &struct{}{})
	var ret = Array.Through(gd.ArrayProxy[Transform3D.BasisOrigin]{}, pointers.Pack(pointers.New[gd.Array](r_ret)))
	return ret
}
func (self class) SetInverseBinds(inverse_binds Array.Contains[Transform3D.BasisOrigin]) { //gd:GLTFSkin.set_inverse_binds
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_inverse_binds, 0|(gdextension.SizeArray<<4), &struct{ inverse_binds gdextension.Array }{pointers.Get(gd.InternalArray(inverse_binds))})
}
func (self class) GetJoints() Packed.Array[int32] { //gd:GLTFSkin.get_joints
	var r_ret = noescape.Call[gd.PackedPointers](gd.ObjectChecked(self.AsObject()), methods.get_joints, gdextension.SizePackedArray, &struct{}{})
	var ret = Packed.Array[int32](Array.Through(gd.PackedProxy[gd.PackedInt32Array, int32]{}, pointers.Pack(pointers.Let[gd.PackedStringArray](r_ret))))
	return ret
}
func (self class) SetJoints(joints Packed.Array[int32]) { //gd:GLTFSkin.set_joints
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_joints, 0|(gdextension.SizePackedArray<<4), &struct {
		joints gdextension.PackedArray[int32]
	}{pointers.Get(gd.InternalPacked[gd.PackedInt32Array, int32](joints))})
}
func (self class) GetNonJoints() Packed.Array[int32] { //gd:GLTFSkin.get_non_joints
	var r_ret = noescape.Call[gd.PackedPointers](gd.ObjectChecked(self.AsObject()), methods.get_non_joints, gdextension.SizePackedArray, &struct{}{})
	var ret = Packed.Array[int32](Array.Through(gd.PackedProxy[gd.PackedInt32Array, int32]{}, pointers.Pack(pointers.Let[gd.PackedStringArray](r_ret))))
	return ret
}
func (self class) SetNonJoints(non_joints Packed.Array[int32]) { //gd:GLTFSkin.set_non_joints
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_non_joints, 0|(gdextension.SizePackedArray<<4), &struct {
		non_joints gdextension.PackedArray[int32]
	}{pointers.Get(gd.InternalPacked[gd.PackedInt32Array, int32](non_joints))})
}
func (self class) GetRoots() Packed.Array[int32] { //gd:GLTFSkin.get_roots
	var r_ret = noescape.Call[gd.PackedPointers](gd.ObjectChecked(self.AsObject()), methods.get_roots, gdextension.SizePackedArray, &struct{}{})
	var ret = Packed.Array[int32](Array.Through(gd.PackedProxy[gd.PackedInt32Array, int32]{}, pointers.Pack(pointers.Let[gd.PackedStringArray](r_ret))))
	return ret
}
func (self class) SetRoots(roots Packed.Array[int32]) { //gd:GLTFSkin.set_roots
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_roots, 0|(gdextension.SizePackedArray<<4), &struct {
		roots gdextension.PackedArray[int32]
	}{pointers.Get(gd.InternalPacked[gd.PackedInt32Array, int32](roots))})
}
func (self class) GetSkeleton() int64 { //gd:GLTFSkin.get_skeleton
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_skeleton, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetSkeleton(skeleton int64) { //gd:GLTFSkin.set_skeleton
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_skeleton, 0|(gdextension.SizeInt<<4), &struct{ skeleton int64 }{skeleton})
}
func (self class) GetJointIToBoneI() Dictionary.Any { //gd:GLTFSkin.get_joint_i_to_bone_i
	var r_ret = noescape.Call[gdextension.Dictionary](gd.ObjectChecked(self.AsObject()), methods.get_joint_i_to_bone_i, gdextension.SizeDictionary, &struct{}{})
	var ret = Dictionary.Through(gd.DictionaryProxy[variant.Any, variant.Any]{}, pointers.Pack(pointers.New[gd.Dictionary](r_ret)))
	return ret
}
func (self class) SetJointIToBoneI(joint_i_to_bone_i Dictionary.Any) { //gd:GLTFSkin.set_joint_i_to_bone_i
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_joint_i_to_bone_i, 0|(gdextension.SizeDictionary<<4), &struct{ joint_i_to_bone_i gdextension.Dictionary }{pointers.Get(gd.InternalDictionary(joint_i_to_bone_i))})
}
func (self class) GetJointIToName() Dictionary.Any { //gd:GLTFSkin.get_joint_i_to_name
	var r_ret = noescape.Call[gdextension.Dictionary](gd.ObjectChecked(self.AsObject()), methods.get_joint_i_to_name, gdextension.SizeDictionary, &struct{}{})
	var ret = Dictionary.Through(gd.DictionaryProxy[variant.Any, variant.Any]{}, pointers.Pack(pointers.New[gd.Dictionary](r_ret)))
	return ret
}
func (self class) SetJointIToName(joint_i_to_name Dictionary.Any) { //gd:GLTFSkin.set_joint_i_to_name
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_joint_i_to_name, 0|(gdextension.SizeDictionary<<4), &struct{ joint_i_to_name gdextension.Dictionary }{pointers.Get(gd.InternalDictionary(joint_i_to_name))})
}
func (self class) GetGodotSkin() [1]gdclass.Skin { //gd:GLTFSkin.get_godot_skin
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_godot_skin, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.Skin{gdclass.NewSkin(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) SetGodotSkin(godot_skin [1]gdclass.Skin) { //gd:GLTFSkin.set_godot_skin
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_godot_skin, 0|(gdextension.SizeObject<<4), &struct{ godot_skin gdextension.Object }{gdextension.Object(gdreference.GetObject(gdclass.GetSkin(godot_skin[0])[0]))})
}
func (o class) AsGLTFSkin() Advanced                  { return Advanced(o) }
func (o Instance) AsGLTFSkin() Instance               { return o }
func (o *Extension[T]) AsGLTFSkin() Instance          { return o.Super() }
func (o class) AsResource() Resource.Advanced         { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance      { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC                   { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC           { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Resource.Advanced(self.AsResource()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Resource.Instance(self.AsResource()), name)
	}
}
func init() {
	gdclass.Register("GLTFSkin", func(ptr gd.Object) any { return Instance{gdclass.NewGLTFSkin(ptr)} })
}
