// Code generated by graphics.gd. DO NOT EDIT.

package flowers

import (
	"graphics.gd/classdb/ArrayMesh"
	"graphics.gd/classdb/MeshInstance3D"
	"graphics.gd/classdb/PackedScene"
	"graphics.gd/classdb/Resource"
)

var OBJ = Resource.Library[struct {
	FlowerPatch ArrayMesh.Instance `gd:"res://Environment/flowers/flower_patch.obj"`
}]()

var TSCN = Resource.Library[struct {
	FlowerPatch PackedScene.Is[SceneFlowerPatch] `gd:"res://Environment/flowers/flower_patch.tscn"`
}]()

type SceneFlowerPatch struct {
	MeshInstance3D.Instance `gd:"res://Environment/flowers/flower_patch.tscn"`
}
