// Code generated by the generate package DO NOT EDIT

/*
Provides language server functionality related to the workspace.
*/
package GDScriptWorkspace

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.GDScriptWorkspace

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	apply_new_signal    gdextension.MethodForClass `hash:"3682583557"`
	get_file_path       gdextension.MethodForClass `hash:"1703090593"`
	get_file_uri        gdextension.MethodForClass `hash:"3135753539"`
	generate_script_api gdextension.MethodForClass `hash:"2786125124"`
	didDeleteFiles      gdextension.MethodForClass `hash:"4155329257"`
	parse_script        gdextension.MethodForClass `hash:"852856452"`
	parse_local_script  gdextension.MethodForClass `hash:"166001499"`
	publish_diagnostics gdextension.MethodForClass `hash:"83702148"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("GDScriptWorkspace")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, true)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsGDScriptWorkspace() Instance
}

func (self Instance) ApplyNewSignal(obj Object.Instance, function string, args []string) { //gd:GDScriptWorkspace.apply_new_signal
	Advanced(self).ApplyNewSignal(obj, String.From(function), Packed.MakeStrings(args...))
}

/*
Converts a URI to a file path.
*/
func (self Instance) GetFilePath(uri string) string { //gd:GDScriptWorkspace.get_file_path
	return string(Advanced(self).GetFilePath(String.From(uri)).String())
}

/*
Converts a file path to a URI.
*/
func (self Instance) GetFileUri(path string) string { //gd:GDScriptWorkspace.get_file_uri
	return string(Advanced(self).GetFileUri(String.From(path)).String())
}

/*
Returns the interface of the script in a machine-readable format.
*/
func (self Instance) GenerateScriptApi(path string) map[string]any { //gd:GDScriptWorkspace.generate_script_api
	return map[string]any(gd.DictionaryAs[map[string]any](Advanced(self).GenerateScriptApi(String.From(path))))
}
func (self Instance) Diddeletefiles(params map[string]any) { //gd:GDScriptWorkspace.didDeleteFiles
	Advanced(self).Diddeletefiles(gd.DictionaryFromMap(params))
}
func (self Instance) ParseScript(path string, content string) error { //gd:GDScriptWorkspace.parse_script
	return error(gd.ToError(Advanced(self).ParseScript(String.From(path), String.From(content))))
}
func (self Instance) ParseLocalScript(path string) error { //gd:GDScriptWorkspace.parse_local_script
	return error(gd.ToError(Advanced(self).ParseLocalScript(String.From(path))))
}
func (self Instance) PublishDiagnostics(path string) { //gd:GDScriptWorkspace.publish_diagnostics
	Advanced(self).PublishDiagnostics(String.From(path))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.GDScriptWorkspace

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewGDScriptWorkspace(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewGDScriptWorkspace(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.GDScriptWorkspace{gdclass.NewGDScriptWorkspace(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetGDScriptWorkspace(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.GDScriptWorkspace{gdclass.NewGDScriptWorkspace(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self class) ApplyNewSignal(obj [1]gdreference.Object, function String.Readable, args Packed.Strings) { //gd:GDScriptWorkspace.apply_new_signal
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.apply_new_signal, 0|(gdextension.SizeObject<<4)|(gdextension.SizeString<<8)|(gdextension.SizePackedArray<<12), &struct {
		obj      gdextension.Object
		function gdextension.String
		args     gdextension.PackedArray[gdextension.String]
	}{gdextension.Object(gdreference.GetObject(gdclass.GetObject(obj[0])[0])), pointers.Get(gd.InternalString(function)), pointers.Get(gd.InternalPackedStrings(args))})
}
func (self class) GetFilePath(uri String.Readable) String.Readable { //gd:GDScriptWorkspace.get_file_path
	var r_ret = noescape.Call[gdextension.String](gd.ObjectChecked(self.AsObject()), methods.get_file_path, gdextension.SizeString|(gdextension.SizeString<<4), &struct{ uri gdextension.String }{pointers.Get(gd.InternalString(uri))})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) GetFileUri(path String.Readable) String.Readable { //gd:GDScriptWorkspace.get_file_uri
	var r_ret = noescape.Call[gdextension.String](gd.ObjectChecked(self.AsObject()), methods.get_file_uri, gdextension.SizeString|(gdextension.SizeString<<4), &struct{ path gdextension.String }{pointers.Get(gd.InternalString(path))})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) GenerateScriptApi(path String.Readable) Dictionary.Any { //gd:GDScriptWorkspace.generate_script_api
	var r_ret = noescape.Call[gdextension.Dictionary](gd.ObjectChecked(self.AsObject()), methods.generate_script_api, gdextension.SizeDictionary|(gdextension.SizeString<<4), &struct{ path gdextension.String }{pointers.Get(gd.InternalString(path))})
	var ret = Dictionary.Through(gd.DictionaryProxy[variant.Any, variant.Any]{}, pointers.Pack(pointers.New[gd.Dictionary](r_ret)))
	return ret
}
func (self class) Diddeletefiles(params Dictionary.Any) { //gd:GDScriptWorkspace.didDeleteFiles
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.didDeleteFiles, 0|(gdextension.SizeDictionary<<4), &struct{ params gdextension.Dictionary }{pointers.Get(gd.InternalDictionary(params))})
}
func (self class) ParseScript(path String.Readable, content String.Readable) Error.Code { //gd:GDScriptWorkspace.parse_script
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.parse_script, gdextension.SizeInt|(gdextension.SizeString<<4)|(gdextension.SizeString<<8), &struct {
		path    gdextension.String
		content gdextension.String
	}{pointers.Get(gd.InternalString(path)), pointers.Get(gd.InternalString(content))})
	var ret = Error.Code(r_ret)
	return ret
}
func (self class) ParseLocalScript(path String.Readable) Error.Code { //gd:GDScriptWorkspace.parse_local_script
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.parse_local_script, gdextension.SizeInt|(gdextension.SizeString<<4), &struct{ path gdextension.String }{pointers.Get(gd.InternalString(path))})
	var ret = Error.Code(r_ret)
	return ret
}
func (self class) PublishDiagnostics(path String.Readable) { //gd:GDScriptWorkspace.publish_diagnostics
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.publish_diagnostics, 0|(gdextension.SizeString<<4), &struct{ path gdextension.String }{pointers.Get(gd.InternalString(path))})
}
func (o class) AsGDScriptWorkspace() Advanced         { return Advanced(o) }
func (o Instance) AsGDScriptWorkspace() Instance      { return o }
func (o *Extension[T]) AsGDScriptWorkspace() Instance { return o.Super() }
func (o class) AsRefCounted() ie.RC                   { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC           { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Advanced(self.AsRefCounted()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Instance(self.AsRefCounted()), name)
	}
}
func init() {
	gdclass.Register("GDScriptWorkspace", func(ptr gdreference.Object) any { return Instance{gdclass.NewGDScriptWorkspace(ptr)} })
}
