// Code generated by graphics.gd. DO NOT EDIT.

package level

import (
	"graphics.gd/classdb/Node2D"
	"graphics.gd/classdb/PackedScene"
	"graphics.gd/classdb/ParallaxBackground"
	"graphics.gd/classdb/ParallaxLayer"
	"graphics.gd/classdb/Resource"
	"graphics.gd/classdb/Sprite2D"
)

var TSCN = Resource.Library[struct {
	ParallaxBackground PackedScene.Is[SceneParallaxBackground] `gd:"res://level/parallax_background.tscn"`
}]()

type SceneParallaxBackground struct {
	ParallaxBackground.Instance `gd:"res://level/parallax_background.tscn"`

	Sky struct {
		ParallaxLayer.Instance

		Sprite2D Sprite2D.Instance
	}
	Clouds struct {
		ParallaxLayer.Instance

		CloudGroup1 struct {
			Node2D.Instance

			Sprite1 Sprite2D.Instance
			Sprite2 Sprite2D.Instance
			Sprite3 Sprite2D.Instance
			Sprite4 Sprite2D.Instance
			Sprite5 Sprite2D.Instance
			Sprite6 Sprite2D.Instance
		}
		CloudGroup2 struct {
			Node2D.Instance

			Sprite1 Sprite2D.Instance
			Sprite2 Sprite2D.Instance
			Sprite3 Sprite2D.Instance
			Sprite4 Sprite2D.Instance
			Sprite5 Sprite2D.Instance
			Sprite6 Sprite2D.Instance
		}
		CloudGroup3 struct {
			Node2D.Instance

			Sprite1 Sprite2D.Instance
			Sprite2 Sprite2D.Instance
			Sprite3 Sprite2D.Instance
			Sprite4 Sprite2D.Instance
			Sprite5 Sprite2D.Instance
			Sprite6 Sprite2D.Instance
		}
		CloudGroup4 struct {
			Node2D.Instance

			Sprite1 Sprite2D.Instance
			Sprite2 Sprite2D.Instance
			Sprite3 Sprite2D.Instance
			Sprite4 Sprite2D.Instance
			Sprite5 Sprite2D.Instance
			Sprite6 Sprite2D.Instance
		}
	}
	Mountains2 struct {
		ParallaxLayer.Instance

		Sprite2D Sprite2D.Instance
	}
	Mountains1 struct {
		ParallaxLayer.Instance

		Sprite2D Sprite2D.Instance
	}
}
