// Code generated by the generate package DO NOT EDIT

/*
JavaScriptObject is used to interact with JavaScript objects retrieved or created via [JavaScriptBridge.GetInterface], [JavaScriptBridge.CreateObject], or [JavaScriptBridge.CreateCallback].

	package main

	import (
		"fmt"

		"graphics.gd/classdb/JavaScriptBridge"
		"graphics.gd/classdb/JavaScriptObject"
		"graphics.gd/classdb/Node"
		"graphics.gd/variant/Object"
	)

	type MyJavaScriptObjects struct {
		Node.Extension[MyJavaScriptObjects]

		my_js_callback JavaScriptObject.Instance
		console        Object.Instance
	}

	func (n MyJavaScriptObjects) Init() {
		n.my_js_callback = JavaScriptBridge.CreateCallback(func(args []any) any {
			fmt.Println(args)
			return nil
		})

		var buf = JavaScriptBridge.CreateObject("ArrayBuffer", 10)
		fmt.Println(buf)
		var uint8arr = JavaScriptBridge.CreateObject("Uint8Array", buf).(Object.Instance)
		Object.SetIndex(uint8arr, 1, 255)
		fmt.Println(Object.Index(uint8arr, 1), Object.Get(uint8arr, "byteLength"))

		Object.Call(n.console, "log", uint8arr)

		Object.Call(Object.Call(JavaScriptBridge.GetInterface("Array"), "from").(Object.Instance), "forEach", n.my_js_callback)
	}

Note: Only available in the Web platform.

[JavaScriptBridge.CreateCallback]: https://pkg.go.dev/graphics.gd/classdb/JavaScriptBridge#CreateCallback
[JavaScriptBridge.CreateObject]: https://pkg.go.dev/graphics.gd/classdb/JavaScriptBridge#CreateObject
[JavaScriptBridge.GetInterface]: https://pkg.go.dev/graphics.gd/classdb/JavaScriptBridge#GetInterface
*/
package JavaScriptObject

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create an extension of this class.
T should be the type that is embedding this [Extension]
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.JavaScriptObject

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("JavaScriptObject")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		gdextension.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsJavaScriptObject() Instance
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.JavaScriptObject

func (self class) AsObject() [1]gd.Object { return self[0].AsObject() }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = pointers.AsA[gdclass.JavaScriptObject](obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = pointers.AsA[gdclass.JavaScriptObject](obj[0])
		return true
	}
	return false
}
func (self Instance) AsObject() [1]gd.Object      { return self[0].AsObject() }
func (self *Extension[T]) AsObject() [1]gd.Object { return self.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.JavaScriptObject{pointers.Add[gdclass.JavaScriptObject]([3]uint64{})})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := pointers.End(New().AsObject()[0])
				pointers.Set(pointers.AsA[gd.Object](placeholder[0]), raw)
				gd.RegisterCleanup(func() {
					if raw := pointers.Get[gd.Object](placeholder.AsObject()[0]); raw[0] != 0 && raw[1] == 0 {
						gdextension.Host.Objects.Unsafe.Free(gdextension.Object(raw[0]))
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.JavaScriptObject{pointers.New[gdclass.JavaScriptObject]([3]uint64{uint64(gdextension.Host.Objects.Make(sname))})})
	casted.AsRefCounted()[0].InitRef()
	casted.AsObject()[0].Notification(0, false)
	return casted
}

func (self class) AsJavaScriptObject() Advanced {
	return Advanced{pointers.AsA[gdclass.JavaScriptObject](self[0])}
}
func (self Instance) AsJavaScriptObject() Instance {
	return Instance{pointers.AsA[gdclass.JavaScriptObject](self[0])}
}
func (self *Extension[T]) AsJavaScriptObject() Instance { return self.Super().AsJavaScriptObject() }
func (self class) AsRefCounted() [1]gd.RefCounted {
	return [1]gd.RefCounted{gd.RefCounted(pointers.AsA[gd.Object](self[0]))}
}
func (self *Extension[T]) AsRefCounted() [1]gd.RefCounted { return self.Super().AsRefCounted() }
func (self Instance) AsRefCounted() [1]gd.RefCounted {
	return [1]gd.RefCounted{gd.RefCounted(pointers.AsA[gd.Object](self[0]))}
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Advanced(self.AsRefCounted()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Instance(self.AsRefCounted()), name)
	}
}
func init() {
	gdclass.Register("JavaScriptObject", func(ptr gd.Object) any { return Instance{pointers.AsA[gdclass.JavaScriptObject](ptr)} })
}
