// Code generated by the generate package DO NOT EDIT

/*
This class is used to store the state of a DTLS server. Upon [Setup] it converts connected [PacketPeerUDP] to [PacketPeerDTLS] accepting them via [TakeConnection] as DTLS clients. Under the hood, this class is used to store the DTLS state and cookies of the server. The reason of why the state and cookies are needed is outside of the scope of this documentation.

Below a small example of how to use it:

	package main

	import (
		"fmt"

		"graphics.gd/classdb/CryptoKey"
		"graphics.gd/classdb/DTLSServer"
		"graphics.gd/classdb/Node"
		"graphics.gd/classdb/PacketPeerDTLS"
		"graphics.gd/classdb/Resource"
		"graphics.gd/classdb/TLSOptions"
		"graphics.gd/classdb/UDPServer"
		"graphics.gd/classdb/X509Certificate"
		"graphics.gd/variant/Float"
	)

	type ServerDTLS struct {
		Node.Extension[ServerDTLS]

		dtls  DTLSServer.Instance
		udp   UDPServer.Instance
		peers []PacketPeerDTLS.Instance
	}

	func (srv *ServerDTLS) Ready() {
		srv.udp.Listen(4242)
		var key = Resource.Load[CryptoKey.Instance]("key.key")
		var cert = Resource.Load[X509Certificate.Instance]("cert.crt")
		srv.dtls.Setup(TLSOptions.Server(key, cert))
	}

	func (srv *ServerDTLS) Process(delta Float.X) {
		for srv.udp.IsConnectionAvailable() {
			var peer = srv.udp.TakeConnection()
			var dtlsPeer = srv.dtls.TakeConnection(peer)
			if dtlsPeer.GetStatus() != PacketPeerDTLS.StatusHandshaking {
				continue // It is normal that 50%!o(MISSING)f the connections fails due to cookie exchange.
			}
			fmt.Println("Peer connected!")
			srv.peers = append(srv.peers, dtlsPeer)
		}
		for _, p := range srv.peers {
			p.Poll() // Must poll to update the state.
			if p.GetStatus() == PacketPeerDTLS.StatusConnected {
				for p.AsPacketPeer().GetAvailablePacketCount() > 0 {
					fmt.Println("Received message from client: ", string(p.AsPacketPeer().GetPacket()))
					p.AsPacketPeer().PutPacket([]byte("Hello DTLS client"))
				}
			}
		}
	}


	package main

	import (
		"fmt"

		"graphics.gd/classdb/Node"
		"graphics.gd/classdb/PacketPeerDTLS"
		"graphics.gd/classdb/PacketPeerUDP"
		"graphics.gd/variant/Float"
	)

	type ClientDTLS struct {
		Node.Extension[ClientDTLS]

		dtls PacketPeerDTLS.Instance
		udp  PacketPeerUDP.Instance

		connected bool
	}

	func (srv *ClientDTLS) Ready() {
		srv.udp.ConnectToHost("127.0.0.1", 4242)
		srv.dtls.ConnectToPeer(srv.udp, "") // Use hostname in production for certificate validation!
	}

	func (srv *ClientDTLS) Process(delta Float.X) {
		srv.dtls.Poll()
		if srv.dtls.GetStatus() == PacketPeerDTLS.StatusConnected {
			if !srv.connected {
				// Try to contact server
				srv.dtls.AsPacketPeer().PutPacket([]byte("The Answer Is... 42!"))
			}
			for srv.dtls.AsPacketPeer().GetAvailablePacketCount() > 0 {
				fmt.Println("Connected: " + string(srv.dtls.AsPacketPeer().GetPacket()))
				srv.connected = true
			}
		}
	}

[PacketPeerDTLS]: https://pkg.go.dev/graphics.gd/classdb/PacketPeerDTLS
[PacketPeerUDP]: https://pkg.go.dev/graphics.gd/classdb/PacketPeerUDP
[Setup]: https://pkg.go.dev/graphics.gd/classdb/DTLSServer#Instance.Setup
[TakeConnection]: https://pkg.go.dev/graphics.gd/classdb/DTLSServer#Instance.TakeConnection
*/
package DTLSServer

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gdunsafe "graphics.gd"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/PacketPeerDTLS"
import "graphics.gd/classdb/PacketPeerUDP"
import "graphics.gd/classdb/TLSOptions"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ gdunsafe.Object
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.DTLSServer

var otype gdunsafe.ObjectType
var sname gdextension.StringName
var methods struct {
	setup           gdextension.MethodForClass `hash:"1262296096"`
	take_connection gdextension.MethodForClass `hash:"3946580474"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.StringName{gdextension.Pointer(gdunsafe.UTF8.Intern("DTLSServer"))}
		otype = gdunsafe.ObjectTypeTag(gdunsafe.StringName(sname[0]))
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsDTLSServer() Instance
}

/*
Setup the DTLS server to use the given 'server_options'. See [TLSOptions.Server].

[TLSOptions.Server]: https://pkg.go.dev/graphics.gd/classdb/TLSOptions#Instance.Server
*/
func (self Instance) Setup(server_options TLSOptions.Instance) error { //gd:DTLSServer.setup
	return error(gd.ToError(Advanced(self).Setup(server_options)))
}

/*
Try to initiate the DTLS handshake with the given 'udp_peer' which must be already connected (see [PacketPeerUDP.ConnectToHost]).

Note: You must check that the state of the return PacketPeerUDP is [Packetpeerdtls.StatusHandshaking], as it is normal that 50% of the new connections will be invalid due to cookie exchange.

[PacketPeerUDP.ConnectToHost]: https://pkg.go.dev/graphics.gd/classdb/PacketPeerUDP#Instance.ConnectToHost
*/
func (self Instance) TakeConnection(udp_peer PacketPeerUDP.Instance) PacketPeerDTLS.Instance { //gd:DTLSServer.take_connection
	return PacketPeerDTLS.Instance(Advanced(self).TakeConnection(udp_peer))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.DTLSServer

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewDTLSServer(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewDTLSServer(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.DTLSServer{gdclass.NewDTLSServer(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetDTLSServer(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdunsafe.Object(raw).Free()
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.DTLSServer{gdclass.NewDTLSServer(gdreference.OwnObject(gdextension.Object(gdunsafe.MakeObject(gdunsafe.StringName(sname[0]))), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

func (self class) Setup(server_options [1]gdclass.TLSOptions) Error.Code { //gd:DTLSServer.setup
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.setup, gdextension.SizeInt|(gdextension.SizeObject<<4), &struct{ server_options gdextension.Object }{gdextension.Object(gdreference.GetObject(gdclass.GetTLSOptions(server_options[0])[0]))})
	var ret = Error.Code(r_ret)
	return ret
}
func (self class) TakeConnection(udp_peer [1]gdclass.PacketPeerUDP) [1]gdclass.PacketPeerDTLS { //gd:DTLSServer.take_connection
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.take_connection, gdextension.SizeObject|(gdextension.SizeObject<<4), &struct{ udp_peer gdextension.Object }{gdextension.Object(gdreference.GetObject(gdclass.GetPacketPeerUDP(udp_peer[0])[0]))})
	var ret = [1]gdclass.PacketPeerDTLS{gdclass.NewPacketPeerDTLS(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (o class) AsDTLSServer() Advanced         { return Advanced(o) }
func (o Instance) AsDTLSServer() Instance      { return o }
func (o *Extension[T]) AsDTLSServer() Instance { return o.Super() }
func (o class) AsRefCounted() ie.RC            { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC    { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC         { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Advanced(self.AsRefCounted()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Instance(self.AsRefCounted()), name)
	}
}
func init() {
	gdclass.Register("DTLSServer", func(ptr gdreference.Object) any { return Instance{gdclass.NewDTLSServer(ptr)} })
}
