// Code generated by the generate package DO NOT EDIT

/*
A directional light is a type of [Light2D] node that models an infinite number of parallel rays covering the entire scene. It is used for lights with strong intensity that are located far away from the scene (for example: to model sunlight or moonlight).

Light is emitted in the +Y direction of the node's global basis. For an unrotated light, this means that the light is emitted downwards. The position of the node is ignored; only the basis is used to determine light direction.

Note: [DirectionalLight2D] does not support light cull masks (but it supports shadow cull masks). It will always light up 2D nodes, regardless of the 2D node's [CanvasItem.LightMask].

[CanvasItem.LightMask]: https://pkg.go.dev/graphics.gd/classdb/CanvasItem#Instance.LightMask
[DirectionalLight2D]: https://pkg.go.dev/graphics.gd/classdb/DirectionalLight2D
[Light2D]: https://pkg.go.dev/graphics.gd/classdb/Light2D
*/
package DirectionalLight2D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/CanvasItem"
import "graphics.gd/classdb/Light2D"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Node2D"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.DirectionalLight2D

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_max_distance gdextension.MethodForClass `hash:"373806689"`
	get_max_distance gdextension.MethodForClass `hash:"1740695150"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("DirectionalLight2D")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsDirectionalLight2D() Instance
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.DirectionalLight2D

func (o class) AsObject() [1]gd.Object { return *(*[1]gd.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewDirectionalLight2D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewDirectionalLight2D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gd.Object      { return *(*[1]gd.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gd.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.DirectionalLight2D{gdclass.NewDirectionalLight2D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetDirectionalLight2D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.DirectionalLight2D{gdclass.NewDirectionalLight2D(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
The maximum distance from the camera center objects can be before their shadows are culled (in pixels). Decreasing this value can prevent objects located outside the camera from casting shadows (while also improving performance). [Camera2D.Zoom] is not taken into account by [MaxDistance], which means that at higher zoom values, shadows will appear to fade out sooner when zooming onto a given point.

[Camera2D.Zoom]: https://pkg.go.dev/graphics.gd/classdb/Camera2D#Instance.Zoom
[MaxDistance]: https://pkg.go.dev/graphics.gd/classdb/DirectionalLight2D#Instance.MaxDistance
*/
func (self Instance) MaxDistance() Float.X { //gd:DirectionalLight2D.max_distance
	return Float.X(Float.X(class(self).GetMaxDistance()))
}

// SetMaxDistance sets the property returned by [GetMaxDistance]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMaxDistance(value Float.X) Instance { //gd:DirectionalLight2D.max_distance
	class(self).SetMaxDistance(float64(value))
	return self
}

func (self class) SetMaxDistance(pixels float64) { //gd:DirectionalLight2D.set_max_distance
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_max_distance, 0|(gdextension.SizeFloat<<4), &struct{ pixels float64 }{pixels})
}
func (self class) GetMaxDistance() float64 { //gd:DirectionalLight2D.get_max_distance
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_max_distance, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsDirectionalLight2D() Advanced            { return Advanced(o) }
func (o Instance) AsDirectionalLight2D() Instance         { return o }
func (o *Extension[T]) AsDirectionalLight2D() Instance    { return o.Super() }
func (o class) AsLight2D() Light2D.Advanced               { return *(*Light2D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsLight2D() Light2D.Instance       { return o.Super().AsLight2D() }
func (o Instance) AsLight2D() Light2D.Instance            { return *(*Light2D.Instance)(ie.As(&o)) }
func (o class) AsNode2D() Node2D.Advanced                 { return *(*Node2D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode2D() Node2D.Instance         { return o.Super().AsNode2D() }
func (o Instance) AsNode2D() Node2D.Instance              { return *(*Node2D.Instance)(ie.As(&o)) }
func (o class) AsCanvasItem() CanvasItem.Advanced         { return *(*CanvasItem.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsCanvasItem() CanvasItem.Instance { return o.Super().AsCanvasItem() }
func (o Instance) AsCanvasItem() CanvasItem.Instance      { return *(*CanvasItem.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced                     { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance             { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance                  { return *(*Node.Instance)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Light2D.Advanced(self.AsLight2D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Light2D.Instance(self.AsLight2D()), name)
	}
}
func init() {
	gdclass.Register("DirectionalLight2D", func(ptr gd.Object) any { return Instance{gdclass.NewDirectionalLight2D(ptr)} })
}
