// Code generated by the generate package DO NOT EDIT

/*
A real-time heightmap-shaped 3D particle collision shape affecting [GPUParticles3D] nodes.

Heightmap shapes allow for efficiently representing collisions for convex and concave objects with a single "floor" (such as terrain). This is less flexible than [GPUParticlesCollisionSDF3D], but it doesn't require a baking step.

[GPUParticlesCollisionHeightField3D] can also be regenerated in real-time when it is moved, when the camera moves, or even continuously. This makes [GPUParticlesCollisionHeightField3D] a good choice for weather effects such as rain and snow and games with highly dynamic geometry. However, this class is limited since heightmaps cannot represent overhangs (e.g. indoors or caves).

Note: [ParticleProcessMaterial.CollisionMode] must be true on the [GPUParticles3D]'s process material for collision to work.

Note: Particle collision only affects [GPUParticles3D], not [CPUParticles3D].

[CPUParticles3D]: https://pkg.go.dev/graphics.gd/classdb/CPUParticles3D
[GPUParticles3D]: https://pkg.go.dev/graphics.gd/classdb/GPUParticles3D
[GPUParticlesCollisionHeightField3D]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D
[GPUParticlesCollisionSDF3D]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionSDF3D
[ParticleProcessMaterial.CollisionMode]: https://pkg.go.dev/graphics.gd/classdb/ParticleProcessMaterial#Instance.CollisionMode
*/
package GPUParticlesCollisionHeightField3D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/GPUParticlesCollision3D"
import "graphics.gd/classdb/Node"
import "graphics.gd/classdb/Node3D"
import "graphics.gd/classdb/VisualInstance3D"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Vector3"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.GPUParticlesCollisionHeightField3D

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_size                   gdextension.MethodForClass `hash:"3460891852"`
	get_size                   gdextension.MethodForClass `hash:"3360562783"`
	set_resolution             gdextension.MethodForClass `hash:"1009996517"`
	get_resolution             gdextension.MethodForClass `hash:"1156065644"`
	set_update_mode            gdextension.MethodForClass `hash:"673680859"`
	get_update_mode            gdextension.MethodForClass `hash:"1998141380"`
	set_heightfield_mask       gdextension.MethodForClass `hash:"1286410249"`
	get_heightfield_mask       gdextension.MethodForClass `hash:"3905245786"`
	set_heightfield_mask_value gdextension.MethodForClass `hash:"300928843"`
	get_heightfield_mask_value gdextension.MethodForClass `hash:"1116898809"`
	set_follow_camera_enabled  gdextension.MethodForClass `hash:"2586408642"`
	is_follow_camera_enabled   gdextension.MethodForClass `hash:"36873697"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("GPUParticlesCollisionHeightField3D")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsGPUParticlesCollisionHeightField3D() Instance
}

/*
Based on 'value', enables or disables the specified layer in the [HeightfieldMask], given a 'layer_number' between 1 and 20, inclusive.

Returns 'self' to enable method chaining.

[HeightfieldMask]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D#Instance.HeightfieldMask
*/
func (self Instance) SetHeightfieldMaskValue(layer_number int, value bool) Instance { //gd:GPUParticlesCollisionHeightField3D.set_heightfield_mask_value
	Advanced(self).SetHeightfieldMaskValue(int64(layer_number), value)
	return self
}

/*
Returns true if the specified layer of the [HeightfieldMask] is enabled, given a 'layer_number' between 1 and 20, inclusive.

[HeightfieldMask]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D#Instance.HeightfieldMask
*/
func (self Instance) GetHeightfieldMaskValue(layer_number int) bool { //gd:GPUParticlesCollisionHeightField3D.get_heightfield_mask_value
	return bool(Advanced(self).GetHeightfieldMaskValue(int64(layer_number)))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.GPUParticlesCollisionHeightField3D

func (o class) AsObject() [1]gd.Object { return *(*[1]gd.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewGPUParticlesCollisionHeightField3D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewGPUParticlesCollisionHeightField3D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gd.Object      { return *(*[1]gd.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gd.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.GPUParticlesCollisionHeightField3D{gdclass.NewGPUParticlesCollisionHeightField3D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetGPUParticlesCollisionHeightField3D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.GPUParticlesCollisionHeightField3D{gdclass.NewGPUParticlesCollisionHeightField3D(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
The collision heightmap's size in 3D units. To improve heightmap quality, [Size] should be set as small as possible while covering the parts of the scene you need.

[Size]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D#Instance.Size
*/
func (self Instance) Size() Vector3.XYZ { //gd:GPUParticlesCollisionHeightField3D.size
	return Vector3.XYZ(class(self).GetSize())
}

// SetSize sets the property returned by [GetSize]. Returns the instance, so that property settings can be chained.
func (self Instance) SetSize(value Vector3.XYZ) Instance { //gd:GPUParticlesCollisionHeightField3D.size
	class(self).SetSize(Vector3.XYZ(value))
	return self
}

/*
Higher resolutions can represent small details more accurately in large scenes, at the cost of lower performance. If [UpdateMode] is [UpdateModeAlways], consider using the lowest resolution possible.

[UpdateMode]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D#Instance.UpdateMode
*/
func (self Instance) Resolution() Resolution { //gd:GPUParticlesCollisionHeightField3D.resolution
	return Resolution(class(self).GetResolution())
}

// SetResolution sets the property returned by [GetResolution]. Returns the instance, so that property settings can be chained.
func (self Instance) SetResolution(value Resolution) Instance { //gd:GPUParticlesCollisionHeightField3D.resolution
	class(self).SetResolution(value)
	return self
}

/*
The update policy to use for the generated heightmap.
*/
func (self Instance) UpdateMode() UpdateMode { //gd:GPUParticlesCollisionHeightField3D.update_mode
	return UpdateMode(class(self).GetUpdateMode())
}

// SetUpdateMode sets the property returned by [GetUpdateMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetUpdateMode(value UpdateMode) Instance { //gd:GPUParticlesCollisionHeightField3D.update_mode
	class(self).SetUpdateMode(value)
	return self
}

/*
If true, the [GPUParticlesCollisionHeightField3D] will follow the current camera in global space. The [GPUParticlesCollisionHeightField3D] does not need to be a child of the [Camera3D] node for this to work.

Following the camera has a performance cost, as it will force the heightmap to update whenever the camera moves. Consider lowering [Resolution] to improve performance if [FollowCameraEnabled] is true.

[Camera3D]: https://pkg.go.dev/graphics.gd/classdb/Camera3D
[FollowCameraEnabled]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D#Instance.FollowCameraEnabled
[GPUParticlesCollisionHeightField3D]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D
[Resolution]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D#Instance.Resolution
*/
func (self Instance) FollowCameraEnabled() bool { //gd:GPUParticlesCollisionHeightField3D.follow_camera_enabled
	return bool(class(self).IsFollowCameraEnabled())
}

// SetFollowCameraEnabled sets the property returned by [IsFollowCameraEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFollowCameraEnabled(value bool) Instance { //gd:GPUParticlesCollisionHeightField3D.follow_camera_enabled
	class(self).SetFollowCameraEnabled(value)
	return self
}

/*
The visual layers to account for when updating the heightmap. Only [MeshInstance3D]s whose [VisualInstance3D.Layers] match with this [HeightfieldMask] will be included in the heightmap collision update. By default, all 20 user-visible layers are taken into account for updating the heightmap collision.

Note: Since the [HeightfieldMask] allows for 32 layers to be stored in total, there are an additional 12 layers that are only used internally by the engine and aren't exposed in the editor. Setting [HeightfieldMask] using a script allows you to toggle those reserved layers, which can be useful for editor plugins.

To adjust [HeightfieldMask] more easily using a script, use [GetHeightfieldMaskValue] and [SetHeightfieldMaskValue].

[GetHeightfieldMaskValue]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D#Instance.GetHeightfieldMaskValue
[HeightfieldMask]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D#Instance.HeightfieldMask
[MeshInstance3D]: https://pkg.go.dev/graphics.gd/classdb/MeshInstance3D
[SetHeightfieldMaskValue]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D#Instance.SetHeightfieldMaskValue
[VisualInstance3D.Layers]: https://pkg.go.dev/graphics.gd/classdb/VisualInstance3D#Instance.Layers
*/
func (self Instance) HeightfieldMask() int { //gd:GPUParticlesCollisionHeightField3D.heightfield_mask
	return int(int(class(self).GetHeightfieldMask()))
}

// SetHeightfieldMask sets the property returned by [GetHeightfieldMask]. Returns the instance, so that property settings can be chained.
func (self Instance) SetHeightfieldMask(value int) Instance { //gd:GPUParticlesCollisionHeightField3D.heightfield_mask
	class(self).SetHeightfieldMask(int64(value))
	return self
}

func (self class) SetSize(size Vector3.XYZ) { //gd:GPUParticlesCollisionHeightField3D.set_size
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_size, 0|(gdextension.SizeVector3<<4), &struct{ size Vector3.XYZ }{size})
}
func (self class) GetSize() Vector3.XYZ { //gd:GPUParticlesCollisionHeightField3D.get_size
	var r_ret = noescape.Call[Vector3.XYZ](gd.ObjectChecked(self.AsObject()), methods.get_size, gdextension.SizeVector3, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetResolution(resolution Resolution) { //gd:GPUParticlesCollisionHeightField3D.set_resolution
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_resolution, 0|(gdextension.SizeInt<<4), &struct{ resolution Resolution }{resolution})
}
func (self class) GetResolution() Resolution { //gd:GPUParticlesCollisionHeightField3D.get_resolution
	var r_ret = noescape.Call[Resolution](gd.ObjectChecked(self.AsObject()), methods.get_resolution, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetUpdateMode(update_mode UpdateMode) { //gd:GPUParticlesCollisionHeightField3D.set_update_mode
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_update_mode, 0|(gdextension.SizeInt<<4), &struct{ update_mode UpdateMode }{update_mode})
}
func (self class) GetUpdateMode() UpdateMode { //gd:GPUParticlesCollisionHeightField3D.get_update_mode
	var r_ret = noescape.Call[UpdateMode](gd.ObjectChecked(self.AsObject()), methods.get_update_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetHeightfieldMask(heightfield_mask int64) { //gd:GPUParticlesCollisionHeightField3D.set_heightfield_mask
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_heightfield_mask, 0|(gdextension.SizeInt<<4), &struct{ heightfield_mask int64 }{heightfield_mask})
}
func (self class) GetHeightfieldMask() int64 { //gd:GPUParticlesCollisionHeightField3D.get_heightfield_mask
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_heightfield_mask, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetHeightfieldMaskValue(layer_number int64, value bool) { //gd:GPUParticlesCollisionHeightField3D.set_heightfield_mask_value
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_heightfield_mask_value, 0|(gdextension.SizeInt<<4)|(gdextension.SizeBool<<8), &struct {
		layer_number int64
		value        bool
	}{layer_number, value})
}
func (self class) GetHeightfieldMaskValue(layer_number int64) bool { //gd:GPUParticlesCollisionHeightField3D.get_heightfield_mask_value
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_heightfield_mask_value, gdextension.SizeBool|(gdextension.SizeInt<<4), &struct{ layer_number int64 }{layer_number})
	var ret = r_ret
	return ret
}
func (self class) SetFollowCameraEnabled(enabled bool) { //gd:GPUParticlesCollisionHeightField3D.set_follow_camera_enabled
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_follow_camera_enabled, 0|(gdextension.SizeBool<<4), &struct{ enabled bool }{enabled})
}
func (self class) IsFollowCameraEnabled() bool { //gd:GPUParticlesCollisionHeightField3D.is_follow_camera_enabled
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_follow_camera_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsGPUParticlesCollisionHeightField3D() Advanced         { return Advanced(o) }
func (o Instance) AsGPUParticlesCollisionHeightField3D() Instance      { return o }
func (o *Extension[T]) AsGPUParticlesCollisionHeightField3D() Instance { return o.Super() }
func (o class) AsGPUParticlesCollision3D() GPUParticlesCollision3D.Advanced {
	return *(*GPUParticlesCollision3D.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsGPUParticlesCollision3D() GPUParticlesCollision3D.Instance {
	return o.Super().AsGPUParticlesCollision3D()
}
func (o Instance) AsGPUParticlesCollision3D() GPUParticlesCollision3D.Instance {
	return *(*GPUParticlesCollision3D.Instance)(ie.As(&o))
}
func (o class) AsVisualInstance3D() VisualInstance3D.Advanced {
	return *(*VisualInstance3D.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsVisualInstance3D() VisualInstance3D.Instance {
	return o.Super().AsVisualInstance3D()
}
func (o Instance) AsVisualInstance3D() VisualInstance3D.Instance {
	return *(*VisualInstance3D.Instance)(ie.As(&o))
}
func (o class) AsNode3D() Node3D.Advanced         { return *(*Node3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode3D() Node3D.Instance { return o.Super().AsNode3D() }
func (o Instance) AsNode3D() Node3D.Instance      { return *(*Node3D.Instance)(ie.As(&o)) }
func (o class) AsNode() Node.Advanced             { return *(*Node.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsNode() Node.Instance     { return o.Super().AsNode() }
func (o Instance) AsNode() Node.Instance          { return *(*Node.Instance)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(GPUParticlesCollision3D.Advanced(self.AsGPUParticlesCollision3D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(GPUParticlesCollision3D.Instance(self.AsGPUParticlesCollision3D()), name)
	}
}
func init() {
	gdclass.Register("GPUParticlesCollisionHeightField3D", func(ptr gd.Object) any { return Instance{gdclass.NewGPUParticlesCollisionHeightField3D(ptr)} })
}

type Resolution int //gd:GPUParticlesCollisionHeightField3D.Resolution

const (
	// Generate a 256×256 heightmap. Intended for small-scale scenes, or larger scenes with no distant particles.
	Resolution256 Resolution = 0
	// Generate a 512×512 heightmap. Intended for medium-scale scenes, or larger scenes with no distant particles.
	Resolution512 Resolution = 1
	// Generate a 1024×1024 heightmap. Intended for large scenes with distant particles.
	Resolution1024 Resolution = 2
	// Generate a 2048×2048 heightmap. Intended for very large scenes with distant particles.
	Resolution2048 Resolution = 3
	// Generate a 4096×4096 heightmap. Intended for huge scenes with distant particles.
	Resolution4096 Resolution = 4
	// Generate a 8192×8192 heightmap. Intended for gigantic scenes with distant particles.
	Resolution8192 Resolution = 5
	// Represents the size of the [Resolution] enum.
	ResolutionMax Resolution = 6
)

type UpdateMode int //gd:GPUParticlesCollisionHeightField3D.UpdateMode

const (
	// Only update the heightmap when the [GPUParticlesCollisionHeightField3D] node is moved, or when the camera moves if [FollowCameraEnabled] is true. An update can be forced by slightly moving the [GPUParticlesCollisionHeightField3D] in any direction, or by calling [RenderingServer.ParticlesCollisionHeightFieldUpdate].
	//
	// [FollowCameraEnabled]: https://pkg.go.dev/graphics.gd/classdb/#Instance.FollowCameraEnabled
	// [GPUParticlesCollisionHeightField3D]: https://pkg.go.dev/graphics.gd/classdb/GPUParticlesCollisionHeightField3D
	// [RenderingServer.ParticlesCollisionHeightFieldUpdate]: https://pkg.go.dev/graphics.gd/classdb/RenderingServer#ParticlesCollisionHeightFieldUpdate
	UpdateModeWhenMoved UpdateMode = 0
	// Update the heightmap every frame. This has a significant performance cost. This update should only be used when geometry that particles can collide with changes significantly during gameplay.
	UpdateModeAlways UpdateMode = 1
)
