// Code generated by the generate package DO NOT EDIT

/*
By changing various properties of this object, such as the ray position, you can configure the parameters for [PhysicsDirectSpaceState2D.IntersectRay].

[PhysicsDirectSpaceState2D.IntersectRay]: https://pkg.go.dev/graphics.gd/classdb/PhysicsDirectSpaceState2D#Instance.IntersectRay
*/
package PhysicsRayQueryParameters2D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gdunsafe "graphics.gd"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Vector2"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ gdunsafe.Object
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.PhysicsRayQueryParameters2D

var otype gdunsafe.ObjectType
var sname gdextension.StringName
var methods struct {
	create                         gdextension.MethodForClass `hash:"3196569324"`
	set_from                       gdextension.MethodForClass `hash:"743155724"`
	get_from                       gdextension.MethodForClass `hash:"3341600327"`
	set_to                         gdextension.MethodForClass `hash:"743155724"`
	get_to                         gdextension.MethodForClass `hash:"3341600327"`
	set_collision_mask             gdextension.MethodForClass `hash:"1286410249"`
	get_collision_mask             gdextension.MethodForClass `hash:"3905245786"`
	set_exclude                    gdextension.MethodForClass `hash:"381264803"`
	get_exclude                    gdextension.MethodForClass `hash:"3995934104"`
	set_collide_with_bodies        gdextension.MethodForClass `hash:"2586408642"`
	is_collide_with_bodies_enabled gdextension.MethodForClass `hash:"36873697"`
	set_collide_with_areas         gdextension.MethodForClass `hash:"2586408642"`
	is_collide_with_areas_enabled  gdextension.MethodForClass `hash:"36873697"`
	set_hit_from_inside            gdextension.MethodForClass `hash:"2586408642"`
	is_hit_from_inside_enabled     gdextension.MethodForClass `hash:"36873697"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.StringName{gdextension.Pointer(gdunsafe.UTF8.Intern("PhysicsRayQueryParameters2D"))}
		otype = gdunsafe.ObjectTypeTag(gdunsafe.StringName(sname[0]))
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsPhysicsRayQueryParameters2D() Instance
}

/*
Returns a new, pre-configured [PhysicsRayQueryParameters2D] object. Use it to quickly create query parameters using the most common options.

	var query = PhysicsRayQueryParameters2D.Create(node2d.GlobalPosition(), Vector2.Add(node2d.GlobalPosition(), Vector2.XY{0, 100}), nil)
	var collision = node2d.AsCanvasItem().GetWorld2d().DirectSpaceState().IntersectRay(query)

[PhysicsRayQueryParameters2D]: https://pkg.go.dev/graphics.gd/classdb/PhysicsRayQueryParameters2D
*/
func Create(from Vector2.XY, to Vector2.XY, exclude []RID.Body2D) Instance { //gd:PhysicsRayQueryParameters2D.create
	self := Instance{}
	return Instance(Advanced(self).Create(Vector2.XY(from), Vector2.XY(to), int64(4294967295), gd.ArrayFromSlice[Array.Contains[RID.Any]](exclude)))
}

/*
Returns a new, pre-configured [PhysicsRayQueryParameters2D] object. Use it to quickly create query parameters using the most common options.

	var query = PhysicsRayQueryParameters2D.Create(node2d.GlobalPosition(), Vector2.Add(node2d.GlobalPosition(), Vector2.XY{0, 100}), nil)
	var collision = node2d.AsCanvasItem().GetWorld2d().DirectSpaceState().IntersectRay(query)

[PhysicsRayQueryParameters2D]: https://pkg.go.dev/graphics.gd/classdb/PhysicsRayQueryParameters2D
*/
func CreateOptions(from Vector2.XY, to Vector2.XY, collision_mask int, exclude []RID.Body2D) Instance { //gd:PhysicsRayQueryParameters2D.create
	self := Instance{}
	return Instance(Advanced(self).Create(Vector2.XY(from), Vector2.XY(to), int64(collision_mask), gd.ArrayFromSlice[Array.Contains[RID.Any]](exclude)))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.PhysicsRayQueryParameters2D

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewPhysicsRayQueryParameters2D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewPhysicsRayQueryParameters2D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.PhysicsRayQueryParameters2D{gdclass.NewPhysicsRayQueryParameters2D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetPhysicsRayQueryParameters2D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdunsafe.Object(raw).Free()
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.PhysicsRayQueryParameters2D{gdclass.NewPhysicsRayQueryParameters2D(gdreference.OwnObject(gdextension.Object(gdunsafe.MakeObject(gdunsafe.StringName(sname[0]))), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
The starting point of the ray being queried for, in global coordinates.
*/
func (self Instance) From() Vector2.XY { //gd:PhysicsRayQueryParameters2D.from
	return Vector2.XY(class(self).GetFrom())
}

// SetFrom sets the property returned by [GetFrom]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFrom(value Vector2.XY) Instance { //gd:PhysicsRayQueryParameters2D.from
	class(self).SetFrom(Vector2.XY(value))
	return self
}

/*
The ending point of the ray being queried for, in global coordinates.
*/
func (self Instance) To() Vector2.XY { //gd:PhysicsRayQueryParameters2D.to
	return Vector2.XY(class(self).GetTo())
}

// SetTo sets the property returned by [GetTo]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTo(value Vector2.XY) Instance { //gd:PhysicsRayQueryParameters2D.to
	class(self).SetTo(Vector2.XY(value))
	return self
}

/*
The physics layers the query will detect (as a bitmask). By default, all collision layers are detected. See [Collision layers and masks] in the documentation for more information.

[Collision layers and masks]: https://docs.godotengine.org/tutorials/physics/physics_introduction.html#collision-layers-and-masks
*/
func (self Instance) CollisionMask() int { //gd:PhysicsRayQueryParameters2D.collision_mask
	return int(int(class(self).GetCollisionMask()))
}

// SetCollisionMask sets the property returned by [GetCollisionMask]. Returns the instance, so that property settings can be chained.
func (self Instance) SetCollisionMask(value int) Instance { //gd:PhysicsRayQueryParameters2D.collision_mask
	class(self).SetCollisionMask(int64(value))
	return self
}

/*
The list of object [Resource.ID]s that will be excluded from collisions. Use [CollisionObject2D.GetRid] to get the [Resource.ID] associated with a [CollisionObject2D]-derived node.

Note: The returned array is copied and any changes to it will not update the original property value. To update the value you need to modify the returned array, and then assign it to the property again.

[CollisionObject2D]: https://pkg.go.dev/graphics.gd/classdb/CollisionObject2D
[CollisionObject2D.GetRid]: https://pkg.go.dev/graphics.gd/classdb/CollisionObject2D#Instance.GetRid
[Resource.ID]: https://pkg.go.dev/graphics.gd/variant/Resource#ID
*/
func (self Instance) Exclude() []RID.Body2D { //gd:PhysicsRayQueryParameters2D.exclude
	return []RID.Body2D(gd.ArrayAs[[]RID.Body2D](gd.InternalArray(class(self).GetExclude())))
}

// SetExclude sets the property returned by [GetExclude]. Returns the instance, so that property settings can be chained.
func (self Instance) SetExclude(value []RID.Body2D) Instance { //gd:PhysicsRayQueryParameters2D.exclude
	class(self).SetExclude(gd.ArrayFromSlice[Array.Contains[RID.Any]](value))
	return self
}

/*
If true, the query will take [PhysicsBody2D]s into account.

[PhysicsBody2D]: https://pkg.go.dev/graphics.gd/classdb/PhysicsBody2D
*/
func (self Instance) CollideWithBodies() bool { //gd:PhysicsRayQueryParameters2D.collide_with_bodies
	return bool(class(self).IsCollideWithBodiesEnabled())
}

// SetCollideWithBodies sets the property returned by [IsCollideWithBodiesEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetCollideWithBodies(value bool) Instance { //gd:PhysicsRayQueryParameters2D.collide_with_bodies
	class(self).SetCollideWithBodies(value)
	return self
}

/*
If true, the query will take [Area2D]s into account.

[Area2D]: https://pkg.go.dev/graphics.gd/classdb/Area2D
*/
func (self Instance) CollideWithAreas() bool { //gd:PhysicsRayQueryParameters2D.collide_with_areas
	return bool(class(self).IsCollideWithAreasEnabled())
}

// SetCollideWithAreas sets the property returned by [IsCollideWithAreasEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetCollideWithAreas(value bool) Instance { //gd:PhysicsRayQueryParameters2D.collide_with_areas
	class(self).SetCollideWithAreas(value)
	return self
}

/*
If true, the query will detect a hit when starting inside shapes. In this case the collision normal will be Vector2(0, 0). Does not affect concave polygon shapes.
*/
func (self Instance) HitFromInside() bool { //gd:PhysicsRayQueryParameters2D.hit_from_inside
	return bool(class(self).IsHitFromInsideEnabled())
}

// SetHitFromInside sets the property returned by [IsHitFromInsideEnabled]. Returns the instance, so that property settings can be chained.
func (self Instance) SetHitFromInside(value bool) Instance { //gd:PhysicsRayQueryParameters2D.hit_from_inside
	class(self).SetHitFromInside(value)
	return self
}

func (self class) Create(from Vector2.XY, to Vector2.XY, collision_mask int64, exclude Array.Contains[RID.Any]) [1]gdclass.PhysicsRayQueryParameters2D { //gd:PhysicsRayQueryParameters2D.create
	var r_ret = noescape.CallStatic[gdextension.Object](methods.create, gdextension.SizeObject|(gdextension.SizeVector2<<4)|(gdextension.SizeVector2<<8)|(gdextension.SizeInt<<12)|(gdextension.SizeArray<<16), &struct {
		from           Vector2.XY
		to             Vector2.XY
		collision_mask int64
		exclude        gdextension.Array
	}{from, to, collision_mask, pointers.Get(gd.InternalArray(exclude))})
	var ret = [1]gdclass.PhysicsRayQueryParameters2D{gdclass.NewPhysicsRayQueryParameters2D(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) SetFrom(from Vector2.XY) { //gd:PhysicsRayQueryParameters2D.set_from
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_from, 0|(gdextension.SizeVector2<<4), &struct{ from Vector2.XY }{from})
}
func (self class) GetFrom() Vector2.XY { //gd:PhysicsRayQueryParameters2D.get_from
	var r_ret = jumponly.Call[Vector2.XY](gd.ObjectChecked(self.AsObject()), methods.get_from, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetTo(to Vector2.XY) { //gd:PhysicsRayQueryParameters2D.set_to
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_to, 0|(gdextension.SizeVector2<<4), &struct{ to Vector2.XY }{to})
}
func (self class) GetTo() Vector2.XY { //gd:PhysicsRayQueryParameters2D.get_to
	var r_ret = jumponly.Call[Vector2.XY](gd.ObjectChecked(self.AsObject()), methods.get_to, gdextension.SizeVector2, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetCollisionMask(collision_mask int64) { //gd:PhysicsRayQueryParameters2D.set_collision_mask
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_collision_mask, 0|(gdextension.SizeInt<<4), &struct{ collision_mask int64 }{collision_mask})
}
func (self class) GetCollisionMask() int64 { //gd:PhysicsRayQueryParameters2D.get_collision_mask
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_collision_mask, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetExclude(exclude Array.Contains[RID.Any]) { //gd:PhysicsRayQueryParameters2D.set_exclude
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_exclude, 0|(gdextension.SizeArray<<4), &struct{ exclude gdextension.Array }{pointers.Get(gd.InternalArray(exclude))})
}
func (self class) GetExclude() Array.Contains[RID.Any] { //gd:PhysicsRayQueryParameters2D.get_exclude
	var r_ret = noescape.Call[gdextension.Array](gd.ObjectChecked(self.AsObject()), methods.get_exclude, gdextension.SizeArray, &struct{}{})
	var ret = Array.Through(gd.ArrayProxy[RID.Any]{}, pointers.Pack(pointers.New[gd.Array](r_ret)))
	return ret
}
func (self class) SetCollideWithBodies(enable bool) { //gd:PhysicsRayQueryParameters2D.set_collide_with_bodies
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_collide_with_bodies, 0|(gdextension.SizeBool<<4), &struct{ enable bool }{enable})
}
func (self class) IsCollideWithBodiesEnabled() bool { //gd:PhysicsRayQueryParameters2D.is_collide_with_bodies_enabled
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_collide_with_bodies_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetCollideWithAreas(enable bool) { //gd:PhysicsRayQueryParameters2D.set_collide_with_areas
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_collide_with_areas, 0|(gdextension.SizeBool<<4), &struct{ enable bool }{enable})
}
func (self class) IsCollideWithAreasEnabled() bool { //gd:PhysicsRayQueryParameters2D.is_collide_with_areas_enabled
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_collide_with_areas_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetHitFromInside(enable bool) { //gd:PhysicsRayQueryParameters2D.set_hit_from_inside
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_hit_from_inside, 0|(gdextension.SizeBool<<4), &struct{ enable bool }{enable})
}
func (self class) IsHitFromInsideEnabled() bool { //gd:PhysicsRayQueryParameters2D.is_hit_from_inside_enabled
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_hit_from_inside_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsPhysicsRayQueryParameters2D() Advanced         { return Advanced(o) }
func (o Instance) AsPhysicsRayQueryParameters2D() Instance      { return o }
func (o *Extension[T]) AsPhysicsRayQueryParameters2D() Instance { return o.Super() }
func (o class) AsRefCounted() ie.RC                             { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC                     { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                          { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Advanced(self.AsRefCounted()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(RefCounted.Instance(self.AsRefCounted()), name)
	}
}
func init() {
	gdclass.Register("PhysicsRayQueryParameters2D", func(ptr gdreference.Object) any { return Instance{gdclass.NewPhysicsRayQueryParameters2D(ptr)} })
}
