// Code generated by the generate package DO NOT EDIT

/*
A resource to add to an [AnimationNodeBlendTree]. This animation node will execute a sub-animation and return once it finishes. Blend times for fading in and out can be customized, as well as filters.

After setting the request and changing the animation playback, the one-shot node automatically clears the request on the next process frame by setting its request value to [OneShotRequestNone].

	package main

	import (
		"graphics.gd/classdb/AnimationNodeOneShot"
		"graphics.gd/classdb/AnimationTree"
		"graphics.gd/variant/Object"
	)

	func ExampleAnimationNodeOneShot(tree AnimationTree.Instance) {
		// Play child animation connected to "shot" port.
		Object.Set(tree, "parameters/OneShot/request", AnimationNodeOneShot.OneShotRequestFire)

		// Abort child animation connected to "shot" port.
		Object.Set(tree, "parameters/OneShot/request", AnimationNodeOneShot.OneShotRequestAbort)

		// Abort child animation with fading out connected to "shot" port.
		Object.Set(tree, "parameters/OneShot/request", AnimationNodeOneShot.OneShotRequestFadeOut)

		// Get current state (read-only).
		Object.Get(tree, "parameters/OneShot/active")

		// Get current internal state (read-only).
		Object.Get(tree, "parameters/OneShot/internal_active")
	}

[AnimationNodeBlendTree]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeBlendTree
*/
package AnimationNodeOneShot

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/AnimationNode"
import "graphics.gd/classdb/AnimationNodeSync"
import "graphics.gd/classdb/Curve"
import "graphics.gd/classdb/Resource"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.AnimationNodeOneShot

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_fadein_time              gdextension.MethodForClass `hash:"373806689"`
	get_fadein_time              gdextension.MethodForClass `hash:"1740695150"`
	set_fadein_curve             gdextension.MethodForClass `hash:"270443179"`
	get_fadein_curve             gdextension.MethodForClass `hash:"2460114913"`
	set_fadeout_time             gdextension.MethodForClass `hash:"373806689"`
	get_fadeout_time             gdextension.MethodForClass `hash:"1740695150"`
	set_fadeout_curve            gdextension.MethodForClass `hash:"270443179"`
	get_fadeout_curve            gdextension.MethodForClass `hash:"2460114913"`
	set_break_loop_at_end        gdextension.MethodForClass `hash:"2586408642"`
	is_loop_broken_at_end        gdextension.MethodForClass `hash:"36873697"`
	set_abort_on_reset           gdextension.MethodForClass `hash:"2586408642"`
	is_aborted_on_reset          gdextension.MethodForClass `hash:"36873697"`
	set_autorestart              gdextension.MethodForClass `hash:"2586408642"`
	has_autorestart              gdextension.MethodForClass `hash:"36873697"`
	set_autorestart_delay        gdextension.MethodForClass `hash:"373806689"`
	get_autorestart_delay        gdextension.MethodForClass `hash:"1740695150"`
	set_autorestart_random_delay gdextension.MethodForClass `hash:"373806689"`
	get_autorestart_random_delay gdextension.MethodForClass `hash:"1740695150"`
	set_mix_mode                 gdextension.MethodForClass `hash:"1018899799"`
	get_mix_mode                 gdextension.MethodForClass `hash:"3076550526"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("AnimationNodeOneShot")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsAnimationNodeOneShot() Instance
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.AnimationNodeOneShot

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewAnimationNodeOneShot(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewAnimationNodeOneShot(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.AnimationNodeOneShot{gdclass.NewAnimationNodeOneShot(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetAnimationNodeOneShot(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.AnimationNodeOneShot{gdclass.NewAnimationNodeOneShot(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
The blend type.
*/
func (self Instance) MixMode() MixMode { //gd:AnimationNodeOneShot.mix_mode
	return MixMode(class(self).GetMixMode())
}

// SetMixMode sets the property returned by [GetMixMode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetMixMode(value MixMode) Instance { //gd:AnimationNodeOneShot.mix_mode
	class(self).SetMixMode(value)
	return self
}

/*
The fade-in duration. For example, setting this to 1.0 for a 5 second length animation will produce a cross-fade that starts at 0 second and ends at 1 second during the animation.

Note: [AnimationNodeOneShot] transitions the current state after the fading has finished.

[AnimationNodeOneShot]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeOneShot
*/
func (self Instance) FadeinTime() Float.X { //gd:AnimationNodeOneShot.fadein_time
	return Float.X(Float.X(class(self).GetFadeinTime()))
}

// SetFadeinTime sets the property returned by [GetFadeinTime]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFadeinTime(value Float.X) Instance { //gd:AnimationNodeOneShot.fadein_time
	class(self).SetFadeinTime(float64(value))
	return self
}

/*
Determines how cross-fading between animations is eased. If empty, the transition will be linear. Should be a unit [Curve].

[Curve]: https://pkg.go.dev/graphics.gd/classdb/Curve
*/
func (self Instance) FadeinCurve() Curve.Instance { //gd:AnimationNodeOneShot.fadein_curve
	return Curve.Instance(class(self).GetFadeinCurve())
}

// SetFadeinCurve sets the property returned by [GetFadeinCurve]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFadeinCurve(value Curve.Instance) Instance { //gd:AnimationNodeOneShot.fadein_curve
	class(self).SetFadeinCurve(value)
	return self
}

/*
The fade-out duration. For example, setting this to 1.0 for a 5 second length animation will produce a cross-fade that starts at 4 second and ends at 5 second during the animation.

Note: [AnimationNodeOneShot] transitions the current state after the fading has finished.

[AnimationNodeOneShot]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeOneShot
*/
func (self Instance) FadeoutTime() Float.X { //gd:AnimationNodeOneShot.fadeout_time
	return Float.X(Float.X(class(self).GetFadeoutTime()))
}

// SetFadeoutTime sets the property returned by [GetFadeoutTime]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFadeoutTime(value Float.X) Instance { //gd:AnimationNodeOneShot.fadeout_time
	class(self).SetFadeoutTime(float64(value))
	return self
}

/*
Determines how cross-fading between animations is eased. If empty, the transition will be linear. Should be a unit [Curve].

[Curve]: https://pkg.go.dev/graphics.gd/classdb/Curve
*/
func (self Instance) FadeoutCurve() Curve.Instance { //gd:AnimationNodeOneShot.fadeout_curve
	return Curve.Instance(class(self).GetFadeoutCurve())
}

// SetFadeoutCurve sets the property returned by [GetFadeoutCurve]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFadeoutCurve(value Curve.Instance) Instance { //gd:AnimationNodeOneShot.fadeout_curve
	class(self).SetFadeoutCurve(value)
	return self
}

/*
If true, breaks the loop at the end of the loop cycle for transition, even if the animation is looping.
*/
func (self Instance) BreakLoopAtEnd() bool { //gd:AnimationNodeOneShot.break_loop_at_end
	return bool(class(self).IsLoopBrokenAtEnd())
}

// SetBreakLoopAtEnd sets the property returned by [IsLoopBrokenAtEnd]. Returns the instance, so that property settings can be chained.
func (self Instance) SetBreakLoopAtEnd(value bool) Instance { //gd:AnimationNodeOneShot.break_loop_at_end
	class(self).SetBreakLoopAtEnd(value)
	return self
}

/*
If true, the sub-animation will abort if resumed with a reset after a prior interruption.
*/
func (self Instance) AbortOnReset() bool { //gd:AnimationNodeOneShot.abort_on_reset
	return bool(class(self).IsAbortedOnReset())
}

// SetAbortOnReset sets the property returned by [IsAbortedOnReset]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAbortOnReset(value bool) Instance { //gd:AnimationNodeOneShot.abort_on_reset
	class(self).SetAbortOnReset(value)
	return self
}

/*
If true, the sub-animation will restart automatically after finishing.

In other words, to start auto restarting, the animation must be played once with the [OneShotRequestFire] request. The [OneShotRequestAbort] request stops the auto restarting, but it does not disable the [Autorestart] itself. So, the [OneShotRequestFire] request will start auto restarting again.

[Autorestart]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeOneShot#Instance.Autorestart
*/
func (self Instance) Autorestart() bool { //gd:AnimationNodeOneShot.autorestart
	return bool(class(self).HasAutorestart())
}

// SetAutorestart sets the property returned by [HasAutorestart]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAutorestart(value bool) Instance { //gd:AnimationNodeOneShot.autorestart
	class(self).SetAutorestart(value)
	return self
}

/*
The delay after which the automatic restart is triggered, in seconds.
*/
func (self Instance) AutorestartDelay() Float.X { //gd:AnimationNodeOneShot.autorestart_delay
	return Float.X(Float.X(class(self).GetAutorestartDelay()))
}

// SetAutorestartDelay sets the property returned by [GetAutorestartDelay]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAutorestartDelay(value Float.X) Instance { //gd:AnimationNodeOneShot.autorestart_delay
	class(self).SetAutorestartDelay(float64(value))
	return self
}

/*
If [Autorestart] is true, a random additional delay (in seconds) between 0 and this value will be added to [AutorestartDelay].

[Autorestart]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeOneShot#Instance.Autorestart
[AutorestartDelay]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeOneShot#Instance.AutorestartDelay
*/
func (self Instance) AutorestartRandomDelay() Float.X { //gd:AnimationNodeOneShot.autorestart_random_delay
	return Float.X(Float.X(class(self).GetAutorestartRandomDelay()))
}

// SetAutorestartRandomDelay sets the property returned by [GetAutorestartRandomDelay]. Returns the instance, so that property settings can be chained.
func (self Instance) SetAutorestartRandomDelay(value Float.X) Instance { //gd:AnimationNodeOneShot.autorestart_random_delay
	class(self).SetAutorestartRandomDelay(float64(value))
	return self
}

func (self class) SetFadeinTime(time float64) { //gd:AnimationNodeOneShot.set_fadein_time
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_fadein_time, 0|(gdextension.SizeFloat<<4), &struct{ time float64 }{time})
}
func (self class) GetFadeinTime() float64 { //gd:AnimationNodeOneShot.get_fadein_time
	var r_ret = noescape.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_fadein_time, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFadeinCurve(curve [1]gdclass.Curve) { //gd:AnimationNodeOneShot.set_fadein_curve
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_fadein_curve, 0|(gdextension.SizeObject<<4), &struct{ curve gdextension.Object }{gdextension.Object(gdreference.GetObject(gdclass.GetCurve(curve[0])[0]))})
}
func (self class) GetFadeinCurve() [1]gdclass.Curve { //gd:AnimationNodeOneShot.get_fadein_curve
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_fadein_curve, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.Curve{gdclass.NewCurve(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) SetFadeoutTime(time float64) { //gd:AnimationNodeOneShot.set_fadeout_time
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_fadeout_time, 0|(gdextension.SizeFloat<<4), &struct{ time float64 }{time})
}
func (self class) GetFadeoutTime() float64 { //gd:AnimationNodeOneShot.get_fadeout_time
	var r_ret = noescape.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_fadeout_time, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFadeoutCurve(curve [1]gdclass.Curve) { //gd:AnimationNodeOneShot.set_fadeout_curve
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_fadeout_curve, 0|(gdextension.SizeObject<<4), &struct{ curve gdextension.Object }{gdextension.Object(gdreference.GetObject(gdclass.GetCurve(curve[0])[0]))})
}
func (self class) GetFadeoutCurve() [1]gdclass.Curve { //gd:AnimationNodeOneShot.get_fadeout_curve
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_fadeout_curve, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.Curve{gdclass.NewCurve(gd.PointerWithOwnershipTransferredToGo(r_ret))}
	return ret
}
func (self class) SetBreakLoopAtEnd(enable bool) { //gd:AnimationNodeOneShot.set_break_loop_at_end
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_break_loop_at_end, 0|(gdextension.SizeBool<<4), &struct{ enable bool }{enable})
}
func (self class) IsLoopBrokenAtEnd() bool { //gd:AnimationNodeOneShot.is_loop_broken_at_end
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_loop_broken_at_end, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAbortOnReset(enable bool) { //gd:AnimationNodeOneShot.set_abort_on_reset
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_abort_on_reset, 0|(gdextension.SizeBool<<4), &struct{ enable bool }{enable})
}
func (self class) IsAbortedOnReset() bool { //gd:AnimationNodeOneShot.is_aborted_on_reset
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_aborted_on_reset, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAutorestart(active bool) { //gd:AnimationNodeOneShot.set_autorestart
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_autorestart, 0|(gdextension.SizeBool<<4), &struct{ active bool }{active})
}
func (self class) HasAutorestart() bool { //gd:AnimationNodeOneShot.has_autorestart
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.has_autorestart, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAutorestartDelay(time float64) { //gd:AnimationNodeOneShot.set_autorestart_delay
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_autorestart_delay, 0|(gdextension.SizeFloat<<4), &struct{ time float64 }{time})
}
func (self class) GetAutorestartDelay() float64 { //gd:AnimationNodeOneShot.get_autorestart_delay
	var r_ret = noescape.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_autorestart_delay, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetAutorestartRandomDelay(time float64) { //gd:AnimationNodeOneShot.set_autorestart_random_delay
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_autorestart_random_delay, 0|(gdextension.SizeFloat<<4), &struct{ time float64 }{time})
}
func (self class) GetAutorestartRandomDelay() float64 { //gd:AnimationNodeOneShot.get_autorestart_random_delay
	var r_ret = noescape.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_autorestart_random_delay, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetMixMode(mode MixMode) { //gd:AnimationNodeOneShot.set_mix_mode
	jumponly.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_mix_mode, 0|(gdextension.SizeInt<<4), &struct{ mode MixMode }{mode})
}
func (self class) GetMixMode() MixMode { //gd:AnimationNodeOneShot.get_mix_mode
	var r_ret = jumponly.Call[MixMode](gd.ObjectChecked(self.AsObject()), methods.get_mix_mode, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsAnimationNodeOneShot() Advanced         { return Advanced(o) }
func (o Instance) AsAnimationNodeOneShot() Instance      { return o }
func (o *Extension[T]) AsAnimationNodeOneShot() Instance { return o.Super() }
func (o class) AsAnimationNodeSync() AnimationNodeSync.Advanced {
	return *(*AnimationNodeSync.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsAnimationNodeSync() AnimationNodeSync.Instance {
	return o.Super().AsAnimationNodeSync()
}
func (o Instance) AsAnimationNodeSync() AnimationNodeSync.Instance {
	return *(*AnimationNodeSync.Instance)(ie.As(&o))
}
func (o class) AsAnimationNode() AnimationNode.Advanced         { return *(*AnimationNode.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsAnimationNode() AnimationNode.Instance { return o.Super().AsAnimationNode() }
func (o Instance) AsAnimationNode() AnimationNode.Instance {
	return *(*AnimationNode.Instance)(ie.As(&o))
}
func (o class) AsResource() Resource.Advanced         { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance      { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC                   { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC           { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(AnimationNodeSync.Advanced(self.AsAnimationNodeSync()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(AnimationNodeSync.Instance(self.AsAnimationNodeSync()), name)
	}
}
func init() {
	gdclass.Register("AnimationNodeOneShot", func(ptr gdreference.Object) any { return Instance{gdclass.NewAnimationNodeOneShot(ptr)} })
}

type OneShotRequest int64 //gd:AnimationNodeOneShot.OneShotRequest

const (
	// The default state of the request. Nothing is done.
	OneShotRequestNone OneShotRequest = 0
	// The request to play the animation connected to "shot" port.
	OneShotRequestFire OneShotRequest = 1
	// The request to stop the animation connected to "shot" port.
	OneShotRequestAbort OneShotRequest = 2
	// The request to fade out the animation connected to "shot" port.
	OneShotRequestFadeOut OneShotRequest = 3
)

type MixMode int64 //gd:AnimationNodeOneShot.MixMode

const (
	// Blends two animations. See also [AnimationNodeBlend2].
	//
	// [AnimationNodeBlend2]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeBlend2
	MixModeBlend MixMode = 0
	// Blends two animations additively. See also [AnimationNodeAdd2].
	//
	// [AnimationNodeAdd2]: https://pkg.go.dev/graphics.gd/classdb/AnimationNodeAdd2
	MixModeAdd MixMode = 1
)
