// Code generated by graphics.gd. DO NOT EDIT.

package art

import (
	"graphics.gd/classdb/Resource"
	"graphics.gd/classdb/Texture2D"
)

var JPG = Resource.Library[struct {
	Burano     Texture2D.Instance `gd:"res://art/burano.jpg"`
	Forest     Texture2D.Instance `gd:"res://art/forest.jpg"`
	Mountains  Texture2D.Instance `gd:"res://art/mountains.jpg"`
	Platformer Texture2D.Instance `gd:"res://art/platformer.jpg"`
}]()

var PNG = Resource.Library[struct {
	Filmgrain Texture2D.Instance `gd:"res://art/filmgrain.png"`
	Vignette  Texture2D.Instance `gd:"res://art/vignette.png"`
	White     Texture2D.Instance `gd:"res://art/white.png"`
}]()
