// Code generated by the generate package DO NOT EDIT

/*
[Translation] maps a collection of strings to their individual translations, and also provides convenience methods for pluralization.

A [Translation] consists of messages. A message is identified by its context and untranslated string. Unlike [gettext], using an empty context string in Godot means not using any context.

[Translation]: https://pkg.go.dev/graphics.gd/classdb/Translation
[gettext]: https://www.gnu.org/software/gettext/
*/
package Translation

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Resource"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
See [Interface] for methods that can be overridden by T.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
See [Interface] for methods that can be overridden by T.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.Translation

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_locale                  gdextension.MethodForClass `hash:"83702148"`
	get_locale                  gdextension.MethodForClass `hash:"201670096"`
	add_message                 gdextension.MethodForClass `hash:"3898530326"`
	add_plural_message          gdextension.MethodForClass `hash:"2356982266"`
	get_message                 gdextension.MethodForClass `hash:"1829228469"`
	get_plural_message          gdextension.MethodForClass `hash:"229954002"`
	erase_message               gdextension.MethodForClass `hash:"3959009644"`
	get_message_list            gdextension.MethodForClass `hash:"1139954409"`
	get_translated_message_list gdextension.MethodForClass `hash:"1139954409"`
	get_message_count           gdextension.MethodForClass `hash:"3905245786"`
	set_plural_rules_override   gdextension.MethodForClass `hash:"83702148"`
	get_plural_rules_override   gdextension.MethodForClass `hash:"201670096"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("Translation")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// MoreArgs is a container for [Instance] functions with additional 'optional' arguments.
type MoreArgs [1]gdclass.Translation
type Expanded = MoreArgs

// MoreArgs enables certain functions to be called with additional 'optional' arguments.
func (self Instance) MoreArgs() MoreArgs { return MoreArgs(self) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsTranslation() Instance
}

type Interface interface {
	// Virtual method to override [GetPluralMessage].
	//
	// [GetPluralMessage]: https://pkg.go.dev/graphics.gd/classdb/Translation#Instance.GetPluralMessage
	GetPluralMessage(src_message string, src_plural_message string, n int, context string) string
	// Virtual method to override [GetMessage].
	//
	// [GetMessage]: https://pkg.go.dev/graphics.gd/classdb/Translation#Instance.GetMessage
	GetMessage(src_message string, context string) string
}

// Implementation implements [Interface] with empty methods.
type Implementation = implementation

type implementation struct{}

func (self implementation) GetPluralMessage(src_message string, src_plural_message string, n int, context string) (_ string) {
	return
}
func (self implementation) GetMessage(src_message string, context string) (_ string) { return }

/*
Virtual method to override [GetPluralMessage].

[GetPluralMessage]: https://pkg.go.dev/graphics.gd/classdb/Translation#Instance.GetPluralMessage
*/
func (Instance) _get_plural_message(impl func(ptr gdclass.Receiver, src_message string, src_plural_message string, n int, context string) string) (cb gd.ExtensionClassCallVirtualFunc) {
	return func(class any, p_args, p_back gdextension.Pointer) {
		var src_message = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 0)))))
		defer pointers.End(gd.InternalStringName(src_message))
		var src_plural_message = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 1)))))
		defer pointers.End(gd.InternalStringName(src_plural_message))
		var n = gd.UnsafeGet[int64](p_args, 2)
		var context = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 3)))))
		defer pointers.End(gd.InternalStringName(context))
		self := gdclass.Receiver(reflect.ValueOf(class).UnsafePointer())
		ret := impl(self, src_message.String(), src_plural_message.String(), int(n), context.String())
		ptr, ok := pointers.End(gd.InternalStringName(String.Name(String.New(ret))))

		if !ok {
			return
		}
		gd.UnsafeSet(p_back, ptr)
	}
}

/*
Virtual method to override [GetMessage].

[GetMessage]: https://pkg.go.dev/graphics.gd/classdb/Translation#Instance.GetMessage
*/
func (Instance) _get_message(impl func(ptr gdclass.Receiver, src_message string, context string) string) (cb gd.ExtensionClassCallVirtualFunc) {
	return func(class any, p_args, p_back gdextension.Pointer) {
		var src_message = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 0)))))
		defer pointers.End(gd.InternalStringName(src_message))
		var context = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 1)))))
		defer pointers.End(gd.InternalStringName(context))
		self := gdclass.Receiver(reflect.ValueOf(class).UnsafePointer())
		ret := impl(self, src_message.String(), context.String())
		ptr, ok := pointers.End(gd.InternalStringName(String.Name(String.New(ret))))

		if !ok {
			return
		}
		gd.UnsafeSet(p_back, ptr)
	}
}

/*
Adds a message if nonexistent, followed by its translation.

An additional context could be used to specify the translation context or differentiate polysemic words.
*/
func (self Instance) AddMessage(src_message string, xlated_message string) { //gd:Translation.add_message
	Advanced(self).AddMessage(String.Name(String.New(src_message)), String.Name(String.New(xlated_message)), String.Name(String.New("")))
}

/*
Adds a message if nonexistent, followed by its translation.

An additional context could be used to specify the translation context or differentiate polysemic words.
*/
func (self MoreArgs) AddMessage(src_message string, xlated_message string, context string) { //gd:Translation.add_message
	Advanced(self).AddMessage(String.Name(String.New(src_message)), String.Name(String.New(xlated_message)), String.Name(String.New(context)))
}

/*
Adds a message involving plural translation if nonexistent, followed by its translation.

An additional context could be used to specify the translation context or differentiate polysemic words.
*/
func (self Instance) AddPluralMessage(src_message string, xlated_messages []string) { //gd:Translation.add_plural_message
	Advanced(self).AddPluralMessage(String.Name(String.New(src_message)), Packed.MakeStrings(xlated_messages...), String.Name(String.New("")))
}

/*
Adds a message involving plural translation if nonexistent, followed by its translation.

An additional context could be used to specify the translation context or differentiate polysemic words.
*/
func (self MoreArgs) AddPluralMessage(src_message string, xlated_messages []string, context string) { //gd:Translation.add_plural_message
	Advanced(self).AddPluralMessage(String.Name(String.New(src_message)), Packed.MakeStrings(xlated_messages...), String.Name(String.New(context)))
}

/*
Returns a message's translation.
*/
func (self Instance) GetMessage(src_message string) string { //gd:Translation.get_message
	return string(Advanced(self).GetMessage(String.Name(String.New(src_message)), String.Name(String.New(""))).String())
}

/*
Returns a message's translation.
*/
func (self MoreArgs) GetMessage(src_message string, context string) string { //gd:Translation.get_message
	return string(Advanced(self).GetMessage(String.Name(String.New(src_message)), String.Name(String.New(context))).String())
}

/*
Returns a message's translation involving plurals.

The number 'n' is the number or quantity of the plural object. It will be used to guide the translation system to fetch the correct plural form for the selected language.

Note: Plurals are only supported in [gettext-based translations (PO)], not CSV.

[gettext-based translations (PO)]: https://docs.godotengine.org/tutorials/i18n/localization_using_gettext.html
*/
func (self Instance) GetPluralMessage(src_message string, src_plural_message string, n int) string { //gd:Translation.get_plural_message
	return string(Advanced(self).GetPluralMessage(String.Name(String.New(src_message)), String.Name(String.New(src_plural_message)), int64(n), String.Name(String.New(""))).String())
}

/*
Returns a message's translation involving plurals.

The number 'n' is the number or quantity of the plural object. It will be used to guide the translation system to fetch the correct plural form for the selected language.

Note: Plurals are only supported in [gettext-based translations (PO)], not CSV.

[gettext-based translations (PO)]: https://docs.godotengine.org/tutorials/i18n/localization_using_gettext.html
*/
func (self MoreArgs) GetPluralMessage(src_message string, src_plural_message string, n int, context string) string { //gd:Translation.get_plural_message
	return string(Advanced(self).GetPluralMessage(String.Name(String.New(src_message)), String.Name(String.New(src_plural_message)), int64(n), String.Name(String.New(context))).String())
}

/*
Erases a message.
*/
func (self Instance) EraseMessage(src_message string) { //gd:Translation.erase_message
	Advanced(self).EraseMessage(String.Name(String.New(src_message)), String.Name(String.New("")))
}

/*
Erases a message.
*/
func (self MoreArgs) EraseMessage(src_message string, context string) { //gd:Translation.erase_message
	Advanced(self).EraseMessage(String.Name(String.New(src_message)), String.Name(String.New(context)))
}

/*
Returns the keys of all messages, that is, the context and untranslated strings of each message.

Note: If a message does not use a context, the corresponding element is the untranslated string. Otherwise, the corresponding element is the context and untranslated string separated by the EOT character (U+0004). This is done for compatibility purposes.

	for _, key := range translation.GetMessageList() {
		var p = strings.Index(key, "\u0004")
		if p == -1 {
			var untranslated = key
			fmt.Printf("Message %s", untranslated)
		} else {
			var context = key[0:p]
			var untranslated = key[p+1:]
			fmt.Printf("Message %s with context %s", untranslated, context)
		}
	}
*/
func (self Instance) GetMessageList() []string { //gd:Translation.get_message_list
	return []string(Advanced(self).GetMessageList().Strings())
}

/*
Returns all the translated strings.
*/
func (self Instance) GetTranslatedMessageList() []string { //gd:Translation.get_translated_message_list
	return []string(Advanced(self).GetTranslatedMessageList().Strings())
}

/*
Returns the number of existing messages.
*/
func (self Instance) GetMessageCount() int { //gd:Translation.get_message_count
	return int(int(Advanced(self).GetMessageCount()))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.Translation

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewTranslation(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewTranslation(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.Translation{gdclass.NewTranslation(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetTranslation(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.Translation{gdclass.NewTranslation(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
The locale of the translation.
*/
func (self Instance) Locale() string { //gd:Translation.locale
	return string(class(self).GetLocale().String())
}

// SetLocale sets the property returned by [GetLocale]. Returns the instance, so that property settings can be chained.
func (self Instance) SetLocale(value string) Instance { //gd:Translation.locale
	class(self).SetLocale(String.New(value))
	return self
}

/*
The plural rules string to enforce. See [GNU gettext] for examples and more info.

If empty or invalid, default plural rules from [TranslationServer.GetPluralRules] are used. The English plural rules are used as a fallback.

[GNU gettext]: https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html
[TranslationServer.GetPluralRules]: https://pkg.go.dev/graphics.gd/classdb/TranslationServer#GetPluralRules
*/
func (self Instance) PluralRulesOverride() string { //gd:Translation.plural_rules_override
	return string(class(self).GetPluralRulesOverride().String())
}

// SetPluralRulesOverride sets the property returned by [GetPluralRulesOverride]. Returns the instance, so that property settings can be chained.
func (self Instance) SetPluralRulesOverride(value string) Instance { //gd:Translation.plural_rules_override
	class(self).SetPluralRulesOverride(String.New(value))
	return self
}
func (class) _get_plural_message(impl func(ptr gdclass.Receiver, src_message String.Name, src_plural_message String.Name, n int64, context String.Name) String.Name) (cb gd.ExtensionClassCallVirtualFunc) {
	return func(class any, p_args, p_back gdextension.Pointer) {
		var src_message = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 0)))))
		defer pointers.End(gd.InternalStringName(src_message))
		var src_plural_message = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 1)))))
		defer pointers.End(gd.InternalStringName(src_plural_message))
		var n = gd.UnsafeGet[int64](p_args, 2)
		var context = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 3)))))
		defer pointers.End(gd.InternalStringName(context))
		self := gdclass.Receiver(reflect.ValueOf(class).UnsafePointer())
		ret := impl(self, src_message, src_plural_message, n, context)
		ptr, ok := pointers.End(gd.InternalStringName(ret))

		if !ok {
			return
		}
		gd.UnsafeSet(p_back, ptr)
	}
}
func (class) _get_message(impl func(ptr gdclass.Receiver, src_message String.Name, context String.Name) String.Name) (cb gd.ExtensionClassCallVirtualFunc) {
	return func(class any, p_args, p_back gdextension.Pointer) {
		var src_message = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 0)))))
		defer pointers.End(gd.InternalStringName(src_message))
		var context = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](gd.UnsafeGet[gdextension.StringName](p_args, 1)))))
		defer pointers.End(gd.InternalStringName(context))
		self := gdclass.Receiver(reflect.ValueOf(class).UnsafePointer())
		ret := impl(self, src_message, context)
		ptr, ok := pointers.End(gd.InternalStringName(ret))

		if !ok {
			return
		}
		gd.UnsafeSet(p_back, ptr)
	}
}

func (self class) SetLocale(locale String.Readable) { //gd:Translation.set_locale
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_locale, 0|(gdextension.SizeString<<4), &struct{ locale gdextension.String }{pointers.Get(gd.InternalString(locale))})
}
func (self class) GetLocale() String.Readable { //gd:Translation.get_locale
	var r_ret = jumponly.Call[gdextension.String](gd.ObjectChecked(self.AsObject()), methods.get_locale, gdextension.SizeString, &struct{}{})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (self class) AddMessage(src_message String.Name, xlated_message String.Name, context String.Name) { //gd:Translation.add_message
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.add_message, 0|(gdextension.SizeStringName<<4)|(gdextension.SizeStringName<<8)|(gdextension.SizeStringName<<12), &struct {
		src_message    gdextension.StringName
		xlated_message gdextension.StringName
		context        gdextension.StringName
	}{pointers.Get(gd.InternalStringName(src_message)), pointers.Get(gd.InternalStringName(xlated_message)), pointers.Get(gd.InternalStringName(context))})
}
func (self class) AddPluralMessage(src_message String.Name, xlated_messages Packed.Strings, context String.Name) { //gd:Translation.add_plural_message
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.add_plural_message, 0|(gdextension.SizeStringName<<4)|(gdextension.SizePackedArray<<8)|(gdextension.SizeStringName<<12), &struct {
		src_message     gdextension.StringName
		xlated_messages gdextension.PackedArray[gdextension.String]
		context         gdextension.StringName
	}{pointers.Get(gd.InternalStringName(src_message)), pointers.Get(gd.InternalPackedStrings(xlated_messages)), pointers.Get(gd.InternalStringName(context))})
}
func (self class) GetMessage(src_message String.Name, context String.Name) String.Name { //gd:Translation.get_message
	var r_ret = noescape.Call[gdextension.StringName](gd.ObjectChecked(self.AsObject()), methods.get_message, gdextension.SizeStringName|(gdextension.SizeStringName<<4)|(gdextension.SizeStringName<<8), &struct {
		src_message gdextension.StringName
		context     gdextension.StringName
	}{pointers.Get(gd.InternalStringName(src_message)), pointers.Get(gd.InternalStringName(context))})
	var ret = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](r_ret))))
	return ret
}
func (self class) GetPluralMessage(src_message String.Name, src_plural_message String.Name, n int64, context String.Name) String.Name { //gd:Translation.get_plural_message
	var r_ret = noescape.Call[gdextension.StringName](gd.ObjectChecked(self.AsObject()), methods.get_plural_message, gdextension.SizeStringName|(gdextension.SizeStringName<<4)|(gdextension.SizeStringName<<8)|(gdextension.SizeInt<<12)|(gdextension.SizeStringName<<16), &struct {
		src_message        gdextension.StringName
		src_plural_message gdextension.StringName
		n                  int64
		context            gdextension.StringName
	}{pointers.Get(gd.InternalStringName(src_message)), pointers.Get(gd.InternalStringName(src_plural_message)), n, pointers.Get(gd.InternalStringName(context))})
	var ret = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](r_ret))))
	return ret
}
func (self class) EraseMessage(src_message String.Name, context String.Name) { //gd:Translation.erase_message
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.erase_message, 0|(gdextension.SizeStringName<<4)|(gdextension.SizeStringName<<8), &struct {
		src_message gdextension.StringName
		context     gdextension.StringName
	}{pointers.Get(gd.InternalStringName(src_message)), pointers.Get(gd.InternalStringName(context))})
}
func (self class) GetMessageList() Packed.Strings { //gd:Translation.get_message_list
	var r_ret = noescape.Call[gd.PackedPointers](gd.ObjectChecked(self.AsObject()), methods.get_message_list, gdextension.SizePackedArray, &struct{}{})
	var ret = Packed.Strings(Array.Through(gd.PackedStringArrayProxy{}, pointers.Pack(pointers.Let[gd.PackedStringArray](r_ret))))
	return ret
}
func (self class) GetTranslatedMessageList() Packed.Strings { //gd:Translation.get_translated_message_list
	var r_ret = noescape.Call[gd.PackedPointers](gd.ObjectChecked(self.AsObject()), methods.get_translated_message_list, gdextension.SizePackedArray, &struct{}{})
	var ret = Packed.Strings(Array.Through(gd.PackedStringArrayProxy{}, pointers.Pack(pointers.Let[gd.PackedStringArray](r_ret))))
	return ret
}
func (self class) GetMessageCount() int64 { //gd:Translation.get_message_count
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_message_count, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetPluralRulesOverride(rules String.Readable) { //gd:Translation.set_plural_rules_override
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_plural_rules_override, 0|(gdextension.SizeString<<4), &struct{ rules gdextension.String }{pointers.Get(gd.InternalString(rules))})
}
func (self class) GetPluralRulesOverride() String.Readable { //gd:Translation.get_plural_rules_override
	var r_ret = jumponly.Call[gdextension.String](gd.ObjectChecked(self.AsObject()), methods.get_plural_rules_override, gdextension.SizeString, &struct{}{})
	var ret = String.Via(gd.StringProxy{}, pointers.Pack(pointers.New[gd.String](r_ret)))
	return ret
}
func (o class) AsTranslation() Advanced               { return Advanced(o) }
func (o Instance) AsTranslation() Instance            { return o }
func (o *Extension[T]) AsTranslation() Instance       { return o.Super() }
func (o class) AsResource() Resource.Advanced         { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance      { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC                   { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC           { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	case "_get_plural_message":
		return reflect.ValueOf(self._get_plural_message)
	case "_get_message":
		return reflect.ValueOf(self._get_message)
	default:
		return gd.VirtualByName(Resource.Advanced(self.AsResource()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	case "_get_plural_message":
		return reflect.ValueOf(self._get_plural_message)
	case "_get_message":
		return reflect.ValueOf(self._get_message)
	default:
		return gd.VirtualByName(Resource.Instance(self.AsResource()), name)
	}
}
func init() {
	gdclass.Register("Translation", func(ptr gdreference.Object) any { return Instance{gdclass.NewTranslation(ptr)} })
}
