// Code generated by the generate package DO NOT EDIT

/*
This class contains a dictionary that uses a list of bone names in [SkeletonProfile] as key names.

By assigning the actual [Skeleton3D] bone name as the key value, it maps the [Skeleton3D] to the [SkeletonProfile].

[Skeleton3D]: https://pkg.go.dev/graphics.gd/classdb/Skeleton3D
[SkeletonProfile]: https://pkg.go.dev/graphics.gd/classdb/SkeletonProfile
*/
package BoneMap

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Resource"
import "graphics.gd/classdb/SkeletonProfile"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.BoneMap

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	get_profile            gdextension.MethodForClass `hash:"4291782652"`
	set_profile            gdextension.MethodForClass `hash:"3870374136"`
	get_skeleton_bone_name gdextension.MethodForClass `hash:"1965194235"`
	set_skeleton_bone_name gdextension.MethodForClass `hash:"3740211285"`
	find_profile_bone_name gdextension.MethodForClass `hash:"1965194235"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("BoneMap")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsBoneMap() Instance
}

/*
Returns a skeleton bone name is mapped to 'profile_bone_name'.

In the retargeting process, the returned bone name is the bone name of the source skeleton.
*/
func (self Instance) GetSkeletonBoneName(profile_bone_name string) string { //gd:BoneMap.get_skeleton_bone_name
	return string(Advanced(self).GetSkeletonBoneName(String.Name(String.New(profile_bone_name))).String())
}

/*
Maps a skeleton bone name to 'profile_bone_name'.

In the retargeting process, the setting bone name is the bone name of the source skeleton.

Returns 'self' to enable method chaining.
*/
func (self Instance) SetSkeletonBoneName(profile_bone_name string, skeleton_bone_name string) Instance { //gd:BoneMap.set_skeleton_bone_name
	Advanced(self).SetSkeletonBoneName(String.Name(String.New(profile_bone_name)), String.Name(String.New(skeleton_bone_name)))
	return self
}

/*
Returns a profile bone name having 'skeleton_bone_name'. If not found, an empty string will be returned.

In the retargeting process, the returned bone name is the bone name of the target skeleton.
*/
func (self Instance) FindProfileBoneName(skeleton_bone_name string) string { //gd:BoneMap.find_profile_bone_name
	return string(Advanced(self).FindProfileBoneName(String.Name(String.New(skeleton_bone_name))).String())
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.BoneMap

func (o class) AsObject() [1]gd.Object { return *(*[1]gd.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = gdclass.NewBoneMap(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = gdclass.NewBoneMap(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gd.Object      { return *(*[1]gd.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gd.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.BoneMap{gdclass.NewBoneMap(pointers.Add[gd.Object]([3]uint64{}))})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := pointers.End(New().AsObject()[0])
				pointers.Set(gdclass.GetBoneMap(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := pointers.Get[gd.Object](placeholder.AsObject()[0]); raw[0] != 0 && raw[1] == 0 {
						gdextension.Host.Objects.Unsafe.Free(gdextension.Object(raw[0]))
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.BoneMap{gdclass.NewBoneMap(pointers.New[gd.Object]([3]uint64{uint64(gdextension.Host.Objects.Make(sname))}))})
	casted.AsRefCounted()[0].InitRef()
	casted.AsObject()[0].Notification(0, false)
	return casted
}

/*
A [SkeletonProfile] of the mapping target. Key names in the [BoneMap] are synchronized with it.

[BoneMap]: https://pkg.go.dev/graphics.gd/classdb/BoneMap
[SkeletonProfile]: https://pkg.go.dev/graphics.gd/classdb/SkeletonProfile
*/
func (self Instance) Profile() SkeletonProfile.Instance { //gd:BoneMap.profile
	return SkeletonProfile.Instance(class(self).GetProfile())
}

// SetProfile sets the property returned by [GetProfile]. Returns the instance, so that property settings can be chained.
func (self Instance) SetProfile(value SkeletonProfile.Instance) Instance { //gd:BoneMap.profile
	class(self).SetProfile(value)
	return self
}

func (self class) GetProfile() [1]gdclass.SkeletonProfile { //gd:BoneMap.get_profile
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_profile, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.SkeletonProfile{gdclass.NewSkeletonProfile(gd.PointerWithOwnershipTransferredToGo[gd.Object](r_ret))}
	return ret
}
func (self class) SetProfile(profile [1]gdclass.SkeletonProfile) { //gd:BoneMap.set_profile
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_profile, 0|(gdextension.SizeObject<<4), &struct{ profile gdextension.Object }{gdextension.Object(gd.ObjectChecked(gdclass.GetSkeletonProfile(profile[0])))})
}
func (self class) GetSkeletonBoneName(profile_bone_name String.Name) String.Name { //gd:BoneMap.get_skeleton_bone_name
	var r_ret = noescape.Call[gdextension.StringName](gd.ObjectChecked(self.AsObject()), methods.get_skeleton_bone_name, gdextension.SizeStringName|(gdextension.SizeStringName<<4), &struct{ profile_bone_name gdextension.StringName }{pointers.Get(gd.InternalStringName(profile_bone_name))})
	var ret = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](r_ret))))
	return ret
}
func (self class) SetSkeletonBoneName(profile_bone_name String.Name, skeleton_bone_name String.Name) { //gd:BoneMap.set_skeleton_bone_name
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_skeleton_bone_name, 0|(gdextension.SizeStringName<<4)|(gdextension.SizeStringName<<8), &struct {
		profile_bone_name  gdextension.StringName
		skeleton_bone_name gdextension.StringName
	}{pointers.Get(gd.InternalStringName(profile_bone_name)), pointers.Get(gd.InternalStringName(skeleton_bone_name))})
}
func (self class) FindProfileBoneName(skeleton_bone_name String.Name) String.Name { //gd:BoneMap.find_profile_bone_name
	var r_ret = noescape.Call[gdextension.StringName](gd.ObjectChecked(self.AsObject()), methods.find_profile_bone_name, gdextension.SizeStringName|(gdextension.SizeStringName<<4), &struct{ skeleton_bone_name gdextension.StringName }{pointers.Get(gd.InternalStringName(skeleton_bone_name))})
	var ret = String.Name(String.Via(gd.StringNameProxy{}, pointers.Pack(pointers.New[gd.StringName](r_ret))))
	return ret
}

/*
This signal is emitted when change the key value in the [BoneMap]. This is used to validate mapping and to update [BoneMap] editor.

[BoneMap]: https://pkg.go.dev/graphics.gd/classdb/BoneMap
*/
func (self Instance) OnBoneMapUpdated(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	self.AsObject()[0].Connect(gd.NewStringName("bone_map_updated"), gd.NewCallable(cb), int64(flags_together))
	return self
}

func (self class) BoneMapUpdated() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`bone_map_updated`))))
}

/*
This signal is emitted when change the value in profile or change the reference of profile. This is used to update key names in the [BoneMap] and to redraw the [BoneMap] editor.

[BoneMap]: https://pkg.go.dev/graphics.gd/classdb/BoneMap
*/
func (self Instance) OnProfileUpdated(cb func(), flags ...Signal.Flags) Instance {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	self.AsObject()[0].Connect(gd.NewStringName("profile_updated"), gd.NewCallable(cb), int64(flags_together))
	return self
}

func (self class) ProfileUpdated() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`profile_updated`))))
}

func (o class) AsBoneMap() Advanced                   { return Advanced(o) }
func (o Instance) AsBoneMap() Instance                { return o }
func (o *Extension[T]) AsBoneMap() Instance           { return o.Super() }
func (o class) AsResource() Resource.Advanced         { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance      { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC                   { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC           { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Resource.Advanced(self.AsResource()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Resource.Instance(self.AsResource()), name)
	}
}
func init() {
	gdclass.Register("BoneMap", func(ptr gd.Object) any { return Instance{gdclass.NewBoneMap(ptr)} })
}
