// Code generated by graphics.gd. DO NOT EDIT.

package controllericons

import (
	"graphics.gd/classdb/Resource"
	"graphics.gd/classdb/Texture2D"
)

var PNG = Resource.Library[struct {
	ButtonStart   Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/buttonStart.png"`
	DownButton    Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/down_button.png"`
	Esc           Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/esc.png"`
	Gamepad       Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/gamepad.png"`
	JoystickLSide Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/joystickL_side.png"`
	JoystickRSide Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/joystickR_side.png"`
	Keyboard      Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/keyboard.png"`
	L2Button      Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/l2_button.png"`
	LeftButton    Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/left_button.png"`
	Minus         Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/minus.png"`
	Mouse         Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/mouse.png"`
	MouseLeft     Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/mouseLeft.png"`
	MouseRight    Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/mouseRight.png"`
	R2Button      Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/r2_button.png"`
	RightButton   Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/right_button.png"`
	Spacebar      Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/spacebar.png"`
	Spacebar2     Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/spacebar2.png"`
	Tab           Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/tab.png"`
	UpButton      Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/up_button.png"`
	Wasd          Texture2D.Instance `gd:"res://DemoPage/ControllerIcons/wasd.png"`
}]()
