// Code generated by the generate package DO NOT EDIT

/*
[ArrayOccluder3D] stores an arbitrary 3D polygon shape that can be used by the engine's occlusion culling system. This is analogous to [ArrayMesh], but for occluders.

See [OccluderInstance3D]'s documentation for instructions on setting up occlusion culling.

[ArrayMesh]: https://pkg.go.dev/graphics.gd/classdb/ArrayMesh
[ArrayOccluder3D]: https://pkg.go.dev/graphics.gd/classdb/ArrayOccluder3D
[OccluderInstance3D]: https://pkg.go.dev/graphics.gd/classdb/OccluderInstance3D
*/
package ArrayOccluder3D

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import gdunsafe "graphics.gd"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Occluder3D"
import "graphics.gd/classdb/Resource"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"
import "graphics.gd/variant/Vector3"

var _ Object.ID

type _ gdclass.Node

var _ gd.String
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ gdunsafe.Object
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.ArrayOccluder3D

var otype gdunsafe.ClassTag
var sname gdunsafe.StringName
var methods struct {
	set_arrays   gdextension.MethodForClass `hash:"3233972621"`
	set_vertices gdextension.MethodForClass `hash:"334873810"`
	set_indices  gdextension.MethodForClass `hash:"3614634198"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdunsafe.UTF8.Intern("ArrayOccluder3D")
		otype = gdunsafe.Class(sname).Tag()
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		gdunsafe.Free(sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsArrayOccluder3D() Instance
}

/*
Sets [Indices] and [Vertices], while updating the final occluder only once after both values are set.

Returns 'self' to enable method chaining.

[Indices]: https://pkg.go.dev/graphics.gd/classdb/ArrayOccluder3D#Instance.Indices
[Vertices]: https://pkg.go.dev/graphics.gd/classdb/ArrayOccluder3D#Instance.Vertices
*/
func (self Instance) SetArrays(vertices []Vector3.XYZ, indices []int32) Instance { //gd:ArrayOccluder3D.set_arrays
	Advanced(self).SetArrays(Packed.New(vertices...), Packed.New(indices...))
	return self
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.ArrayOccluder3D

func (o class) AsObject() [1]gdreference.Object { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewArrayOccluder3D(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gdreference.Object) bool {
	if gdunsafe.Object(gdreference.GetObject(obj[0])).Cast(otype) != 0 {
		self[0] = gdclass.NewArrayOccluder3D(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gdreference.Object      { return *(*[1]gdreference.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gdreference.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.ArrayOccluder3D{gdclass.NewArrayOccluder3D(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetArrayOccluder3D(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdunsafe.Object(raw).Free()
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.ArrayOccluder3D{gdclass.NewArrayOccluder3D(gdreference.OwnObject(gdextension.Object(gdunsafe.New(gdunsafe.Class(sname))), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
The occluder's vertex positions in local 3D coordinates.

Note: The occluder is always updated after setting this value. If creating occluders procedurally, consider using [SetArrays] instead to avoid updating the occluder twice when it's created.

[SetArrays]: https://pkg.go.dev/graphics.gd/classdb/ArrayOccluder3D#Instance.SetArrays
Returns the instance, so that property settings can be chained.
*/
func (self Instance) SetVertices(value []Vector3.XYZ) Instance { //gd:ArrayOccluder3D.vertices
	class(self).SetVertices(Packed.New(value...))
	return self
}

/*
The occluder's index position. Indices determine which points from the [Vertices] array should be drawn, and in which order.

Note: The occluder is always updated after setting this value. If creating occluders procedurally, consider using [SetArrays] instead to avoid updating the occluder twice when it's created.

[SetArrays]: https://pkg.go.dev/graphics.gd/classdb/ArrayOccluder3D#Instance.SetArrays
[Vertices]: https://pkg.go.dev/graphics.gd/classdb/ArrayOccluder3D#Instance.Vertices
Returns the instance, so that property settings can be chained.
*/
func (self Instance) SetIndices(value []int32) Instance { //gd:ArrayOccluder3D.indices
	class(self).SetIndices(Packed.New(value...))
	return self
}

func (self class) SetArrays(vertices Packed.Array[Vector3.XYZ], indices Packed.Array[int32]) { //gd:ArrayOccluder3D.set_arrays
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_arrays, 0|(gdextension.SizePackedArray<<4)|(gdextension.SizePackedArray<<8), &struct {
		vertices gdextension.PackedArray[Vector3.XYZ]
		indices  gdextension.PackedArray[int32]
	}{pointers.Get(gd.InternalPacked[gd.PackedVector3Array, Vector3.XYZ](vertices)), pointers.Get(gd.InternalPacked[gd.PackedInt32Array, int32](indices))})
}
func (self class) SetVertices(vertices Packed.Array[Vector3.XYZ]) { //gd:ArrayOccluder3D.set_vertices
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_vertices, 0|(gdextension.SizePackedArray<<4), &struct {
		vertices gdextension.PackedArray[Vector3.XYZ]
	}{pointers.Get(gd.InternalPacked[gd.PackedVector3Array, Vector3.XYZ](vertices))})
}
func (self class) SetIndices(indices Packed.Array[int32]) { //gd:ArrayOccluder3D.set_indices
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_indices, 0|(gdextension.SizePackedArray<<4), &struct {
		indices gdextension.PackedArray[int32]
	}{pointers.Get(gd.InternalPacked[gd.PackedInt32Array, int32](indices))})
}
func (o class) AsArrayOccluder3D() Advanced               { return Advanced(o) }
func (o Instance) AsArrayOccluder3D() Instance            { return o }
func (o *Extension[T]) AsArrayOccluder3D() Instance       { return o.Super() }
func (o class) AsOccluder3D() Occluder3D.Advanced         { return *(*Occluder3D.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsOccluder3D() Occluder3D.Instance { return o.Super().AsOccluder3D() }
func (o Instance) AsOccluder3D() Occluder3D.Instance      { return *(*Occluder3D.Instance)(ie.As(&o)) }
func (o class) AsResource() Resource.Advanced             { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance     { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance          { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC                       { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC               { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                    { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Occluder3D.Advanced(self.AsOccluder3D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Occluder3D.Instance(self.AsOccluder3D()), name)
	}
}
func init() {
	gdclass.Register("ArrayOccluder3D", func(ptr gdreference.Object) any { return Instance{gdclass.NewArrayOccluder3D(ptr)} })
}
