// Code generated by the generate package DO NOT EDIT

/*
This [SkeletonModification2D] uses an algorithm typically called TwoBoneIK. This algorithm works by leveraging the law of cosines and the lengths of the bones to figure out what rotation the bones currently have, and what rotation they need to make a complete triangle, where the first bone, the second bone, and the target form the three vertices of the triangle. Because the algorithm works by making a triangle, it can only operate on two bones.

TwoBoneIK is great for arms, legs, and really any joints that can be represented by just two bones that bend to reach a target. This solver is more lightweight than [SkeletonModification2DFABRIK], but gives similar, natural looking results.

[SkeletonModification2D]: https://pkg.go.dev/graphics.gd/classdb/SkeletonModification2D
[SkeletonModification2DFABRIK]: https://pkg.go.dev/graphics.gd/classdb/SkeletonModification2DFABRIK
*/
package SkeletonModification2DTwoBoneIK

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/gdreference"
import "graphics.gd/internal/noescape"
import "graphics.gd/internal/jumponly"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/internal/ie"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/Resource"
import "graphics.gd/classdb/SkeletonModification2D"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ = jumponly.PtrcallFn
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create a Go extension of this class.

T must be a type that is embedding this [Extension] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

/*
Singleton can be embedded in a new struct to create a Go singleton extension of the class.

It will become available as a global inside scripts and any any other Go Extension types will
have any *T typed fields filled in to point at this singleton once they have been instantiated.

T must be a type that is embedding this [Singleton] as the first field.
It is unsafe and invalid to use this type directly, or embedded in any other way.
*/
type Singleton[T gdclass.Interface] = Extension[T]

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.SkeletonModification2DTwoBoneIK

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_target_node             gdextension.MethodForClass `hash:"1348162250"`
	get_target_node             gdextension.MethodForClass `hash:"4075236667"`
	set_target_minimum_distance gdextension.MethodForClass `hash:"373806689"`
	get_target_minimum_distance gdextension.MethodForClass `hash:"1740695150"`
	set_target_maximum_distance gdextension.MethodForClass `hash:"373806689"`
	get_target_maximum_distance gdextension.MethodForClass `hash:"1740695150"`
	set_flip_bend_direction     gdextension.MethodForClass `hash:"2586408642"`
	get_flip_bend_direction     gdextension.MethodForClass `hash:"36873697"`
	set_joint_one_bone2d_node   gdextension.MethodForClass `hash:"1348162250"`
	get_joint_one_bone2d_node   gdextension.MethodForClass `hash:"4075236667"`
	set_joint_one_bone_idx      gdextension.MethodForClass `hash:"1286410249"`
	get_joint_one_bone_idx      gdextension.MethodForClass `hash:"3905245786"`
	set_joint_two_bone2d_node   gdextension.MethodForClass `hash:"1348162250"`
	get_joint_two_bone2d_node   gdextension.MethodForClass `hash:"4075236667"`
	set_joint_two_bone_idx      gdextension.MethodForClass `hash:"1286410249"`
	get_joint_two_bone_idx      gdextension.MethodForClass `hash:"3905245786"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("SkeletonModification2DTwoBoneIK")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsSkeletonModification2DTwoBoneIK() Instance
}

/*
Sets the [Bone2D] node that is being used as the first bone in the TwoBoneIK modification.

Returns 'self' to enable method chaining.

[Bone2D]: https://pkg.go.dev/graphics.gd/classdb/Bone2D
*/
func (self Instance) SetJointOneBone2dNode(bone2d_node string) Instance { //gd:SkeletonModification2DTwoBoneIK.set_joint_one_bone2d_node
	Advanced(self).SetJointOneBone2dNode(Path.ToNode(String.New(bone2d_node)))
	return self
}

/*
Returns the [Bone2D] node that is being used as the first bone in the TwoBoneIK modification.

[Bone2D]: https://pkg.go.dev/graphics.gd/classdb/Bone2D
*/
func (self Instance) GetJointOneBone2dNode() string { //gd:SkeletonModification2DTwoBoneIK.get_joint_one_bone2d_node
	return string(Advanced(self).GetJointOneBone2dNode().String())
}

/*
Sets the index of the [Bone2D] node that is being used as the first bone in the TwoBoneIK modification.

Returns 'self' to enable method chaining.

[Bone2D]: https://pkg.go.dev/graphics.gd/classdb/Bone2D
*/
func (self Instance) SetJointOneBoneIdx(bone_idx int) Instance { //gd:SkeletonModification2DTwoBoneIK.set_joint_one_bone_idx
	Advanced(self).SetJointOneBoneIdx(int64(bone_idx))
	return self
}

/*
Returns the index of the [Bone2D] node that is being used as the first bone in the TwoBoneIK modification.

[Bone2D]: https://pkg.go.dev/graphics.gd/classdb/Bone2D
*/
func (self Instance) GetJointOneBoneIdx() int { //gd:SkeletonModification2DTwoBoneIK.get_joint_one_bone_idx
	return int(int(Advanced(self).GetJointOneBoneIdx()))
}

/*
Sets the [Bone2D] node that is being used as the second bone in the TwoBoneIK modification.

Returns 'self' to enable method chaining.

[Bone2D]: https://pkg.go.dev/graphics.gd/classdb/Bone2D
*/
func (self Instance) SetJointTwoBone2dNode(bone2d_node string) Instance { //gd:SkeletonModification2DTwoBoneIK.set_joint_two_bone2d_node
	Advanced(self).SetJointTwoBone2dNode(Path.ToNode(String.New(bone2d_node)))
	return self
}

/*
Returns the [Bone2D] node that is being used as the second bone in the TwoBoneIK modification.

[Bone2D]: https://pkg.go.dev/graphics.gd/classdb/Bone2D
*/
func (self Instance) GetJointTwoBone2dNode() string { //gd:SkeletonModification2DTwoBoneIK.get_joint_two_bone2d_node
	return string(Advanced(self).GetJointTwoBone2dNode().String())
}

/*
Sets the index of the [Bone2D] node that is being used as the second bone in the TwoBoneIK modification.

Returns 'self' to enable method chaining.

[Bone2D]: https://pkg.go.dev/graphics.gd/classdb/Bone2D
*/
func (self Instance) SetJointTwoBoneIdx(bone_idx int) Instance { //gd:SkeletonModification2DTwoBoneIK.set_joint_two_bone_idx
	Advanced(self).SetJointTwoBoneIdx(int64(bone_idx))
	return self
}

/*
Returns the index of the [Bone2D] node that is being used as the second bone in the TwoBoneIK modification.

[Bone2D]: https://pkg.go.dev/graphics.gd/classdb/Bone2D
*/
func (self Instance) GetJointTwoBoneIdx() int { //gd:SkeletonModification2DTwoBoneIK.get_joint_two_bone_idx
	return int(int(Advanced(self).GetJointTwoBoneIdx()))
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.SkeletonModification2DTwoBoneIK

func (o class) AsObject() [1]gd.Object { return *(*[1]gd.Object)(ie.As(&o)) }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewSkeletonModification2DTwoBoneIK(obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdreference.GetObject(obj[0]), otype) != 0 {
		self[0] = gdclass.NewSkeletonModification2DTwoBoneIK(obj[0])
		return true
	}
	return false
}
func (o Instance) AsObject() [1]gd.Object      { return *(*[1]gd.Object)(ie.As(&o)) }
func (o *Extension[T]) AsObject() [1]gd.Object { return o.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.SkeletonModification2DTwoBoneIK{gdclass.NewSkeletonModification2DTwoBoneIK(gdreference.NewObject())})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := gdreference.EndObject(New().AsObject()[0])
				gdreference.SetObject(gdclass.GetSkeletonModification2DTwoBoneIK(placeholder[0])[0], raw)
				gd.RegisterCleanup(func() {
					if raw := gdreference.GetObject(placeholder.AsObject()[0]); raw != 0 {
						gdextension.Host.Objects.Unsafe.Free(raw)
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.SkeletonModification2DTwoBoneIK{gdclass.NewSkeletonModification2DTwoBoneIK(gdreference.OwnObject(gdextension.Host.Objects.Make(sname), gd.Free))})
	casted.AsRefCounted()[0].InitRef()
	gd.ObjectNotification(casted.AsObject()[0], 0, false)
	return casted
}

/*
The NodePath to the node that is the target for the TwoBoneIK modification. This node is what the modification will use when bending the [Bone2D] nodes.

[Bone2D]: https://pkg.go.dev/graphics.gd/classdb/Bone2D
*/
func (self Instance) TargetNodepath() string { //gd:SkeletonModification2DTwoBoneIK.target_nodepath
	return string(class(self).GetTargetNode().String())
}

// SetTargetNodepath sets the property returned by [GetTargetNode]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTargetNodepath(value string) Instance { //gd:SkeletonModification2DTwoBoneIK.target_nodepath
	class(self).SetTargetNode(Path.ToNode(String.New(value)))
	return self
}

/*
The minimum distance the target can be at. If the target is closer than this distance, the modification will solve as if it's at this minimum distance. When set to 0, the modification will solve without distance constraints.
*/
func (self Instance) TargetMinimumDistance() Float.X { //gd:SkeletonModification2DTwoBoneIK.target_minimum_distance
	return Float.X(Float.X(class(self).GetTargetMinimumDistance()))
}

// SetTargetMinimumDistance sets the property returned by [GetTargetMinimumDistance]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTargetMinimumDistance(value Float.X) Instance { //gd:SkeletonModification2DTwoBoneIK.target_minimum_distance
	class(self).SetTargetMinimumDistance(float64(value))
	return self
}

/*
The maximum distance the target can be at. If the target is farther than this distance, the modification will solve as if it's at this maximum distance. When set to 0, the modification will solve without distance constraints.
*/
func (self Instance) TargetMaximumDistance() Float.X { //gd:SkeletonModification2DTwoBoneIK.target_maximum_distance
	return Float.X(Float.X(class(self).GetTargetMaximumDistance()))
}

// SetTargetMaximumDistance sets the property returned by [GetTargetMaximumDistance]. Returns the instance, so that property settings can be chained.
func (self Instance) SetTargetMaximumDistance(value Float.X) Instance { //gd:SkeletonModification2DTwoBoneIK.target_maximum_distance
	class(self).SetTargetMaximumDistance(float64(value))
	return self
}

/*
If true, the bones in the modification will bend outward as opposed to inwards when contracting. If false, the bones will bend inwards when contracting.
*/
func (self Instance) FlipBendDirection() bool { //gd:SkeletonModification2DTwoBoneIK.flip_bend_direction
	return bool(class(self).GetFlipBendDirection())
}

// SetFlipBendDirection sets the property returned by [GetFlipBendDirection]. Returns the instance, so that property settings can be chained.
func (self Instance) SetFlipBendDirection(value bool) Instance { //gd:SkeletonModification2DTwoBoneIK.flip_bend_direction
	class(self).SetFlipBendDirection(value)
	return self
}

func (self class) SetTargetNode(target_nodepath Path.ToNode) { //gd:SkeletonModification2DTwoBoneIK.set_target_node
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_target_node, 0|(gdextension.SizeNodePath<<4), &struct{ target_nodepath gdextension.NodePath }{pointers.Get(gd.InternalNodePath(target_nodepath))})
}
func (self class) GetTargetNode() Path.ToNode { //gd:SkeletonModification2DTwoBoneIK.get_target_node
	var r_ret = jumponly.Call[gdextension.NodePath](gd.ObjectChecked(self.AsObject()), methods.get_target_node, gdextension.SizeNodePath, &struct{}{})
	var ret = Path.ToNode(String.Via(gd.NodePathProxy{}, pointers.Pack(pointers.New[gd.NodePath](r_ret))))
	return ret
}
func (self class) SetTargetMinimumDistance(minimum_distance float64) { //gd:SkeletonModification2DTwoBoneIK.set_target_minimum_distance
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_target_minimum_distance, 0|(gdextension.SizeFloat<<4), &struct{ minimum_distance float64 }{minimum_distance})
}
func (self class) GetTargetMinimumDistance() float64 { //gd:SkeletonModification2DTwoBoneIK.get_target_minimum_distance
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_target_minimum_distance, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetTargetMaximumDistance(maximum_distance float64) { //gd:SkeletonModification2DTwoBoneIK.set_target_maximum_distance
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_target_maximum_distance, 0|(gdextension.SizeFloat<<4), &struct{ maximum_distance float64 }{maximum_distance})
}
func (self class) GetTargetMaximumDistance() float64 { //gd:SkeletonModification2DTwoBoneIK.get_target_maximum_distance
	var r_ret = jumponly.Call[float64](gd.ObjectChecked(self.AsObject()), methods.get_target_maximum_distance, gdextension.SizeFloat, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetFlipBendDirection(flip_direction bool) { //gd:SkeletonModification2DTwoBoneIK.set_flip_bend_direction
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_flip_bend_direction, 0|(gdextension.SizeBool<<4), &struct{ flip_direction bool }{flip_direction})
}
func (self class) GetFlipBendDirection() bool { //gd:SkeletonModification2DTwoBoneIK.get_flip_bend_direction
	var r_ret = jumponly.Call[bool](gd.ObjectChecked(self.AsObject()), methods.get_flip_bend_direction, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetJointOneBone2dNode(bone2d_node Path.ToNode) { //gd:SkeletonModification2DTwoBoneIK.set_joint_one_bone2d_node
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_joint_one_bone2d_node, 0|(gdextension.SizeNodePath<<4), &struct{ bone2d_node gdextension.NodePath }{pointers.Get(gd.InternalNodePath(bone2d_node))})
}
func (self class) GetJointOneBone2dNode() Path.ToNode { //gd:SkeletonModification2DTwoBoneIK.get_joint_one_bone2d_node
	var r_ret = jumponly.Call[gdextension.NodePath](gd.ObjectChecked(self.AsObject()), methods.get_joint_one_bone2d_node, gdextension.SizeNodePath, &struct{}{})
	var ret = Path.ToNode(String.Via(gd.NodePathProxy{}, pointers.Pack(pointers.New[gd.NodePath](r_ret))))
	return ret
}
func (self class) SetJointOneBoneIdx(bone_idx int64) { //gd:SkeletonModification2DTwoBoneIK.set_joint_one_bone_idx
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_joint_one_bone_idx, 0|(gdextension.SizeInt<<4), &struct{ bone_idx int64 }{bone_idx})
}
func (self class) GetJointOneBoneIdx() int64 { //gd:SkeletonModification2DTwoBoneIK.get_joint_one_bone_idx
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_joint_one_bone_idx, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (self class) SetJointTwoBone2dNode(bone2d_node Path.ToNode) { //gd:SkeletonModification2DTwoBoneIK.set_joint_two_bone2d_node
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_joint_two_bone2d_node, 0|(gdextension.SizeNodePath<<4), &struct{ bone2d_node gdextension.NodePath }{pointers.Get(gd.InternalNodePath(bone2d_node))})
}
func (self class) GetJointTwoBone2dNode() Path.ToNode { //gd:SkeletonModification2DTwoBoneIK.get_joint_two_bone2d_node
	var r_ret = jumponly.Call[gdextension.NodePath](gd.ObjectChecked(self.AsObject()), methods.get_joint_two_bone2d_node, gdextension.SizeNodePath, &struct{}{})
	var ret = Path.ToNode(String.Via(gd.NodePathProxy{}, pointers.Pack(pointers.New[gd.NodePath](r_ret))))
	return ret
}
func (self class) SetJointTwoBoneIdx(bone_idx int64) { //gd:SkeletonModification2DTwoBoneIK.set_joint_two_bone_idx
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_joint_two_bone_idx, 0|(gdextension.SizeInt<<4), &struct{ bone_idx int64 }{bone_idx})
}
func (self class) GetJointTwoBoneIdx() int64 { //gd:SkeletonModification2DTwoBoneIK.get_joint_two_bone_idx
	var r_ret = jumponly.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_joint_two_bone_idx, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}
func (o class) AsSkeletonModification2DTwoBoneIK() Advanced         { return Advanced(o) }
func (o Instance) AsSkeletonModification2DTwoBoneIK() Instance      { return o }
func (o *Extension[T]) AsSkeletonModification2DTwoBoneIK() Instance { return o.Super() }
func (o class) AsSkeletonModification2D() SkeletonModification2D.Advanced {
	return *(*SkeletonModification2D.Advanced)(ie.As(&o))
}
func (o *Extension[T]) AsSkeletonModification2D() SkeletonModification2D.Instance {
	return o.Super().AsSkeletonModification2D()
}
func (o Instance) AsSkeletonModification2D() SkeletonModification2D.Instance {
	return *(*SkeletonModification2D.Instance)(ie.As(&o))
}
func (o class) AsResource() Resource.Advanced         { return *(*Resource.Advanced)(ie.As(&o)) }
func (o *Extension[T]) AsResource() Resource.Instance { return o.Super().AsResource() }
func (o Instance) AsResource() Resource.Instance      { return *(*Resource.Instance)(ie.As(&o)) }
func (o class) AsRefCounted() ie.RC                   { return *(*ie.RC)(ie.As(&o)) }
func (o *Extension[T]) AsRefCounted() ie.RC           { return o.Super().AsRefCounted() }
func (o Instance) AsRefCounted() ie.RC                { return *(*ie.RC)(ie.As(&o)) }

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(SkeletonModification2D.Advanced(self.AsSkeletonModification2D()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(SkeletonModification2D.Instance(self.AsSkeletonModification2D()), name)
	}
}
func init() {
	gdclass.Register("SkeletonModification2DTwoBoneIK", func(ptr gd.Object) any { return Instance{gdclass.NewSkeletonModification2DTwoBoneIK(ptr)} })
}
