// Code generated by the generate package DO NOT EDIT

/*
A container that accepts only two child controls, then arranges them horizontally or vertically and creates a divisor between them. The divisor can be dragged around to change the size relation between the child controls.
*/
package SplitContainer

import "reflect"
import "slices"
import "graphics.gd/internal/pointers"
import "graphics.gd/internal/callframe"
import "graphics.gd/internal/gdextension"
import "graphics.gd/internal/noescape"
import gd "graphics.gd/internal"
import "graphics.gd/internal/gdclass"
import "graphics.gd/variant"
import "graphics.gd/variant/Angle"
import "graphics.gd/variant/Euler"
import "graphics.gd/variant/Signal"
import "graphics.gd/classdb/CanvasItem"
import "graphics.gd/classdb/Container"
import "graphics.gd/classdb/Control"
import "graphics.gd/classdb/Node"
import "graphics.gd/variant/Array"
import "graphics.gd/variant/Callable"
import "graphics.gd/variant/Dictionary"
import "graphics.gd/variant/Error"
import "graphics.gd/variant/Float"
import "graphics.gd/variant/Object"
import "graphics.gd/variant/Packed"
import "graphics.gd/variant/Path"
import "graphics.gd/variant/RID"
import "graphics.gd/variant/RefCounted"
import "graphics.gd/variant/String"

var _ Object.ID

type _ gdclass.Node

var _ gd.Object
var _ RefCounted.Instance
var _ reflect.Type
var _ callframe.Frame
var _ = pointers.Cycle
var _ = Array.Nil
var _ variant.Any
var _ Callable.Function
var _ Dictionary.Any
var _ RID.Any
var _ noescape.Variant
var _ String.Readable
var _ Path.ToNode
var _ Packed.Bytes
var _ Error.Code
var _ Float.X
var _ Signal.Any
var _ Angle.Radians
var _ Euler.Radians
var _ gdextension.Object
var _ = slices.Delete[[]struct{}, struct{}]

/*
ID is a typed object ID (reference) to an instance of this class, use it to store references to objects with
unknown lifetimes, as an ID will not panic on use if the underlying object has been destroyed.
*/
type ID Object.ID

func (id ID) Instance() (Instance, bool) { return Object.As[Instance](Object.ID(id).Instance()) }

/*
Extension can be embedded in a new struct to create an extension of this class.
T should be the type that is embedding this [Extension]
*/
type Extension[T gdclass.Interface] struct{ gdclass.Extension[T, Instance] }

// Instance of the class with convieniently typed arguments and results.
type Instance [1]gdclass.SplitContainer

var otype gdextension.ObjectType
var sname gdextension.StringName
var methods struct {
	set_split_offset                         gdextension.MethodForClass `hash:"1286410249"`
	get_split_offset                         gdextension.MethodForClass `hash:"3905245786"`
	clamp_split_offset                       gdextension.MethodForClass `hash:"3218959716"`
	set_collapsed                            gdextension.MethodForClass `hash:"2586408642"`
	is_collapsed                             gdextension.MethodForClass `hash:"36873697"`
	set_dragger_visibility                   gdextension.MethodForClass `hash:"1168273952"`
	get_dragger_visibility                   gdextension.MethodForClass `hash:"967297479"`
	set_vertical                             gdextension.MethodForClass `hash:"2586408642"`
	is_vertical                              gdextension.MethodForClass `hash:"36873697"`
	set_dragging_enabled                     gdextension.MethodForClass `hash:"2586408642"`
	is_dragging_enabled                      gdextension.MethodForClass `hash:"36873697"`
	set_drag_area_margin_begin               gdextension.MethodForClass `hash:"1286410249"`
	get_drag_area_margin_begin               gdextension.MethodForClass `hash:"3905245786"`
	set_drag_area_margin_end                 gdextension.MethodForClass `hash:"1286410249"`
	get_drag_area_margin_end                 gdextension.MethodForClass `hash:"3905245786"`
	set_drag_area_offset                     gdextension.MethodForClass `hash:"1286410249"`
	get_drag_area_offset                     gdextension.MethodForClass `hash:"3905245786"`
	set_drag_area_highlight_in_editor        gdextension.MethodForClass `hash:"2586408642"`
	is_drag_area_highlight_in_editor_enabled gdextension.MethodForClass `hash:"36873697"`
	get_drag_area_control                    gdextension.MethodForClass `hash:"829782337"`
	set_touch_dragger_enabled                gdextension.MethodForClass `hash:"2586408642"`
	is_touch_dragger_enabled                 gdextension.MethodForClass `hash:"36873697"`
}

func init() {
	gd.Links = append(gd.Links, func() {
		sname = gdextension.Host.Strings.Intern.UTF8("SplitContainer")
		otype = gdextension.Host.Objects.Type(sname)
		gd.LinkMethods(sname, &methods, false)
	})
	gd.RegisterCleanup(func() {
		noescape.Free(gdextension.TypeStringName, &sname)
	})
}
func (self Instance) ID() ID { return ID(Object.Instance(self.AsObject()).ID()) }

// Nil is a nil/null instance of the class. Equivalent to the zero value.
var Nil Instance

type Any interface {
	gd.IsClass
	AsSplitContainer() Instance
}

/*
Clamps the [SplitOffset] value to not go outside the currently possible minimal and maximum values.

[SplitOffset]: https://pkg.go.dev/graphics.gd/classdb/SplitContainer#Instance.SplitOffset
*/
func (self Instance) ClampSplitOffset() { //gd:SplitContainer.clamp_split_offset
	Advanced(self).ClampSplitOffset()
}

/*
Returns the drag area [Control]. For example, you can move a pre-configured button into the drag area [Control] so that it rides along with the split bar. Try setting the [Button] anchors to center prior to the reparent() call.

	barnacleButton.AsNode().Reparent(splitContainer.GetDragAreaControl().AsNode())

Note: The drag area [Control] is drawn over the [SplitContainer]'s children, so [CanvasItem] draw objects called from the [Control] and children added to the [Control] will also appear over the [SplitContainer]'s children. Try setting [Control.MouseFilter] of custom children to [Control.MouseFilterIgnore] to prevent blocking the mouse from dragging if desired.

Warning: This is a required internal node, removing and freeing it may cause a crash.

[Button]: https://pkg.go.dev/graphics.gd/classdb/Button
[CanvasItem]: https://pkg.go.dev/graphics.gd/classdb/CanvasItem
[Control]: https://pkg.go.dev/graphics.gd/classdb/Control
[Control.MouseFilter]: https://pkg.go.dev/graphics.gd/classdb/Control#Instance.MouseFilter
[SplitContainer]: https://pkg.go.dev/graphics.gd/classdb/SplitContainer
*/
func (self Instance) GetDragAreaControl() Control.Instance { //gd:SplitContainer.get_drag_area_control
	return Control.Instance(Advanced(self).GetDragAreaControl())
}

// Advanced exposes a 1:1 low-level instance of the class, undocumented, for those who know what they are doing.
type Advanced = class
type class [1]gdclass.SplitContainer

func (self class) AsObject() [1]gd.Object { return self[0].AsObject() }
func (self *class) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = pointers.AsA[gdclass.SplitContainer](obj[0])
		return true
	}
	return false
}
func (self *Instance) SetObject(obj [1]gd.Object) bool {
	if gdextension.Host.Objects.Cast(gdextension.Object(pointers.Get(obj[0])[0]), otype) != 0 {
		self[0] = pointers.AsA[gdclass.SplitContainer](obj[0])
		return true
	}
	return false
}
func (self Instance) AsObject() [1]gd.Object      { return self[0].AsObject() }
func (self *Extension[T]) AsObject() [1]gd.Object { return self.Super().AsObject() }
func New() Instance {
	if !gd.Linked {
		var placeholder = Instance([1]gdclass.SplitContainer{pointers.Add[gdclass.SplitContainer]([3]uint64{})})
		gd.StartupFunctions = append(gd.StartupFunctions, func() {
			if gd.Linked {
				raw, _ := pointers.End(New().AsObject()[0])
				pointers.Set(pointers.AsA[gd.Object](placeholder[0]), raw)
				gd.RegisterCleanup(func() {
					if raw := pointers.Get[gd.Object](placeholder.AsObject()[0]); raw[0] != 0 && raw[1] == 0 {
						gdextension.Host.Objects.Unsafe.Free(gdextension.Object(raw[0]))
					}
				})
			}
		})
		return placeholder
	}
	casted := Instance([1]gdclass.SplitContainer{pointers.New[gdclass.SplitContainer]([3]uint64{uint64(gdextension.Host.Objects.Make(sname))})})
	casted.AsObject()[0].Notification(0, false)
	return casted
}

/*
The initial offset of the splitting between the two [Control]s, with 0 being at the end of the first [Control].

[Control]: https://pkg.go.dev/graphics.gd/classdb/Control
*/
func (self Instance) SplitOffset() int {
	return int(int(class(self).GetSplitOffset()))
}

// SetSplitOffset sets the property returned by [GetSplitOffset].
func (self Instance) SetSplitOffset(value int) {
	class(self).SetSplitOffset(int64(value))
}

/*
If true, the dragger will be disabled and the children will be sized as if the [SplitOffset] was 0.

[SplitOffset]: https://pkg.go.dev/graphics.gd/classdb/SplitContainer#Instance.SplitOffset
*/
func (self Instance) Collapsed() bool {
	return bool(class(self).IsCollapsed())
}

// SetCollapsed sets the property returned by [IsCollapsed].
func (self Instance) SetCollapsed(value bool) {
	class(self).SetCollapsed(value)
}

/*
Enables or disables split dragging.
*/
func (self Instance) DraggingEnabled() bool {
	return bool(class(self).IsDraggingEnabled())
}

// SetDraggingEnabled sets the property returned by [IsDraggingEnabled].
func (self Instance) SetDraggingEnabled(value bool) {
	class(self).SetDraggingEnabled(value)
}

/*
Determines the dragger's visibility. This property does not determine whether dragging is enabled or not. Use [DraggingEnabled] for that.

[DraggingEnabled]: https://pkg.go.dev/graphics.gd/classdb/SplitContainer#Instance.DraggingEnabled
*/
func (self Instance) DraggerVisibility() DraggerVisibility {
	return DraggerVisibility(class(self).GetDraggerVisibility())
}

// SetDraggerVisibility sets the property returned by [GetDraggerVisibility].
func (self Instance) SetDraggerVisibility(value DraggerVisibility) {
	class(self).SetDraggerVisibility(value)
}

/*
If true, the [SplitContainer] will arrange its children vertically, rather than horizontally.

Can't be changed when using [HSplitContainer] and [VSplitContainer].

[HSplitContainer]: https://pkg.go.dev/graphics.gd/classdb/HSplitContainer
[SplitContainer]: https://pkg.go.dev/graphics.gd/classdb/SplitContainer
[VSplitContainer]: https://pkg.go.dev/graphics.gd/classdb/VSplitContainer
*/
func (self Instance) Vertical() bool {
	return bool(class(self).IsVertical())
}

// SetVertical sets the property returned by [IsVertical].
func (self Instance) SetVertical(value bool) {
	class(self).SetVertical(value)
}

/*
If true, a touch-friendly drag handle will be enabled for better usability on smaller screens. Unlike the standard grabber, this drag handle overlaps the [SplitContainer]'s children and does not affect their minimum separation. The standard grabber will no longer be drawn when this option is enabled.

[SplitContainer]: https://pkg.go.dev/graphics.gd/classdb/SplitContainer
*/
func (self Instance) TouchDraggerEnabled() bool {
	return bool(class(self).IsTouchDraggerEnabled())
}

// SetTouchDraggerEnabled sets the property returned by [IsTouchDraggerEnabled].
func (self Instance) SetTouchDraggerEnabled(value bool) {
	class(self).SetTouchDraggerEnabled(value)
}

/*
Reduces the size of the drag area and split bar theme's 'split_bar_background' at the beginning of the container.
*/
func (self Instance) DragAreaMarginBegin() int {
	return int(int(class(self).GetDragAreaMarginBegin()))
}

// SetDragAreaMarginBegin sets the property returned by [GetDragAreaMarginBegin].
func (self Instance) SetDragAreaMarginBegin(value int) {
	class(self).SetDragAreaMarginBegin(int64(value))
}

/*
Reduces the size of the drag area and split bar theme's 'split_bar_background' at the end of the container.
*/
func (self Instance) DragAreaMarginEnd() int {
	return int(int(class(self).GetDragAreaMarginEnd()))
}

// SetDragAreaMarginEnd sets the property returned by [GetDragAreaMarginEnd].
func (self Instance) SetDragAreaMarginEnd(value int) {
	class(self).SetDragAreaMarginEnd(int64(value))
}

/*
Shifts the drag area in the axis of the container to prevent the drag area from overlapping the [ScrollBar] or other selectable [Control] of a child node.

[Control]: https://pkg.go.dev/graphics.gd/classdb/Control
[ScrollBar]: https://pkg.go.dev/graphics.gd/classdb/ScrollBar
*/
func (self Instance) DragAreaOffset() int {
	return int(int(class(self).GetDragAreaOffset()))
}

// SetDragAreaOffset sets the property returned by [GetDragAreaOffset].
func (self Instance) SetDragAreaOffset(value int) {
	class(self).SetDragAreaOffset(int64(value))
}

/*
Highlights the drag area [Rect2.PositionSize] so you can see where it is during development. The drag area is gold if [DraggingEnabled] is true, and red if false.

[DraggingEnabled]: https://pkg.go.dev/graphics.gd/classdb/SplitContainer#Instance.DraggingEnabled
[Rect2.PositionSize]: https://pkg.go.dev/graphics.gd/variant/Rect2#PositionSize
*/
func (self Instance) DragAreaHighlightInEditor() bool {
	return bool(class(self).IsDragAreaHighlightInEditorEnabled())
}

// SetDragAreaHighlightInEditor sets the property returned by [IsDragAreaHighlightInEditorEnabled].
func (self Instance) SetDragAreaHighlightInEditor(value bool) {
	class(self).SetDragAreaHighlightInEditor(value)
}

//go:nosplit
func (self class) SetSplitOffset(offset int64) { //gd:SplitContainer.set_split_offset
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_split_offset, 0|(gdextension.SizeInt<<4), &struct{ offset int64 }{offset})
}

//go:nosplit
func (self class) GetSplitOffset() int64 { //gd:SplitContainer.get_split_offset
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_split_offset, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}

/*
Clamps the [SplitOffset] value to not go outside the currently possible minimal and maximum values.

[SplitOffset]: https://pkg.go.dev/graphics.gd/classdb/SplitContainer#Instance.SplitOffset
*/
//go:nosplit
func (self class) ClampSplitOffset() { //gd:SplitContainer.clamp_split_offset
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.clamp_split_offset, 0, &struct{}{})
}

//go:nosplit
func (self class) SetCollapsed(collapsed bool) { //gd:SplitContainer.set_collapsed
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_collapsed, 0|(gdextension.SizeBool<<4), &struct{ collapsed bool }{collapsed})
}

//go:nosplit
func (self class) IsCollapsed() bool { //gd:SplitContainer.is_collapsed
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_collapsed, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}

//go:nosplit
func (self class) SetDraggerVisibility(mode DraggerVisibility) { //gd:SplitContainer.set_dragger_visibility
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_dragger_visibility, 0|(gdextension.SizeInt<<4), &struct{ mode DraggerVisibility }{mode})
}

//go:nosplit
func (self class) GetDraggerVisibility() DraggerVisibility { //gd:SplitContainer.get_dragger_visibility
	var r_ret = noescape.Call[DraggerVisibility](gd.ObjectChecked(self.AsObject()), methods.get_dragger_visibility, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}

//go:nosplit
func (self class) SetVertical(vertical bool) { //gd:SplitContainer.set_vertical
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_vertical, 0|(gdextension.SizeBool<<4), &struct{ vertical bool }{vertical})
}

//go:nosplit
func (self class) IsVertical() bool { //gd:SplitContainer.is_vertical
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_vertical, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}

//go:nosplit
func (self class) SetDraggingEnabled(dragging_enabled bool) { //gd:SplitContainer.set_dragging_enabled
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_dragging_enabled, 0|(gdextension.SizeBool<<4), &struct{ dragging_enabled bool }{dragging_enabled})
}

//go:nosplit
func (self class) IsDraggingEnabled() bool { //gd:SplitContainer.is_dragging_enabled
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_dragging_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}

//go:nosplit
func (self class) SetDragAreaMarginBegin(margin int64) { //gd:SplitContainer.set_drag_area_margin_begin
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_drag_area_margin_begin, 0|(gdextension.SizeInt<<4), &struct{ margin int64 }{margin})
}

//go:nosplit
func (self class) GetDragAreaMarginBegin() int64 { //gd:SplitContainer.get_drag_area_margin_begin
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_drag_area_margin_begin, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}

//go:nosplit
func (self class) SetDragAreaMarginEnd(margin int64) { //gd:SplitContainer.set_drag_area_margin_end
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_drag_area_margin_end, 0|(gdextension.SizeInt<<4), &struct{ margin int64 }{margin})
}

//go:nosplit
func (self class) GetDragAreaMarginEnd() int64 { //gd:SplitContainer.get_drag_area_margin_end
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_drag_area_margin_end, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}

//go:nosplit
func (self class) SetDragAreaOffset(offset int64) { //gd:SplitContainer.set_drag_area_offset
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_drag_area_offset, 0|(gdextension.SizeInt<<4), &struct{ offset int64 }{offset})
}

//go:nosplit
func (self class) GetDragAreaOffset() int64 { //gd:SplitContainer.get_drag_area_offset
	var r_ret = noescape.Call[int64](gd.ObjectChecked(self.AsObject()), methods.get_drag_area_offset, gdextension.SizeInt, &struct{}{})
	var ret = r_ret
	return ret
}

//go:nosplit
func (self class) SetDragAreaHighlightInEditor(drag_area_highlight_in_editor bool) { //gd:SplitContainer.set_drag_area_highlight_in_editor
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_drag_area_highlight_in_editor, 0|(gdextension.SizeBool<<4), &struct{ drag_area_highlight_in_editor bool }{drag_area_highlight_in_editor})
}

//go:nosplit
func (self class) IsDragAreaHighlightInEditorEnabled() bool { //gd:SplitContainer.is_drag_area_highlight_in_editor_enabled
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_drag_area_highlight_in_editor_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}

/*
Returns the drag area [Control]. For example, you can move a pre-configured button into the drag area [Control] so that it rides along with the split bar. Try setting the [Button] anchors to center prior to the reparent() call.


	barnacleButton.AsNode().Reparent(splitContainer.GetDragAreaControl().AsNode())


Note: The drag area [Control] is drawn over the [SplitContainer]'s children, so [CanvasItem] draw objects called from the [Control] and children added to the [Control] will also appear over the [SplitContainer]'s children. Try setting [Control.MouseFilter] of custom children to [Control.MouseFilterIgnore] to prevent blocking the mouse from dragging if desired.

Warning: This is a required internal node, removing and freeing it may cause a crash.

[Button]: https://pkg.go.dev/graphics.gd/classdb/Button
[CanvasItem]: https://pkg.go.dev/graphics.gd/classdb/CanvasItem
[Control]: https://pkg.go.dev/graphics.gd/classdb/Control
[Control.MouseFilter]: https://pkg.go.dev/graphics.gd/classdb/Control#Instance.MouseFilter
[SplitContainer]: https://pkg.go.dev/graphics.gd/classdb/SplitContainer
*/
//go:nosplit
func (self class) GetDragAreaControl() [1]gdclass.Control { //gd:SplitContainer.get_drag_area_control
	var r_ret = noescape.Call[gdextension.Object](gd.ObjectChecked(self.AsObject()), methods.get_drag_area_control, gdextension.SizeObject, &struct{}{})
	var ret = [1]gdclass.Control{gd.PointerLifetimeBoundTo[gdclass.Control](self.AsObject(), r_ret)}
	return ret
}

//go:nosplit
func (self class) SetTouchDraggerEnabled(enabled bool) { //gd:SplitContainer.set_touch_dragger_enabled
	noescape.Call[struct{}](gd.ObjectChecked(self.AsObject()), methods.set_touch_dragger_enabled, 0|(gdextension.SizeBool<<4), &struct{ enabled bool }{enabled})
}

//go:nosplit
func (self class) IsTouchDraggerEnabled() bool { //gd:SplitContainer.is_touch_dragger_enabled
	var r_ret = noescape.Call[bool](gd.ObjectChecked(self.AsObject()), methods.is_touch_dragger_enabled, gdextension.SizeBool, &struct{}{})
	var ret = r_ret
	return ret
}

/*
Emitted when the dragger is dragged by user.
*/
func (self Instance) OnDragged(cb func(offset int), flags ...Signal.Flags) {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	self[0].AsObject()[0].Connect(gd.NewStringName("dragged"), gd.NewCallable(cb), int64(flags_together))
}

func (self class) Dragged() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`Dragged`))))
}

/*
Emitted when the user starts dragging.
*/
func (self Instance) OnDragStarted(cb func(), flags ...Signal.Flags) {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	self[0].AsObject()[0].Connect(gd.NewStringName("drag_started"), gd.NewCallable(cb), int64(flags_together))
}

func (self class) DragStarted() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`DragStarted`))))
}

/*
Emitted when the user ends dragging.
*/
func (self Instance) OnDragEnded(cb func(), flags ...Signal.Flags) {
	var flags_together Signal.Flags
	for _, flag := range flags {
		flags_together |= flag
	}
	self[0].AsObject()[0].Connect(gd.NewStringName("drag_ended"), gd.NewCallable(cb), int64(flags_together))
}

func (self class) DragEnded() Signal.Any {
	return Signal.Via(gd.SignalProxy{}, pointers.Pack(gd.NewSignalOf(self.AsObject(), gd.NewStringName(`DragEnded`))))
}

func (self class) AsSplitContainer() Advanced {
	return Advanced{pointers.AsA[gdclass.SplitContainer](self[0])}
}
func (self Instance) AsSplitContainer() Instance {
	return Instance{pointers.AsA[gdclass.SplitContainer](self[0])}
}
func (self *Extension[T]) AsSplitContainer() Instance { return self.Super().AsSplitContainer() }
func (self class) AsContainer() Container.Advanced {
	return Container.Advanced{pointers.AsA[gdclass.Container](self[0])}
}
func (self *Extension[T]) AsContainer() Container.Instance { return self.Super().AsContainer() }
func (self Instance) AsContainer() Container.Instance {
	return Container.Instance{pointers.AsA[gdclass.Container](self[0])}
}
func (self class) AsControl() Control.Advanced {
	return Control.Advanced{pointers.AsA[gdclass.Control](self[0])}
}
func (self *Extension[T]) AsControl() Control.Instance { return self.Super().AsControl() }
func (self Instance) AsControl() Control.Instance {
	return Control.Instance{pointers.AsA[gdclass.Control](self[0])}
}
func (self class) AsCanvasItem() CanvasItem.Advanced {
	return CanvasItem.Advanced{pointers.AsA[gdclass.CanvasItem](self[0])}
}
func (self *Extension[T]) AsCanvasItem() CanvasItem.Instance { return self.Super().AsCanvasItem() }
func (self Instance) AsCanvasItem() CanvasItem.Instance {
	return CanvasItem.Instance{pointers.AsA[gdclass.CanvasItem](self[0])}
}
func (self class) AsNode() Node.Advanced         { return Node.Advanced{pointers.AsA[gdclass.Node](self[0])} }
func (self *Extension[T]) AsNode() Node.Instance { return self.Super().AsNode() }
func (self Instance) AsNode() Node.Instance {
	return Node.Instance{pointers.AsA[gdclass.Node](self[0])}
}

func (self class) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Container.Advanced(self.AsContainer()), name)
	}
}

func (self Instance) Virtual(name string) reflect.Value {
	switch name {
	default:
		return gd.VirtualByName(Container.Instance(self.AsContainer()), name)
	}
}
func init() {
	gdclass.Register("SplitContainer", func(ptr gd.Object) any { return Instance{pointers.AsA[gdclass.SplitContainer](ptr)} })
}

type DraggerVisibility int //gd:SplitContainer.DraggerVisibility

const (
	// The split dragger icon is always visible when theme's 'autohide' is false, otherwise visible only when the cursor hovers it.
	//
	// The size of the grabber icon determines the minimum theme's 'separation'.
	//
	// The dragger icon is automatically hidden if the length of the grabber icon is longer than the split bar.
	DraggerVisible DraggerVisibility = 0
	// The split dragger icon is never visible regardless of the value of theme's 'autohide'.
	//
	// The size of the grabber icon determines the minimum theme's 'separation'.
	DraggerHidden DraggerVisibility = 1
	// The split dragger icon is not visible, and the split bar is collapsed to zero thickness.
	DraggerHiddenCollapsed DraggerVisibility = 2
)
